### ISSUE TITLE
crashes when opening the notification page

### ISSUE THREAD

**Issue by qorron** [SickGear/SickGear#1000]
#### Branch version commit hash: d9216d0b893c0acf7f8210adba61873ab8eec5c8

when going to the notifications page in the config, this happens:

```
Error

cannot import name NotifierFactory

Traceback

Traceback (most recent call last): 
File "/opt/sickgear/lib/tornado/web.py", line 1511, in _execute result = yield result 
File "/opt/sickgear/lib/tornado/gen.py", line 1055, in run value = future.result() 
File "/opt/sickgear/lib/tornado/concurrent.py", line 238, in result raise_exc_info(self._exc_info) 
File "/opt/sickgear/lib/tornado/gen.py", line 292, in wrapper result = func(*args, **kwargs) 
File "/opt/sickgear/sickbeard/webserve.py", line 319, in get result = method(**kwargss) 
File "/opt/sickgear/sickbeard/webserve.py", line 5702, in index discordapp_notify_onsubtitledownload=None, discordapp_access_token=None, 
File "/opt/sickgear/sickbeard/webserve.py", line 112, in __init__ super(PageTemplate, self).__init__(*args, **kwargs) 
File "/opt/sickgear/.pyenv/versions/2.7.12/lib/python2.7/site-packages/Cheetah/Template.py", line 1259, in __init__ self._compile(source, file, compilerSettings=compilerSettings) 
File "/opt/sickgear/.pyenv/versions/2.7.12/lib/python2.7/site-packages/Cheetah/Template.py", line 1553, in _compile keepRefToGeneratedCode=True) 
File "/opt/sickgear/sickbeard/webserve.py", line 120, in compile return super(PageTemplate, self).compile(*args, **kwargs) 
File "/opt/sickgear/.pyenv/versions/2.7.12/lib/python2.7/site-packages/Cheetah/Template.py", line 788, in compile exec(co, mod.__dict__) 
File "/home/sickgear/data/cache/cheetah/cheetah__opt_sickgear_gui_slick_interfaces_default_config_notifications_tmpl_1509189187_42_16538.py", line 31, in from sickbeard.notifiers import NotifierFactory 
ImportError: cannot import name NotifierFactory 
```

also, when changing back to 'master' that happens: (change to master went through though)

```
Error

'bool' object has no attribute '__getitem__'

Traceback

Traceback (most recent call last): 
File "/opt/sickgear/lib/tornado/web.py", line 1511, in _execute result = yield result 
File "/opt/sickgear/lib/tornado/gen.py", line 1055, in run value = future.result() 
File "/opt/sickgear/lib/tornado/concurrent.py", line 238, in result raise_exc_info(self._exc_info) 
File "/opt/sickgear/lib/tornado/gen.py", line 292, in wrapper result = func(*args, **kwargs) 
File "/opt/sickgear/sickbeard/webserve.py", line 319, in get result = method(**kwargss) 
File "/opt/sickgear/sickbeard/webserve.py", line 1239, in branchCheckout if showObj is None: 
File "/opt/sickgear/sickbeard/webserve.py", line 1230, in update return json.dumps({'success': t.respond()}) 
File "/opt/sickgear/sickbeard/version_checker.py", line 115, in update return self.updater.update() 
File "/opt/sickgear/sickbeard/version_checker.py", line 414, in update return True 
File "/opt/sickgear/sickbeard/notifiers/__init__.py", line 110, in notify_git_update for n in filter(lambda v: v.is_enabled() and v.is_enabled_library(), self.notifiers.values()): 
File "/opt/sickgear/sickbeard/notifiers/slack.py", line 63, in notify_git_update 
File "/opt/sickgear/sickbeard/notifiers/slack.py", line 46, in _notify_str 
File "/opt/sickgear/sickbeard/notifiers/slack.py", line 40, in _notify json=True) 
TypeError: 'bool' object has no attribute '__getitem__' 
```

the notification page works on the current master branch.
the crash while changing branches happens regardless of the change direction. i.e. master->dev and dev-> master alike.

**Comment by JackDandy** [comment]
In your browser come to : https://gitter.im/SickGear/Lobby

**Comment by JackDandy** [comment]
This was found to be an issue of the OS, after a reboot, everything was fine.
