### ISSUE TITLE
Manage snatched throws error

### ISSUE THREAD

**Issue by barbequesauce** [SickGear/SickGear#1023]
#### Branch version commit hash: (See the About page) 709c7c2c5ceb3a7b32f403aa7e4a34d97a52f80e

Expectation | Result
------------ | -------------
Snatched episodes are reset to failed. | error thrown.

**Steps to reproduce:**
*1)* from episode status screen, select snatched shows
*2)* Select all, then set checked shows status to failed and click go

```
Error

level must be an integer

Traceback

Traceback (most recent call last): 
File "/opt/sickgear/lib/tornado/web.py", line 1511, in _execute result = yield result 
File "/opt/sickgear/lib/tornado/gen.py", line 1055, in run value = future.result() 
File "/opt/sickgear/lib/tornado/concurrent.py", line 238, in result raise_exc_info(self._exc_info) 
File "/opt/sickgear/lib/tornado/gen.py", line 292, in wrapper result = func(*args, **kwargs) 
File "/opt/sickgear/sickbeard/webserve.py", line 312, in get result = method(**kwargss) 
File "/opt/sickgear/sickbeard/webserve.py", line 4052, in changeEpisodeStatuses newStatus, direct=True) 
File "/opt/sickgear/sickbeard/webserve.py", line 2251, in setStatus (showObj.name, season)) 
File "/opt/sickgear/sickbeard/logger.py", line 321, in log sb_log_instance.log(to_log, log_level) 
File "/opt/sickgear/sickbeard/logger.py", line 176, in log sb_logger.log(log_level, out_line) 
File "/opt/sickgear/.pyenv/versions/2.7.13/lib/python2.7/logging/__init__.py", line 1227, in log raise TypeError("level must be an integer") 
TypeError: level must be an integer 

Request Info

body: oldStatus=2&newStatus=11&wantedStatus=-1&81386-all=on&196921-all=on&253463-all=on&295759-all=on&328552-all=on
files: {}
protocol: http
connection: 
body_arguments: {'295759-all': ['on'], '196921-all': ['on'], 'newStatus': ['11'], 'oldStatus': ['2'], '81386-all': ['on'], 'wantedStatus': ['-1'], '328552-all': ['on'], '253463-all': ['on']}
uri: /sickgear/manage/changeEpisodeStatuses
query_arguments: {}
_start_time: 1512527854.12
headers: Origin: http://pi.local:9094 Content-Length: 109 Accept-Language: en-us Accept-Encoding: gzip, deflate Connection: keep-alive Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 User-Agent: Mozilla/5.0 (iPad; CPU OS 11_1_2 like Mac OS X) AppleWebKit/604.3.5 (KHTML, like Gecko) Version/11.0 Mobile/15B202 Safari/604.1 Host: pi.local:9094 Referer: http://pi.local:9094/sickgear/manage/episodeStatuses?whichStatus=2 Cookie: jqCookieJar_sg={%22theme%22:%22dark%22}; session=86735658c563ee59f9d3aa86c7aa5587b2408b59; movie_layout=compact%20striped Upgrade-Insecure-Requests: 1 Content-Type: application/x-www-form-urlencoded 
host: pi.local:9094
version: HTTP/1.1
server_connection: 
host_name: pi.local
_finish_time: None
query: 
arguments: {'295759-all': 'on', '196921-all': 'on', 'newStatus': '11', 'oldStatus': '2', '81386-all': 'on', 'wantedStatus': '-1', '328552-all': 'on', '253463-all': 'on'}
path: /sickgear/manage/changeEpisodeStatuses
method: POST
remote_ip: 10.0.1.48
```

**Comment by JackDandy** [comment]
I think this occurred due to stale page used before the button was clicked, please confirm

**Comment by JackDandy** [comment]
Can you come to IRC
