### ISSUE TITLE
Show/Folder does not exist

### ISSUE THREAD

**Issue by rbhamilton** [SickGear/SickGear#1042]
**Please don't close this thread until it is really resolved.**  

I've tried all the suggestions so far and they do NOT solve the problem.  How would you like it if you called up Best Buy and the Geek Squad said "try rebooting - case closed - click".  That's jo help at all.  If you don't have another answer that's fine.  Nobody expects you to be able to solve everything.  But please leave the case open so other people can assist if they wish.

After I process I get a Show/Folder does not exist error.

Here's the suggestions so far and the reason they are not a solution:

"Look in Finished Downloads and check the shows for any file that exist in there."
 - Because I use COPY all the files remain in the finished files folder after processing so I can't use that as an indication of which show failed.

"Look at your showlist, then make sure for each show, that a folder exists at parent folder"
 - Done.  Each show has a folder.  I've also checked all the show paths - nothing in red.

"Do "media process" and check the output for a failure."
 - Done - result below - which folder is the issue?  I can't tell from the output.  Can you?

Any idea How I can I tell which show and/or Path is causing trouble? 

Thanks in advance for any assistance and thanks for not just saying "Case closed".

This is the log I've got:

Error
Show folder doesn't exist, you shouldn't be using it

Traceback
Traceback (most recent call last):
File "C:\SickGear\SickGear\lib\tornado\web.py", line 1511, in _execute result = yield result
File "C:\SickGear\SickGear\lib\tornado\gen.py", line 1055, in run value = future.result()
File "C:\SickGear\SickGear\lib\tornado\concurrent.py", line 238, in result raise_exc_info(self._exc_info)
File "C:\SickGear\SickGear\lib\tornado\gen.py", line 292, in wrapper result = func(*args, **kwargs)
File "C:\SickGear\SickGear\sickbeard\webserve.py", line 319, in get result = method(**kwargss)
File "C:\SickGear\SickGear\sickbeard\webserve.py", line 2538, in processEpisode showObj=showObj, is_basedir=is_basedir in ['on', '1'])
File "C:\SickGear\SickGear\sickbeard\processTV.py", line 954, in processDir dir_name, nzb_name, process_method, force, force_replace, failed, type, cleanup, showObj)
File "C:\SickGear\SickGear\sickbeard\processTV.py", line 397, in process_dir self.check_video_filenames(walk_dir, video_pick)))
File "C:\SickGear\SickGear\sickbeard\processTV.py", line 873, in _process_media file_success = processor.process()
File "C:\SickGear\SickGear\sickbeard\postProcessor.py", line 916, in process if not ek.ek(os.path.isdir, ep_obj.show.location) and sickbeard.CREATE_MISSING_SHOW_DIRS:
File "C:\SickGear\SickGear\sickbeard\tv.py", line 293, in _getLocation raise exceptions.ShowDirNotFoundException('Show folder doesn't exist, you shouldn't be using it')
ShowDirNotFoundException: Show folder doesn't exist, you shouldn't be using it

Request Info
body: type=manual&dir=G%3A%5CFinished+Downloads&process_method=copy&force=on
files: {}
protocol: http
connection:
body_arguments: {'type': ['manual'], 'force': ['on'], 'dir': ['G:\Finished Downloads'], 'process_method': ['copy']}
uri: /home/postprocess/processEpisode
query_arguments: {}
_start_time: 1516822314.06
headers: Origin: http://localhost:2828 Content-Length: 70 Accept-Language: en-US,en;q=0.9 Accept-Encoding: gzip, deflate, br Connection: keep-alive Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,/;q=0.8 Upgrade-Insecure-Requests: 1 Dnt: 1 Host: localhost:2828 Referer: http://localhost:2828/home/postprocess/ Cache-Control: max-age=0 Cookie: snatched_view=list; soon_view=thumb; suggest_view=thumb; late_view=list; blu_ray_com_new_releases_view=thumb; imdb_box_office_view=thumb; imdb_top_dvd_rentals_view=thumb; wanted_view=thumb; sickgear-session-579aafd3ceeb1bdc2914e3bb139aeda1="2|1:0|10:1516821364|49:sickgear-session-579aafd3ceeb1bdc2914e3bb139aeda1|60:RFppSWlCL01SbnlMSlo1MUZqTDZvVC9Eeng2YTVFekJpMHczRjJzVTZiTT0=|b887dca1b970835c5c42cd91585c53b109712e0b9efa1d4678a25a0beab2dac5" User-Agent: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36 Content-Type: application/x-www-form-urlencoded
host: localhost:2828
version: HTTP/1.1
server_connection:
host_name: localhost
_finish_time: None
query:
arguments: {'force': 'on', 'type': 'manual', 'dir': 'G:\Finished Downloads', 'process_method': 'copy'}
path: /home/postprocess/processEpisode
_cookies: Set-Cookie: blu_ray_com_new_releases_view=thumb Set-Cookie: imdb_box_office_view=thumb Set-Cookie: imdb_top_dvd_rentals_view=thumb Set-Cookie: late_view=list Set-Cookie: sickgear-session-579aafd3ceeb1bdc2914e3bb139aeda1="2|1:0|10:1516821364|49:sickgear-session-579aafd3ceeb1bdc2914e3bb139aeda1|60:RFppSWlCL01SbnlMSlo1MUZqTDZvVC9Eeng2YTVFekJpMHczRjJzVTZiTT0=|b887dca1b970835c5c42cd91585c53b109712e0b9efa1d4678a25a0beab2dac5" Set-Cookie: snatched_view=list Set-Cookie: soon_view=thumb Set-Cookie: suggest_view=thumb Set-Cookie: wanted_view=thumb
method: POST
remote_ip: 127.0.0.1

**Comment by JackDandy** [comment]
Please do not tell us how to run our issues.
