### ISSUE TITLE
[Errno 13] Permission denied

### ISSUE THREAD

**Issue by ranthonissen** [SickGear/SickGear#1059]
#### Branch version commit hash: 5c94105

I got this error in SickGear on Synology after the last upgrade:

<pre>
File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1614, in freespace storage = os.statvfs(path)
</pre>

I had to manually go back to release_0.13.8 (c1b3056) to get SickGear working again.

Full error log:
<pre>
Error
[Errno 13] Permission denied: '/volume1/video/Series'

Traceback
Traceback (most recent call last): 
File "/usr/local/sickbeard-custom/var/SickBeard/lib/tornado/web.py", line 1511, in _execute result = yield result 
File "/usr/local/sickbeard-custom/var/SickBeard/lib/tornado/gen.py", line 1055, in run value = future.result() 
File "/usr/local/sickbeard-custom/var/SickBeard/lib/tornado/concurrent.py", line 238, in result raise_exc_info(self._exc_info) 
File "/usr/local/sickbeard-custom/var/SickBeard/lib/tornado/gen.py", line 292, in wrapper result = func(*args, **kwargs) 
File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 323, in get result = method(**kwargss) 
File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 4767, in index return t.respond() 
File "/usr/local/sickbeard-custom/var/cache/cheetah/cheetah__usr_local_sickbeard_custom_var_SickBeard_gui_slick_interfaces_default_history_tmpl_1518003743_91_15361.py", line 535, in respond self._handleCheetahInclude(VFN(VFFSL(SL,"os.path",True),"join",False)(VFFSL(SL,"sg_str",False)('PROG_DIR'), 'gui/slick/interfaces/default/inc_bottom.tmpl'), trans=trans, includeFrom="file", raw=False) 
File "/usr/local/python/lib/python2.7/site-packages/Cheetah/Template.py", line 1615, in _handleCheetahInclude self._CHEETAH__cheetahIncludes[_includeID].respond(trans) 
File "cheetah__usr_local_sickbeard_custom_var_SickBeard_gui_slick_interfaces_default_inc_bottom_tmpl_1518003754_26_65355.py", line 130, in respond 
File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1585, in df free = freespace(path) 
File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1614, in freespace storage = os.statvfs(path) 
OSError: [Errno 13] Permission denied: '/volume1/video/Series' 
</pre>

**Comment by JackDandy** [comment]
Hi,

try: in the ui, go to `/config/general/` and disable the feature `Display freespace`

is that ok?

**Comment by ranthonissen** [comment]
I didn't have feature (because it was introduced in a newer version?)
So I update manually to master, but then the error screen appeared again, and I couldn't open de management screens.

**Comment by JackDandy** [comment]
Fixed: https://github.com/SickGear/SickGear/releases/tag/release_0.14.2

**Comment by ranthonissen** [comment]
After updating to release release_0.14.2 it works again
Thanks!
