### ISSUE TITLE
Server returned status 500

### ISSUE THREAD

**Issue by Th3MadHatter** [SickGear/SickGear#1062]
BRANCH: develop / COMMIT: 875530ce5a6f2b9df718d93236a87e22c6ab2279

This just happens every now and then when an (external) post process request is sent, log will be more useful then my comments

**Steps to reproduce:**
*1)* cause (external) post process trigger
*2)* Error occurs.

```
2018-02-13 11:10:43 ERROR    TORNADO.APP :: Uncaught exception GET /home/postprocess/processEpisode?proc_type=manual&nzbName=American.Dad.S14.720p.WEB-DL.DD5.1.H.264-Group&quiet=1&dir=T%3A%5CProcess%5Ctv%5CAmerican.Dad.S14.720p.WEB-DL.DD5.1.H.264-Group(127.0.0.1)
 1) HTTPServerRequest(protocol='http', host='localhost:53321', method='GET', uri='/home/postprocess/processEpisode?proc_type=manual&nzbName=American.Dad.S14.720p.WEB-DL.DD5.1.H.264-Group&quiet=1&dir=T%3A%5CProcess%5Ctv%5CAmerican.Dad.S14.720p.WEB-DL.DD5.1.H.264-Group, version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:53321', 'Accept': '*/*', 'User-Agent': 'python-requests/2.7.0 CPython/2.7.13 Windows/10', 'Connection': 'keep-alive', 'Cookie': 'sickgear-session-331fe53cd94e24afea221a0ef965e0652="2|1:0|10:1518516623|49:sickgear-session-331fe53cd94e24afea221a0ef965e0652|60:L0VHS3cyeThRbEZ0dVY4ZHBpSFNzOG5rWkpzS241V0I0RmVybz0=|3776d2d4aa21b6c8e2b2bbf07a45dfeef27da83e65a2134ac730feb7cf41b42f"', 'Authorization': 'Basic EE2lej2JlLYJkoq=='})
 2) Traceback (most recent call last):
 3)   File "C:\SickGear\SickGear\lib\tornado\web.py", line 1511, in _execute
 4)     result = yield result
 5)   File "C:\SickGear\SickGear\lib\tornado\gen.py", line 1055, in run
 6)     value = future.result()
 7)   File "C:\SickGear\SickGear\lib\tornado\concurrent.py", line 238, in result
 8)     raise_exc_info(self._exc_info)
 9)   File "C:\SickGear\SickGear\lib\tornado\gen.py", line 292, in wrapper
10)     result = func(*args, **kwargs)
11)   File "C:\SickGear\SickGear\sickbeard\webserve.py", line 335, in get
12)     result = method(**kwargss)
13)   File "C:\SickGear\SickGear\sickbeard\webserve.py", line 2560, in processEpisode
14)     skip_failure_processing=skip_failure_processing)
15)   File "C:\SickGear\SickGear\sickbeard\processTV.py", line 960, in processDir
16)     dir_name, nzb_name, process_method, force, force_replace, failed, type, cleanup, showObj)
17)   File "C:\SickGear\SickGear\sickbeard\processTV.py", line 398, in process_dir
18)     self.check_video_filenames(walk_dir, video_pick)))
19)   File "C:\SickGear\SickGear\sickbeard\processTV.py", line 874, in _process_media
20)     file_success = processor.process()
21)   File "C:\SickGear\SickGear\sickbeard\postProcessor.py", line 926, in process
22)     ep_obj.show.writeMetadata(True)
23)   File "C:\SickGear\SickGear\sickbeard\tv.py", line 472, in writeMetadata
24)     self.getImages()
25)   File "C:\SickGear\SickGear\sickbeard\tv.py", line 725, in getImages
26)     season_posters_result = cur_provider.create_season_posters(self) or season_posters_result
27)   File "C:\SickGear\SickGear\sickbeard\metadata\generic.py", line 356, in create_season_posters
28)     result = result + [self.save_season_posters(show_obj, season)]
29)   File "C:\SickGear\SickGear\sickbeard\metadata\generic.py", line 616, in save_season_posters
30)     season_dict = self._season_image_dict(show_obj, season, 'seasons')
31)   File "C:\SickGear\SickGear\sickbeard\metadata\generic.py", line 872, in _season_image_dict
32)     t = sickbeard.indexerApi(show_obj.indexer).indexer(**lINDEXER_API_PARMS)
33)   File "C:\SickGear\SickGear\sickbeard\indexers\indexer_api.py", line 89, in indexer
34)     return indexerConfig[self.indexerID]['module'](*args, **kwargs)
35)   File "C:\SickGear\SickGear\lib\tvdb_api\tvdb_api.py", line 506, in __init__
36)     raise ValueError('Invalid language %s, options are: %s' % (language, self.config['valid_languages']))
37) ValueError: Invalid language , options are: ['da', 'fi', 'nl', 'de', 'it', 'es', 'fr', 'pl', 'hu', 'el', 'tr', 'ru', 'he', 'ja', 'pt', 'zh', 'cs', 'sl', 'hr', 'ko', 'en', 'sv', 'no']
```

Additional notes:
Running it manually about 10 minutes later gave no such errors.

**Comment by JackDandy** [comment]
This is now handled in release_0.14.3
