### ISSUE TITLE
Fatal error while attempting to change episode status from "skipped" to "wanted" in bulk.

### ISSUE THREAD

**Issue by funar** [SickGear/SickGear#1069]
#### Branch version commit hash: 5cb04b0802077a945d9def396872798d3f917114

Expectation | Result
------------ | -------------
Modify episode status, in bulk, from "skipped" to "wanted." | Episodes change status.

**Steps to reproduce:**
*1)* Click Manage -> Episode Status
*2)* Change drop down for "Manage episode with status to "Skipped"
*3)* Click "Manage" Wait for results
*4)* Click episodes/shows to be changed, or "select all"
*5)* Change drop-down for "Override checked status" to "Wanted"
*6)* Click "Go" next to "Wanted" drop-down box.
*7)* Observe error.

Either a link to gist (best as they are easily deleted) or log text wrapped in "pre" tags
<pre>
Error
argument of type 'int' is not iterable

Traceback
Traceback (most recent call last): 
File "X:\SickGear\lib\tornado\web.py", line 1511, in _execute result = yield result 
File "X:\SickGear\lib\tornado\gen.py", line 1055, in run value = future.result() 
File "X:\SickGear\lib\tornado\concurrent.py", line 238, in result raise_exc_info(self._exc_info) 
File "X:\SickGear\lib\tornado\gen.py", line 292, in wrapper result = func(*args, **kwargs) 
File "X:\SickGear\sickbeard\webserve.py", line 323, in get result = method(**kwargss) 
File "X\SickGear\sickbeard\webserve.py", line 3999, in changeEpisodeStatuses newStatus, direct=True) 
File "X:\SickGear\sickbeard\webserve.py", line 2084, in setStatus if '-' in status: 
TypeError: argument of type 'int' is not iterable 
</pre>

Additional notes:
Thanks for all the work you've put into this!

**Comment by JackDandy** [comment]
[Fixed](https://github.com/SickGear/SickGear/releases/tag/release_0.14.8)
