### ISSUE TITLE
TypeError: expected string or buffer [ettv provider]

### ISSUE THREAD

**Issue by tomasparks** [SickGear/SickGear#1085]
BRANCH: develop / COMMIT: 7567f04872b281502dbd88d2e8b10522fd7120fd
Python Version: | 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]
Raspberry Pi 3B+

<pre>
2018-04-17 02:56:59 BACKLOG-328724 :: Traceback (most recent call last):
  File "/media/disk/programs/SickGear/sickbeard/search_queue.py", line 469, in run
    scheduled=self.standard_backlog)
  File "/media/disk/programs/SickGear/sickbeard/search.py", line 754, in search_providers
    best_result.url = best_result.get_data_func(best_result.url)
  File "/media/disk/programs/SickGear/sickbeard/providers/ettv.py", line 119, in get_data
    result = re.findall('(?i)"(magnet:[^"]+?)">', html)[0]
  File "/usr/lib/python2.7/re.py", line 181, in findall
    return _compile(pattern, flags).findall(string)
TypeError: expected string or buffer

2018-04-17 02:56:32 BACKLOG-277165 :: Traceback (most recent call last):
  File "/media/disk/programs/SickGear/sickbeard/search_queue.py", line 469, in run
    scheduled=self.standard_backlog)
  File "/media/disk/programs/SickGear/sickbeard/search.py", line 754, in search_providers
    best_result.url = best_result.get_data_func(best_result.url)
  File "/media/disk/programs/SickGear/sickbeard/providers/ettv.py", line 119, in get_data
    result = re.findall('(?i)"(magnet:[^"]+?)">', html)[0]
  File "/usr/lib/python2.7/re.py", line 181, in findall
    return _compile(pattern, flags).findall(string)
TypeError: expected string or buffer

2018-04-17 02:56:27 BACKLOG-248835 :: Traceback (most recent call last):
  File "/media/disk/programs/SickGear/sickbeard/search_queue.py", line 469, in run
    scheduled=self.standard_backlog)
  File "/media/disk/programs/SickGear/sickbeard/search.py", line 754, in search_providers
    best_result.url = best_result.get_data_func(best_result.url)
  File "/media/disk/programs/SickGear/sickbeard/providers/ettv.py", line 119, in get_data
    result = re.findall('(?i)"(magnet:[^"]+?)">', html)[0]
  File "/usr/lib/python2.7/re.py", line 181, in findall
    return _compile(pattern, flags).findall(string)
TypeError: expected string or buffer

2018-04-17 02:55:23 BACKLOG-266967 :: Traceback (most recent call last):
  File "/media/disk/programs/SickGear/sickbeard/search_queue.py", line 469, in run
    scheduled=self.standard_backlog)
  File "/media/disk/programs/SickGear/sickbeard/search.py", line 754, in search_providers
    best_result.url = best_result.get_data_func(best_result.url)
  File "/media/disk/programs/SickGear/sickbeard/providers/ettv.py", line 119, in get_data
    result = re.findall('(?i)"(magnet:[^"]+?)">', html)[0]
  File "/usr/lib/python2.7/re.py", line 181, in findall
    return _compile(pattern, flags).findall(string)
TypeError: expected string or buffer

2018-04-17 02:55:19 BACKLOG-75692 :: Traceback (most recent call last):
  File "/media/disk/programs/SickGear/sickbeard/search_queue.py", line 469, in run
    scheduled=self.standard_backlog)
  File "/media/disk/programs/SickGear/sickbeard/search.py", line 754, in search_providers
    best_result.url = best_result.get_data_func(best_result.url)
  File "/media/disk/programs/SickGear/sickbeard/providers/ettv.py", line 119, in get_data
    result = re.findall('(?i)"(magnet:[^"]+?)">', html)[0]
  File "/usr/lib/python2.7/re.py", line 181, in findall
    return _compile(pattern, flags).findall(string)
TypeError: expected string or buffer
</pre>

**Comment by JackDandy** [comment]
Thanks for the report, [fixed](https://github.com/SickGear/SickGear/releases/tag/release_0.15.12) and merged to develop.
