### ISSUE TITLE
Uncaught exception GET /home/discover_emby (10.0.1.3)

### ISSUE THREAD

**Issue by kitten77** [SickGear/SickGear#1087]
Version:	BRANCH: develop / COMMIT: 1952f050478e460bfabf4ea8b739e771f4a41ebb
This is BETA software

13:46:39 ERROR TORNADO.APP :: Uncaught exception GET /home/discover_emby (10.0.1.3)
HTTPServerRequest(protocol='http', host='localhost:8081', method='GET', uri='/home/discover_emby', version='HTTP/1.1', remote_ip='10.0.1.3')
Traceback (most recent call last):
  File "/usr/home/sickgear/SickGear/lib/tornado/web.py", line 1543, in _execute
    result = yield result
  File "/usr/home/sickgear/SickGear/lib/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/home/sickgear/SickGear/lib/tornado/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "/usr/home/sickgear/SickGear/lib/tornado/gen.py", line 307, in wrapper
    result = func(*args, **kwargs)
  File "/usr/home/sickgear/SickGear/sickbeard/webserve.py", line 651, in get
    result = method(**kwargss)
  File "/usr/home/sickgear/SickGear/sickbeard/webserve.py", line 1282, in discover_emby
    return notifiers.NotifierFactory().get('EMBY').discover_server()
  File "/usr/home/sickgear/SickGear/sickbeard/notifiers/emby.py", line 179, in discover_server
    return self._discover_server()
  File "/usr/home/sickgear/SickGear/sickbeard/notifiers/emby.py", line 106, in _discover_server
    cs.shutdown(SHUT_RDWR)
  File "/usr/local/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 57] Socket is not connected
Exception in thread Q-EMBY-WATCHED:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/home/sickgear/SickGear/sickbeard/watchedstate_queue.py", line 69, in run
    History.update_watched_state_emby()
  File "/usr/home/sickgear/SickGear/sickbeard/webserve.py", line 5357, in update_watched_state_emby
    for user_id in [u.get('Id') for u in users if u.get('Id')]:
TypeError: 'NoneType' object is not iterable

**Comment by kitten77** [comment]
This one is weird cause emby reports that we could notify

**Comment by kitten77** [comment]
HTTPServerRequest(protocol='http', host='localhost:8081', method='GET', uri='/home/discover_emby', version='HTTP/1.1', remote_ip='10.0.1.3')
Traceback (most recent call last):
  File "/usr/home/sickgear/SickGear/lib/tornado/web.py", line 1543, in _execute
    result = yield result
  File "/usr/home/sickgear/SickGear/lib/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/home/sickgear/SickGear/lib/tornado/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "/usr/home/sickgear/SickGear/lib/tornado/gen.py", line 307, in wrapper
    result = func(*args, **kwargs)
  File "/usr/home/sickgear/SickGear/sickbeard/webserve.py", line 651, in get
    result = method(**kwargss)
  File "/usr/home/sickgear/SickGear/sickbeard/webserve.py", line 1282, in discover_emby
    return notifiers.NotifierFactory().get('EMBY').discover_server()
  File "/usr/home/sickgear/SickGear/sickbeard/notifiers/emby.py", line 179, in discover_server
    return self._discover_server()
  File "/usr/home/sickgear/SickGear/sickbeard/notifiers/emby.py", line 106, in _discover_server
    cs.shutdown(SHUT_RDWR)
  File "/usr/local/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 57] Socket is not connected

**Comment by JackDandy** [comment]
[Fixed](https://github.com/SickGear/SickGear/releases/tag/release_0.15.13)
