### ISSUE TITLE
Propers search on Xspeeds errors out

### ISSUE THREAD

**Issue by benfishbus** [SickGear/SickGear#1129]
#### Branch version commit hash: 762ba5c7e8fca7636cd6ce0c0b30caffc2286444

Expectation | Result
------------ | -------------
Propers search using Xspeeds provider should work without error. | An error occurs.

**Steps to reproduce:**
*1)* Add Xspeeds media provider (built-in, not custom)
*2)* Enable all 3 types of searches
*3)* Force a propers search

Log text:
<pre>
2018-09-20 20:31:31 PROPER-SEARCH :: [Xspeeds] :: Error while searching Xspeeds, skipping: tuple indices must be integers, not NoneType
2018-09-20 20:31:31 PROPER-SEARCH :: [Xspeeds] :: Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/SickGear/SickGear/sickbeard/properFinder.py", line 203, in _get_proper_list
    anime=recent_anime)
  File "/share/CACHEDEV1_DATA/.qpkg/SickGear/SickGear/sickbeard/providers/generic.py", line 1740, in find_propers
    items = self._search_provider({'Propers': search_terms})
  File "/share/CACHEDEV1_DATA/.qpkg/SickGear/SickGear/sickbeard/providers/xspeeds.py", line 64, in _search_provider
    save_url, restore = self._set_categories(mode)
  File "/share/CACHEDEV1_DATA/.qpkg/SickGear/SickGear/sickbeard/providers/xspeeds.py", line 192, in _set_categories
    (re.search('(Se|Ep)', mode) and self.show and self.show.is_anime)])))
TypeError: tuple indices must be integers, not NoneType
</pre>

**Comment by JackDandy** [comment]
Thanks for the report. [Fixed here](https://github.com/SickGear/SickGear/releases/tag/release_0.17.6)
