### ISSUE TITLE
TokyoToshokan proper search throws error

### ISSUE THREAD

**Issue by gkoh** [SickGear/SickGear#1159]
#### Branch version commit hash: 8d0b76e

Expectation | Result
---------------  | ---------
No errors | Daily error logged

Getting a daily error thrown by the TokyoToshokan provider:
```
2019-02-06 17:35:21 PROPER-SEARCH :: [TokyoToshokan] :: Error while searching TokyoToshokan, skipping: 'dict' object has no attribute 'encode'
2019-02-06 17:35:21 PROPER-SEARCH :: [TokyoToshokan] :: Traceback (most recent call last):
  File "/home/SickGear/sickbeard/properFinder.py", line 187, in _get_proper_list
    anime=recent_anime)
  File "/home/SickGear/sickbeard/providers/generic.py", line 1772, in find_propers
    items = self._search_provider({'Propers': search_terms})
  File "/home/SickGear/sickbeard/providers/tokyotoshokan.py", line 42, in _search_provider
    params = urllib.urlencode({'terms': search_string.encode('utf-8'),
AttributeError: 'dict' object has no attribute 'encode'
```

**Steps to reproduce:**
*1)* Enable TokyoToshokan media provider
*2)* Use default options
*3)* Wait for daily proper search to occur

Additional notes:
Running Python 2.7.15 on OmniOS r151028.

Looks like the incoming _search_string_ is no longer a string, other providers now have it as _search_params_.

**Comment by JackDandy** [comment]
Fix to be released in 0.18.12

**Comment by JackDandy** [comment]
Issue fixed [here](https://github.com/SickGear/SickGear/releases/tag/release_0.18.12)

**Comment by gkoh** [comment]
Fix confirmed, no errors now.
Amazing response time, thanks!
