### ISSUE TITLE
SickGear deletes series folder after manually moving downloaded file into it

### ISSUE THREAD

**Issue by MattiSony** [SickGear/SickGear#1179]
#### Branch version commit hash: d1166f9 @ 0.19.0

Expectation | Result
------------ | -------------
move downloaded file to series folder automatically without deleting the series folder | after moving it(manually), because sickgear doesn't do it automatically, sickgear then deletes the whole series folder

**Steps to reproduce:**
*1)*  Manually move a downloaded file into the same folder as the software would
*2)* Wait for software to delete that folder.
...

Either a link to gist (best as they are easily deleted) or log text wrapped in "pre" tags
```
2019-05-17 07:33:36 INFO     POSTPROCESSER :: Processing... brooklyn.nine-nine.s06e17.1080p.hdtv.x264-lucidtv.mkv
2019-05-17 07:33:36 INFO     POSTPROCESSER :: Analyzing name None
2019-05-17 07:33:36 INFO     POSTPROCESSER :: Analyzing name u'brooklyn.nine-nine.s06e17.1080p.hdtv.x264-lucidtv.mkv'
2019-05-17 07:33:36 ERROR    POSTPROCESSER :: Exception generated in thread POSTPROCESSER: Show folder does not exist: '/volume1/nzb/TV show/Brooklyn Nine-Nine'
2019-05-17 07:33:36 ERROR    POSTPROCESSER :: 'Traceback (most recent call last):\n  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/scheduler.py", line 116, in run\n    self.action.run()\n  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/auto_post_processer.py", line 37, in run\n    self._main()\n  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/auto_post_processer.py", line 53, in _main\n    processTV.processDir(sickbeard.TV_DOWNLOAD_DIR, is_basedir=True)\n  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/processTV.py", line 952, in processDir\n    dir_name, nzb_name, process_method, force, force_replace, failed, type, cleanup, showObj)\n  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/processTV.py", line 388, in process_dir\n    self.check_video_filenames(walk_dir, video_pick)))\n  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/processTV.py", line 866, in _process_media\n    file_success = processor.process()\n  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/postProcessor.py", line 912, in process\n    if not ek.ek(os.path.isdir, ep_obj.show.location) and sickbeard.CREATE_MISSING_SHOW_DIRS:\n  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/tv.py", line 291, in _getLocation\n    raise exceptions.ShowDirNotFoundException(\'Show folder does not exist: \\\'%s\\\'\' % self._location)\nShowDirNotFoundException: Show folder does not exist: \'/volume1/nzb/TV show/Brooklyn Nine-Nine\'\n'

Folder was deleted earlier by sickgear so I added it again:

2019-05-17 11:04:24 INFO     POSTPROCESSER :: Deleted folder /volume1/nzb/TV show/Brooklyn Nine-Nine/Brooklyn.Nine-Nine.S06E17.1080p.HDTV.x264-LucidTV[rarbg]/@eaDir/brooklyn.nine-nine.s06e17.1080p.hdtv.x264-lucidtv.mkv
2019-05-17 11:04:24 INFO     POSTPROCESSER :: Deleted folder /volume1/nzb/TV show/Brooklyn Nine-Nine/Brooklyn.Nine-Nine.S06E17.1080p.HDTV.x264-LucidTV[rarbg]/@eaDir
2019-05-17 11:04:26 INFO     POSTPROCESSER :: Processing... brooklyn.nine-nine.s06e17.1080p.hdtv.x264-lucidtv.mkv
2019-05-17 11:04:26 INFO     POSTPROCESSER :: Analyzing name None
2019-05-17 11:04:26 INFO     POSTPROCESSER :: Analyzing name u'brooklyn.nine-nine.s06e17.1080p.hdtv.x264-lucidtv.mkv'
2019-05-17 11:04:28 INFO     POSTPROCESSER :: Release name (brooklyn.nine-nine.s06e17.1080p.hdtv.x264-lucidtv) found from file (brooklyn.nine-nine.s06e17.1080p.hdtv.x264-lucidtv.nfo)
2019-05-17 11:04:29 INFO     POSTPROCESSER :: 269586: Changed modify date of brooklyn.nine-nine.s06e17.1080p.hdtv.x264-lucidtv.mkv to show air date May 16,2019 (21:00)
2019-05-17 11:04:31 INFO     POSTPROCESSER :: Successfully processed brooklyn.nine-nine.s06e17.1080p.hdtv.x264-lucidtv.mkv
2019-05-17 11:04:31 INFO     POSTPROCESSER :: Deleted folder /volume1/nzb/TV show/Brooklyn Nine-Nine/Brooklyn.Nine-Nine.S06E17.1080p.HDTV.x264-LucidTV[rarbg]
2019-05-17 11:04:34 INFO     POSTPROCESSER :: Deleted folder /volume1/nzb/TV show/Brooklyn Nine-Nine
2019-05-17 11:04:45 INFO     POSTPROCESSER :: Successfully processed at least one video file, others were skipped.
```

Additional notes:
I believe it also does this when it moves the downloaded file itself into the right folder but I haven't been able to reproduce that and it only happens sometimes if so, had some folder deleted that I don't recall moving files manually into it. It also sometimes doesn't move the downloaded file into the folder, which is what happened here so I moved it manually.

Pretty much every TV show I have has been deleted because of this, a few 100GBs.

**Comment by JackDandy** [comment]
Looks as though a terribly bad user configuration is the cause here (though you have not included debug level in your log items).

You have not separated client/manual downloads from where you want shows to be finally stored, therefore, the normal cleanup is being run on files/folders that do match existing items being processed - this is normal cleanup behavior.

You absolutely must...

1) Set your download client to use one path e.g.  `/volume1/downloads/here/` and then set the config/post-processing/"Completed TV downloads" to this path (use same path for manual).

2) Then each show must have a parent location separate to location in step (1) e.g. `/volume1/TV shows`. SG will move shows to this **completely separate path** e.g. `/volume1/TV show/Show.name` and the clean up will made on the correct source location of (1) and not the final show location as you have been doing.

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.

**Comment by MattiSony** [comment]
Thanks i've done that now, should probably have a warning that says it can't be on the same path in the settings so others don't do it too :)

**Comment by JackDandy** [comment]
It always has, I just didn't say, under the setting for  "Completed TV downloads".

**Comment by JackDandy** [comment]
To be fair, since 2014, you are the second that has set up SG in this way - people simply don't place temp work folders inside final data folders. However, two is enough to justify existing tips be looked at.

**Comment by JackDandy** [comment]
To be fair, since 2014, you are the second that has set up SG in this way - people simply don't place temp work folders inside final data folders. However, two is enough to justify existing tips be looked at. Though it's hard to believe that tips/warnings will prevent every kind of human foolery.

**Comment by MattiSony** [comment]
The path was for completed files not temps, warning only warns about not adding to temp which I didn't, maybe make it also say to not make it the same path as root of SG

**Comment by JackDandy** [comment]
An action on any file or folder before placement at a final parent location is considered temporary. 

Performing a media process on "completed" data is a action on temporary files; those files, folders and sub-folders can be deleted afterwards - therefore, they are indeed temporary.

**Comment by JackDandy** [comment]
An action on any file or folder before placement at a final parent location is considered temporary.

Performing a media process on "completed" data is an action on temporary files; files, folders and sub-folders at the process location can be deleted afterwards - therefore, they are indeed temporary.

**Comment by JackDandy** [comment]
Hi @MattiSony  

Progress on this will soon be merged to `develop` branch. Safe guards have been added so that SG will no longer be able to post process files anywhere under a parent show folder.

Thanks for your report :)

**Comment by JackDandy** [comment]
User safeguard added [here](https://github.com/SickGear/SickGear/releases/tag/release_0.19.2)
