### ISSUE TITLE
Update PLEX not working

### ISSUE THREAD

**Issue by HaArD2000** [SickGear/SickGear#1227]
#### Branch version commit hash: b09d621 @ 0.21.0

Expectation | Result
------------ | -------------
Clicking Update Plex should do that. | Returns an error page:

<pre>Error
addinfourl instance has no attribute '__exit__'

Traceback
Traceback (most recent call last):
File "E:\SickGear\SickGear\lib\tornado_py2\web.py", line 1592, in _execute result = yield result
File "E:\SickGear\SickGear\lib\tornado_py2\gen.py", line 1133, in run value = future.result()
File "E:\SickGear\SickGear\lib\tornado_py2\concurrent.py", line 261, in result raise_exc_info(self._exc_info)
File "E:\SickGear\SickGear\lib\tornado_py2\gen.py", line 307, in wrapper result = func(*args, **kwargs)
File "E:\SickGear\SickGear\sickbeard\webserve.py", line 790, in get self.route_method(route, use_404=True)
File "E:\SickGear\SickGear\sickbeard\webserve.py", line 218, in route_method result = method(**filter_kwargs)
File "E:\SickGear\SickGear\sickbeard\webserve.py", line 2749, in update_plex result = notifiers.NotifierFactory().get('PLEX').update_library()
File "E:\SickGear\SickGear\sickbeard\notifiers\plex.py", line 176, in update_library with urllib.request.urlopen(req) as response:
AttributeError: addinfourl instance has no attribute '__exit__'<pre>

**Steps to reproduce:**
*1)* Click on Shows, then Show list
*2)* Click on Update Plex

or

*1)* Click on Manage
*2)* Click on Update Plex
...

<pre>2019-12-29 03:17:25 ERROR    TORNADO.APP :: Uncaught exception GET /home/update-plex/ (192.168.2.100)
 1) HTTPServerRequest(protocol='http', host='192.168.2.100:8081', method='GET', uri='/home/update-plex/', version='HTTP/1.1', remote_ip='192.168.2.100')
 2) Traceback (most recent call last):
 3)   File "E:\SickGear\SickGear\lib\tornado_py2\web.py", line 1592, in _execute
 4)     result = yield result
 5)   File "E:\SickGear\SickGear\lib\tornado_py2\gen.py", line 1133, in run
 6)     value = future.result()
 7)   File "E:\SickGear\SickGear\lib\tornado_py2\concurrent.py", line 261, in result
 8)     raise_exc_info(self._exc_info)
 9)   File "E:\SickGear\SickGear\lib\tornado_py2\gen.py", line 307, in wrapper
10)     result = func(*args, **kwargs)
11)   File "E:\SickGear\SickGear\sickbeard\webserve.py", line 790, in get
12)     self.route_method(route, use_404=True)
13)   File "E:\SickGear\SickGear\sickbeard\webserve.py", line 218, in route_method
14)     result = method(**filter_kwargs)
15)   File "E:\SickGear\SickGear\sickbeard\webserve.py", line 2749, in update_plex
16)     result = notifiers.NotifierFactory().get('PLEX').update_library()
17)   File "E:\SickGear\SickGear\sickbeard\notifiers\plex.py", line 176, in update_library
18)     with urllib.request.urlopen(req) as response:
19) AttributeError: addinfourl instance has no attribute '__exit__'
</pre>

Additional notes:

Sickgear is configured to send Plex commands (box is checked)
username and password is correctly configured
Update server library is checked
watched interval = 60
blank parent folder(s)
PMS IP:Port = 192.168.2.100:32400
Test is unresponsive (worked previously)

**Comment by JackDandy** [comment]
New logic on the develop branch introduced a bug here - fixed.

Thanks for the report.
