### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get' when opening a added tvshow

### ISSUE THREAD

**Issue by segator** [SickGear/SickGear#1232]
Source linuxserver/sickgear

Run a clean sickgear and try to add Game of thrones
then try to open the TVSHow http:/xxx/home/view-show?tvid_prodid=1:121361
```
Traceback (most recent call last):
File "/app/sickgear/lib/tornado_py2/web.py", line 1592, in _execute result = yield result
File "/app/sickgear/lib/tornado_py2/gen.py", line 1133, in run value = future.result()
File "/app/sickgear/lib/tornado_py2/concurrent.py", line 261, in result raise_exc_info(self._exc_info)
File "/app/sickgear/lib/tornado_py2/gen.py", line 307, in wrapper result = func(*args, **kwargs)
File "/app/sickgear/sickbeard/webserve.py", line 790, in get self.route_method(route, use_404=True)
File "/app/sickgear/sickbeard/webserve.py", line 218, in route_method result = method(**filter_kwargs)
File "/app/sickgear/sickbeard/webserve.py", line 2126, in view_show sickbeard.FANART_RATINGS.get(tvid_prodid, {}).get(match.group(1), ''))]
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by JackDandy** [comment]
This can only happen **IF** a config is never saved, no wonder it took 2 years for it to be found.

Thanks for the report, the fix will be in the next release.

**Comment by JackDandy** [comment]
Fixed [here](https://github.com/SickGear/SickGear/releases/tag/release_0.21.1)
