### ISSUE TITLE
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: dictionary changed size during iteration

### ISSUE THREAD

**Issue by ambreswe2** [SickGear/SickGear#1241]
#### Branch version commit hash: a07cf67 @ 0.21.5

Expectation | Result
POSTPROCESSER usually runs without fault | 020-01-20 10:36:20 POSTPROCESSER :: Exception generated in thread POSTPROCESSER: dictionary changed size during iteration
2020-01-20 10:36:20 POSTPROCESSER :: 'Traceback (most recent call last):\n  File "C:\\SickGear\\SickGear\\sickbeard\\scheduler.py", line 120, in run\n    self.action.run()\n  File "C:\\SickGear\\SickGear\\sickbeard\\auto_post_processer.py", line 39, in run\n    self._main()\n  File "C:\\SickGear\\SickGear\\sickbeard\\auto_post_processer.py", line 55, in _main\n    processTV.processDir(sickbeard.TV_DOWNLOAD_DIR, is_basedir=True)\n  File "C:\\SickGear\\SickGear\\sickbeard\\processTV.py", line 1188, in processDir\n    dir_name, nzb_name, process_method, force, force_replace, failed, pp_type, cleanup, show_obj)\n  File "C:\\SickGear\\SickGear\\sickbeard\\processTV.py", line 375, in process_dir\n    path, filter_list(helpers.is_first_rar_volume, files), pp_type, process_method)\n  File "C:\\SickGear\\SickGear\\sickbeard\\processTV.py", line 569, in unused_archives\n    for archive in archive_history:\nRuntimeError: dictionary changed size during iteration\n'

Your expectation paragraph(s) text here. Before the bar >> | then, your result paragraph(s) text here.

**Steps to reproduce:**
*1)* Every time postprocessor runs
*2)* Step to take
...

Either a link to gist (best as they are easily deleted) or log text wrapped in "pre" tags

Additional notes:
For example, any relevant config settings that may be help us replicate the reported issue

Targeting your info so that the issue can be reproduced is the single fastest way to get it resolved

**Comment by JackDandy** [comment]
Hi, a fix for this is complete and will be available at the next release.

**Comment by ambreswe2** [comment]
Awesome :)

**Comment by JackDandy** [comment]
Fixed [here](https://github.com/SickGear/SickGear/releases/tag/release_0.21.6)

Thanks for the report.
