### ISSUE TITLE
Errors since last update

### ISSUE THREAD

**Issue by herkalurk** [SickGear/SickGear#1248]
#### Release: 0.21.10

Since on latest version I've been seeing some errors in the error log consistently.  Unsure if this is a larger issue but thought you should be aware.

```
2020-02-01 09:55:03 BACKLOG :: Exception generated in thread BACKLOG: 'dict_valueiterator' object has no attribute 'next'
2020-02-01 09:55:03 BACKLOG :: 'Traceback (most recent call last):\n  File "/opt/SickGear/sickbeard/scheduler.py", line 120, in run\n    self.action.run()\n  File "/opt/SickGear/sickbeard/search_backlog.py", line 399, in run\n    self.search_backlog(force_type=force_type, force=force)\n  File "/opt/SickGear/sickbeard/search_backlog.py", line 286, in search_backlog\n    wanted_list = filter_list(\n  File "/opt/SickGear/lib/_23.py", line 170, in filter_list\n    return list(filter(*args))\n  File "/opt/SickGear/sickbeard/search_backlog.py", line 287, in \n    lambda wi: wi and itervalues(wi).next()[0].show_obj.tvid_prodid in runparts, wanted_list)\nAttributeError: \'dict_valueiterator\' object has no attribute \'next\'\n'
2020-01-31 21:55:03 BACKLOG :: Exception generated in thread BACKLOG: 'dict_valueiterator' object has no attribute 'next'
2020-01-31 21:55:03 BACKLOG :: 'Traceback (most recent call last):\n  File "/opt/SickGear/sickbeard/scheduler.py", line 120, in run\n    self.action.run()\n  File "/opt/SickGear/sickbeard/search_backlog.py", line 399, in run\n    self.search_backlog(force_type=force_type, force=force)\n  File "/opt/SickGear/sickbeard/search_backlog.py", line 286, in search_backlog\n    wanted_list = filter_list(\n  File "/opt/SickGear/lib/_23.py", line 170, in filter_list\n    return list(filter(*args))\n  File "/opt/SickGear/sickbeard/search_backlog.py", line 287, in \n    lambda wi: wi and itervalues(wi).next()[0].show_obj.tvid_prodid in runparts, wanted_list)\nAttributeError: \'dict_valueiterator\' object has no attribute \'next\'\n'
2020-01-31 09:55:02 BACKLOG :: Exception generated in thread BACKLOG: 'dict_valueiterator' object has no attribute 'next'
2020-01-31 09:55:02 BACKLOG :: 'Traceback (most recent call last):\n  File "/opt/SickGear/sickbeard/scheduler.py", line 120, in run\n    self.action.run()\n  File "/opt/SickGear/sickbeard/search_backlog.py", line 399, in run\n    self.search_backlog(force_type=force_type, force=force)\n  File "/opt/SickGear/sickbeard/search_backlog.py", line 286, in search_backlog\n    wanted_list = filter_list(\n  File "/opt/SickGear/lib/_23.py", line 170, in filter_list\n    return list(filter(*args))\n  File "/opt/SickGear/sickbeard/search_backlog.py", line 287, in \n    lambda wi: wi and itervalues(wi).next()[0].show_obj.tvid_prodid in runparts, wanted_list)\nAttributeError: \'dict_valueiterator\' object has no attribute \'next\'\n'
2020-01-30 21:55:02 BACKLOG :: Exception generated in thread BACKLOG: 'dict_valueiterator' object has no attribute 'next'
2020-01-30 21:55:02 BACKLOG :: 'Traceback (most recent call last):\n  File "/opt/SickGear/sickbeard/scheduler.py", line 120, in run\n    self.action.run()\n  File "/opt/SickGear/sickbeard/search_backlog.py", line 399, in run\n    self.search_backlog(force_type=force_type, force=force)\n  File "/opt/SickGear/sickbeard/search_backlog.py", line 286, in search_backlog\n    wanted_list = filter_list(\n  File "/opt/SickGear/lib/_23.py", line 170, in filter_list\n    return list(filter(*args))\n  File "/opt/SickGear/sickbeard/search_backlog.py", line 287, in \n    lambda wi: wi and itervalues(wi).next()[0].show_obj.tvid_prodid in runparts, wanted_list)\nAttributeError: \'dict_valueiterator\' object has no attribute \'next\'\n'
```

**Comment by JackDandy** [comment]
Fixed [here](https://github.com/SickGear/SickGear/releases/tag/release_0.21.11)

Thanks for the report.
