### ISSUE TITLE
'ascii' error

### ISSUE THREAD

**Issue by mifrith** [SickGear/SickGear#1251]
When I go to the page of the series I get this error:

Error
'ascii' codec can't encode characters in position 16-23: ordinal not in range(128)

Traceback
Traceback (most recent call last):
File "/usr/local/sickgear/lib/tornado_py2/web.py", line 1592, in _execute result = yield result
File "/usr/local/sickgear/lib/tornado_py2/gen.py", line 1133, in run value = future.result()
File "/usr/local/sickgear/lib/tornado_py2/concurrent.py", line 261, in result raise_exc_info(self._exc_info)
File "/usr/local/sickgear/lib/tornado_py2/gen.py", line 307, in wrapper result = func(*args, **kwargs)
File "/usr/local/sickgear/sickbeard/webserve.py", line 821, in get self.route_method(route, use_404=True)
File "/usr/local/sickgear/sickbeard/webserve.py", line 221, in route_method result = method(**filter_kwargs)
File "/usr/local/sickgear/sickbeard/webserve.py", line 2189, in view_show return t.respond()
File "/usr/local/sickgear/cache/cheetah/_usr_local_sickgear_gui_slick_interfaces_default_displayShow_tmpl.py", line 747, in respond _v = VFFSL(SL,"human",False)(VFFSL(SL,"get_size",False)(VFFSL(SL,"showLoc",True)[0])) # u'$human($get_size($showLoc[0]))' on line 336, col 48
File "/usr/local/sickgear/sickbeard/helpers.py", line 1334, in get_size return sum(map((lambda x: x.stat(follow_symlinks=False).st_size), scantree(start_path)))
File "/usr/local/sickgear/sickbeard/helpers.py", line 1561, in scantree for entry in ek.ek(scandir, path):
File "/usr/local/sickgear/lib/encodingKludge.py", line 126, in ek else fixParaLists(x) for x in args], **kwargs)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 16-23: ordinal not in range(128)

**Comment by JackDandy** [comment]
The steps section requested when this issue was created, enables your reported issue to be replicated and investigated, however, you removed it so there is no idea how to trigger your reported event in order to fix it for you. Until you can supply this information, then there is no choice but to mark this issue "invalid" as what you are reporting cannot be verified. Sorry.

Essential help on [[How-to] Report Issues](https://github.com/SickGear/SickGear/wiki/%5BHow-to%5D-Report-Issues)

There's no need to open a new issue, additions to the end of this thread are just fine.

Thanks.

**Comment by mifrith** [comment]
I apologize for the incorrectly drawn up appeal. Now I understand why there are so many hits marked as incorrect. But I humbly thought that the developer supports his product, and does not lame the user. Probably have to look for an alternative. Thank you for your work. Good luck.

**Comment by JackDandy** [comment]
No, you fail to understand...

You have not supplied steps to reach your issue, therefore, how can you expect us to reach your issue?

Perhaps think what actual show you are trying to view, then we can try the same thing here and fix the issue, the issue you describe is not happening under normal usage.
