### ISSUE TITLE
unexpected keyword argument 'os_auth'

### ISSUE THREAD

**Issue by r0main** [SickGear/SickGear#1254]
#### Branch: master

Expectation | Result
------------ | -------------
If I select Tvsubtitles in Subtitles Plugin, i'm able to download subtitles| I got error, see below

**Steps to reproduce:**
*1)* Select Tvsubtitles in Subtitles Plugin
*2)* Select Subtitle Languages = English (not sure it's relevant to reproduce the issue)
*3)* Wait for scheduler to try to download subtitles

Then you have this error in the logs :
``` 
2020-02-22 02:14:31 ERROR    SUBLIMINAL :: Error consuming task ListTask(Episode, language_set([Language(English)]), addic7ed, ServiceConfig(True, /volume1/@appstore/sickbeard-custom/var/cache))
 1) Traceback (most recent call last):
 2)   File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/subliminal/api.py", line 60, in list_subtitles
 3)     result = consume_task(task, service_instances, os_auth=os_auth)
 4)   File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/subliminal/core.py", line 131, in consume_task
 5)     service = get_service(services, task.service, config=task.config, os_auth=os_auth)
 6)   File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/subliminal/core.py", line 207, in get_service
 7)     services[service_name] = mod.Service(os_auth=os_auth)
 8) TypeError: __init__() got an unexpected keyword argument 'os_auth'
```
I Think it's because the class https://github.com/SickGear/SickGear/blob/master/lib/subliminal/services/tvsubtitles.py is missing a constructor with `os_auth`.

**Comment by r0main** [comment]
Same problem with addicted : 
```
2020-02-22 02:14:31 ERROR    SUBLIMINAL :: Error consuming task ListTask(Episode, language_set([Language(English)]), addic7ed, ServiceConfig(True, /volume1/@appstore/sickbeard-custom/var/cache))
 1) Traceback (most recent call last):
 2)   File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/subliminal/api.py", line 60, in list_subtitles
 3)     result = consume_task(task, service_instances, os_auth=os_auth)
 4)   File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/subliminal/core.py", line 131, in consume_task
 5)     service = get_service(services, task.service, config=task.config, os_auth=os_auth)
 6)   File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/subliminal/core.py", line 207, in get_service
 7)     services[service_name] = mod.Service(os_auth=os_auth)
 8) TypeError: __init__() got an unexpected keyword argument 'os_auth'
```

**Comment by JackDandy** [comment]
Can you let me know if the following steps fixes your issue... https://i.vgy.me/G09mUF.png

**Comment by JackDandy** [comment]
issue fixed here... https://github.com/SickGear/SickGear/releases/tag/release_0.21.14

**Comment by JackDandy** [comment]
this thread will be removed as the issue is fixed.
