### ISSUE TITLE
Reporting consistent error

### ISSUE THREAD

**Issue by herkalurk** [SickGear/SickGear#1255]
#### Branch version: 0.21.14

```
2020-02-24 12:38:42 RECENT-SEARCH :: Traceback (most recent call last):
  File "/opt/SickGear/sickbeard/search_queue.py", line 305, in run
    self.snatched_eps.add(SimpleNamespace(tvid_prodid=ep_obj.show_obj.tvid_prodid,
TypeError: unhashable type: 'SimpleNamespace'

2020-02-24 09:23:31 RECENT-SEARCH :: Traceback (most recent call last):
  File "/opt/SickGear/sickbeard/search_queue.py", line 305, in run
    self.snatched_eps.add(SimpleNamespace(tvid_prodid=ep_obj.show_obj.tvid_prodid,
TypeError: unhashable type: 'SimpleNamespace'

2020-02-23 17:37:44 RECENT-SEARCH :: Traceback (most recent call last):
  File "/opt/SickGear/sickbeard/search_queue.py", line 305, in run
    self.snatched_eps.add(SimpleNamespace(tvid_prodid=ep_obj.show_obj.tvid_prodid,
TypeError: unhashable type: 'SimpleNamespace'
```

#### Additional notes:
Been seeing this in error log since latest update

**Comment by JackDandy** [comment]
**Steps to reproduce:** ??

**Comment by herkalurk** [comment]
I simply updated to the latest version, I haven't found an action I'm performing correlating to the time these errors occur.

**Comment by JackDandy** [comment]
can you come talk about this in irc, i have followup questions and here is not private enough

**Comment by JackDandy** [comment]
Fixed [here](https://github.com/SickGear/SickGear/releases/tag/release_0.21.15)
