### ISSUE TITLE
Exception in thread RECENT-SEARCH :: [omgwtfnzbs]

### ISSUE THREAD

**Issue by boredazfcuk** [SickGear/SickGear#1271]
Branch: develop @ py3.8.2
Branch version commit hash: fa2a239 @ 0.22.0
Python version: 3.8.2 (default, Feb 29 2020, 17:03:31) [GCC 9.2.0]
OS version: Alpine Linux v3.11

After upgrading to Python3, I'm now seeing the following error in my container logs:
```
Exception in thread RECENT-SEARCH :: [omgwtfnzbs]:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/SickGear/sickbeard/tvcache.py", line 113, in updateCache
    data = self._cache_data(**kwargs)
  File "/SickGear/sickbeard/providers/omgwtfnzbs.py", line 428, in _cache_data
    return self.provider.cache_data(**kwargs)
  File "/SickGear/sickbeard/providers/omgwtfnzbs.py", line 229, in cache_data
    data = feedparser.parse(response.replace('<xml', '<?xml').replace('>\n<info>', '?>\n<feed>\n<info>')
  File "/SickGear/lib/feedparser_py3/api.py", line 283, in parse
    saxparser.parse(source)
  File "/usr/lib/python3.8/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python3.8/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/lib/python3.8/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "/home/buildozer/aports/main/python3/src/Python-3.8.2/Modules/pyexpat.c", line 459, in EndElement
  File "/usr/lib/python3.8/xml/sax/expatreader.py", line 381, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/SickGear/lib/feedparser_py3/parsers/strict.py", line 126, in endElementNS
    self.unknown_endtag(localname)
  File "/SickGear/lib/feedparser_py3/mixin.py", line 343, in unknown_endtag
NameError: name 'interesting' is not defined
```
It only seems to be happening during launch. Doesn't seem to happen during a manual search. I see a reference to `cache_data` in there. Is it a because my in-place upgrade is looking at a Python2.7 cache? Should I remove the `cache.db*` files and also the `cache` folder?

**Comment by JackDandy** [comment]
No the issue is in a vendored lib, fix will be at next update.

**Comment by JackDandy** [comment]
Fixed [here](https://github.com/SickGear/SickGear/releases/tag/release_0.21.27).

Thanks for the report.

**Comment by boredazfcuk** [comment]
No worries. I wasn't aware what the cache db contained so only speculating as it was mentioned in the error. No errors at all since the upgrade and it's been quite busy today. Thanks again.
