### ISSUE TITLE
Feature Request: Jellyfin support

### ISSUE THREAD

**Issue by boredazfcuk** [SickGear/SickGear#1272]
Hi,

I was wondering if it would be possible to get Jellyfin support? Jellyfin is a free and open-source media centre which was forked from Emby 3.5.2

Documentation: https://jellyfin.org/docs/
Source: https://github.com/jellyfin/jellyfin
Jellyfin SVG icon assets: https://github.com/jellyfin/jellyfin-ux/tree/master/branding/SVG

I have configured the Emby settings:
```
[Emby]
use_emby = 1
emby_apikey = myjellyfinapikey
emby_host = jellyfin:8096
emby_update_library = 1
emby_watchedstate_frequency = 10 
```
and the `Test Emby` button returns `Success, all hosts tested`

However, if I click the 'Update Emby' button in the top right corner of the home page, I get an error:
```
Error

'NoneType' object has no attribute 'get'
Traceback

Traceback (most recent call last):
File "/SickGear/lib/tornado_py2/web.py", line 1592, in _execute result = yield result
File "/SickGear/lib/tornado_py2/gen.py", line 1133, in run value = future.result()
File "/SickGear/lib/tornado_py2/concurrent.py", line 261, in result raise_exc_info(self._exc_info)
File "/SickGear/lib/tornado_py2/gen.py", line 307, in wrapper result = func(*args, **kwargs)
File "/SickGear/sickbeard/webserve.py", line 823, in get self.route_method(route, use_404=True)
File "/SickGear/sickbeard/webserve.py", line 220, in route_method result = method(**request_kwargs)
File "/SickGear/sickbeard/webserve.py", line 2788, in update_mb helpers.find_show_by_id(tvid_prodid), force=True):
File "/SickGear/sickbeard/notifiers/emby.py", line 91, in update_library if self.is_min_server_version([4, 3, 0, 0], cur_host, keys[i]):
File "/SickGear/sickbeard/notifiers/emby.py", line 56, in is_min_server_version version <= map_list(lambda x: int(x), response.get('Version', '0.0.0.0').split('.'))
AttributeError: 'NoneType' object has no attribute 'get'
```

Thanks,

boredazfcuk

**Comment by JackDandy** [comment]
Works with Emby. Perhaps JF support will be added, but we're currently busy with other stuff, so this is added to todo list for when things clear up.

**Comment by JackDandy** [comment]
Strange though, we cannot replicate this. Under tests, we are seeing version 10.x

**Comment by JackDandy** [comment]
Strange though, we cannot replicate this. Under tests, we are seeing version 10.x and the behavior is the same as Emby, to queue an update in jelly fin.

**Comment by boredazfcuk** [comment]
My SG & JF containers talk to each other directly as they're on the same Docker network. I'm using hostname:port though as the container IPs are dynamic,

Thanks for letting me know. I'll go away and do some more digging.

**Comment by boredazfcuk** [comment]
I think I know why this is happening now...

I found this in the log file:
```
2020-04-22 14:15:47 WARNING  SG_HELPER :: JSON data issue from URL http://jellyfin:8096/emby/System/Info/Public
```
but I have a base URL of /jellyfin, so that URL is invalid.

If I wget http://jellyfin:8096/emby/System/Info/Public from the SG container, I get redirected to: /jellyfin/web/index.html

If I wget http://jellyfin:8096/jellyfin/emby/System/Info/Public, then I get:
```
{"ServerName":"jellyfin","Version":"10.5.4","ProductName":"Jellyfin Server","OperatingSystem":"Linux","Id":"12345789012345678901234567890"}
```
Ideally, I'd be able to set 
```
emby_host = jellyfin:8096/jellyfin
```
or for encrypted communications:
```
emby_host = https://jellyfin:8290/jellyfin
```

**Comment by JackDandy** [comment]
Done [here](https://github.com/SickGear/SickGear/releases/tag/release_0.21.27).

Thanks for the report.

**Comment by boredazfcuk** [comment]
I installed this morning and have tested numerous times both manually and from nzbToMedia scripts and everything is great. Thanks for adding.
