### ISSUE TITLE
IPTorrents Cloudflare anti-bots changes

### ISSUE THREAD

**Issue by mixednutts** [SickGear/SickGear#1273]
Unable to obtain torrents from IPTorrents with following error:

```2020-04-23 13:20:19 WARNING  SG_HELPER :: Exception caught while loading URL https://iptorrents.com/
Detail... Error #1 Cloudflare anti-bots changed, please notify SickGear for an update
Traceback (most recent call last):
  File "/volume1/.@plugins/AppCentral/sickgear/SickGear/lib/sg_helpers.py", line 299, in get_url
    response = session.get(url, timeout=timeout, **kwargs)
  File "/volume1/.@plugins/AppCentral/sickgear/SickGear/lib/requests/sessions.py", line 550, in get
    return self.request('GET', url, **kwargs)
  File "/volume1/.@plugins/AppCentral/sickgear/SickGear/lib/cfscrape/__init__.py", line 63, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/volume1/.@plugins/AppCentral/sickgear/SickGear/lib/cfscrape/__init__.py", line 129, in solve_cf_challenge
    js = self.extract_js(body, domain)
  File "/volume1/.@plugins/AppCentral/sickgear/SickGear/lib/cfscrape/__init__.py", line 173, in extract_js
    raise RuntimeError('Error #1 Cloudflare anti-bots changed, please notify SickGear for an update')
RuntimeError: Error #1 Cloudflare anti-bots changed, please notify SickGear for an update
```

**Comment by JackDandy** [comment]
Hello,

I have a test, are you able to manually switch branches using git ?

**Comment by mixednutts** [comment]
Yep all working.  Checked out hotfix branch and confirmed in "About"
section.  Did a manual search and torrent grabbed and sent to dl client
successfully.  Automatic backlog search also grabbed a few more.   Scanned
logs and saw no issues.

Thanks

**Comment by JackDandy** [comment]
Fix [here](https://github.com/SickGear/SickGear/releases/tag/release_0.21.28)

Thanks for the report.
