### ISSUE TITLE
Missing subtitles download using OpenSubtitles triggers Protocol Error due to unhandled "429 Too Many Requests" response 

### ISSUE THREAD

**Issue by skepticalwaves** [SickGear/SickGear#1288]
#### Branch version commit hash: e22281e

Expectation | Result
------------ | -------------
Missing subtitles are downloaded | Missing subtitle downloads quickly stall

**Steps to reproduce:**
*1)*  Have a large number of missing subtitles
*2)* Trigger a missing subtitles search

This repeats many times as SickGear continues to try to download after getting "Too Many Request" from the OpenSubtitlesAPI
```
2020-06-15 16:36:58 ERROR    SUBLIMINAL :: Error consuming task ListTask(Episode, language_set([Language(English)]), opensubtitles, ServiceConfig(True, /opt/SickGear/cache))
Traceback (most recent call last):
  File "/opt/SickGear/lib/subliminal/api.py", line 60, in list_subtitles
    result = consume_task(task, service_instances, os_auth=os_auth)
  File "/opt/SickGear/lib/subliminal/core.py", line 132, in consume_task
    result = service.list(task.video, task.languages)
  File "/opt/SickGear/lib/subliminal/services/__init__.py", line 155, in list
    return self.list_checked(video, languages)
  File "/opt/SickGear/lib/subliminal/services/opensubtitles.py", line 170, in list_checked
    size=str(video.size))
  File "/opt/SickGear/lib/subliminal/services/opensubtitles.py", line 152, in query
    results = self.server.SearchSubtitles(self.token, searches)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1331, in single_request
    response.msg,
ProtocolError: <ProtocolError for api.opensubtitles.org/xml-rpc: 429 Too Many Requests>

```

Additional notes:
OpenSubtitles notes the following limits on API usage:
https://forum.opensubtitles.org/viewtopic.php?t=16072#:~:text=Starting%20September%201st%2C%202017%20there,10%20second%20per%20IP%20Address.

**Comment by JackDandy** [comment]
This is not an issues, more a feature request because under normal conditions, this is not triggered. Therefore, it can be looked at when time allows.
