### ISSUE TITLE
Cloudflare anti-bots changed

### ISSUE THREAD

**Issue by Namlaz** [SickGear/SickGear#1297]
#### Branch version: 0.21.39

Expectation | Result
------------ | -------------
Searcher working for sources protected by Cloudflare | Failure following a change at Cloudflare

**Steps to reproduce:**
*1)* Auto-search

```
2020-07-18 19:55:20 WARNING  SG_HELPER :: Exception caught while loading URL https://limetorrents.unblocked.lat/
 1) Detail... Error #1 Cloudflare anti-bots changed, please notify SickGear for an update
 2) Traceback (most recent call last):
 3)   File "/app/sickgear/lib/cfscrape/__init__.py", line 167, in extract_js
 4)     js = re.search(
 5) AttributeError: 'NoneType' object has no attribute 'group'
 6) During handling of the above exception, another exception occurred:
 7) Traceback (most recent call last):
 8)   File "/app/sickgear/lib/sg_helpers.py", line 299, in get_url
 9)     response = session.get(url, timeout=timeout, **kwargs)
10)   File "/app/sickgear/lib/requests/sessions.py", line 550, in get
11)     return self.request('GET', url, **kwargs)
12)   File "/app/sickgear/lib/cfscrape/__init__.py", line 63, in request
13)     resp = self.solve_cf_challenge(resp, **kwargs)
14)   File "/app/sickgear/lib/cfscrape/__init__.py", line 129, in solve_cf_challenge
15)     js = self.extract_js(body, domain)
16)   File "/app/sickgear/lib/cfscrape/__init__.py", line 172, in extract_js
17)     raise RuntimeError('Error #1 Cloudflare anti-bots changed, please notify SickGear for an update')
18) RuntimeError: Error #1 Cloudflare anti-bots changed, please notify SickGear for an update

2020-07-18 19:55:19 INFO     RECENT-SEARCH :: [ETTV] :: 100 cache items in response from https://www.ettvdl.com/torrents.php?c5=1&c7=1&c41=1&c50=1&c72=1&c77=1&search=&sort=id&order=desc
2020-07-18 19:55:18 INFO     RECENT-SEARCH :: [Skytorrents] :: 11 cache items in response from https://skytorrents.lol/?category=show&sort=created&query=x265&page=1
2020-07-18 19:55:18 WARNING  SG_HELPER :: Connection error msg:HTTPSConnectionPool(host='www.limetorrents.cc', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3e9fc7a6a0>: Failed to establish a new connection: [Errno 111] Connection refused')) while loading URL https://www.limetorrents.cc/
2020-07-18 19:55:18 WARNING  SG_HELPER :: Connection error msg:HTTPSConnectionPool(host='www.torlock.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3e9fc7af10>: Failed to establish a new connection: [Errno 111] Connection refused')) while loading URL https://www.torlock.com/
2020-07-18 19:55:17 WARNING  SG_HELPER :: Exception caught while loading URL https://limetorrents.unblocked.vc/
 1) Detail... Unable to parse Cloudflare anti-bot IUAM page: JsException()
 2) Traceback (most recent call last):
 3)   File "/app/sickgear/lib/js2py/base.py", line 1464, in call
 4)     return Js(self.code(*args))
 5)   File "/app/sickgear/lib/js2py/host/jseval.py", line 17, in Eval
 6)     py_code = translate_js(code.to_string().value, '')
 7)   File "/app/sickgear/lib/js2py/translators/translator.py", line 69, in translate_js
 8)     return HEADER + translating_nodes.trans(
 9)   File "/app/sickgear/lib/js2py/translators/translating_nodes.py", line 128, in trans
10)     return node(**ele)
11)   File "/app/sickgear/lib/js2py/translators/translating_nodes.py", line 570, in Program
12)     code = inline_stack.inject_inlines(code)
13)   File "/app/sickgear/lib/js2py/translators/translating_nodes.py", line 48, in inject_inlines
14)     source = inject_before_lval(source, lval, self.reps[lval])
15)   File "/app/sickgear/lib/js2py/translators/friendly_nodes.py", line 33, in inject_before_lval
16)     raise RuntimeError('No lval found "%s"' % lval)
17) RuntimeError: No lval found "PyJs_LONG_5_"
18) During handling of the above exception, another exception occurred:
19) Traceback (most recent call last):
20)   File "/app/sickgear/lib/cfscrape/__init__.py", line 133, in solve_cf_challenge
21)     params['jschl_answer'] = str(js2py.EvalJs({'atob': atob}).eval(js))
22)   File "/app/sickgear/lib/js2py/evaljs.py", line 204, in eval
23)     self.execute(code, use_compilation_plan=use_compilation_plan)
24)   File "/app/sickgear/lib/js2py/evaljs.py", line 199, in execute
25)     exec (compiled, self._context)
26)   File "<EvalJS snippet>", line 4, in <module>
27)   File "<EvalJS snippet>", line 3, in PyJs_LONG_0_
28)   File "/app/sickgear/lib/js2py/base.py", line 949, in __call__
29)     return self.call(self.GlobalObject, args)
30)   File "/app/sickgear/lib/js2py/base.py", line 1472, in call
31)     raise MakeError('RangeError', msg)
32) js2py.internals.simplex.JsException: RangeError: RuntimeError('No lval found "PyJs_LONG_5_"')
33) During handling of the above exception, another exception occurred:
34) Traceback (most recent call last):
35)   File "/app/sickgear/lib/js2py/base.py", line 1464, in call
36)     return Js(self.code(*args))
37)   File "/app/sickgear/lib/js2py/host/jseval.py", line 17, in Eval
38)     py_code = translate_js(code.to_string().value, '')
39)   File "/app/sickgear/lib/js2py/translators/translator.py", line 69, in translate_js
40)     return HEADER + translating_nodes.trans(
41)   File "/app/sickgear/lib/js2py/translators/translating_nodes.py", line 128, in trans
42)     return node(**ele)
43)   File "/app/sickgear/lib/js2py/translators/translating_nodes.py", line 570, in Program
44)     code = inline_stack.inject_inlines(code)
45)   File "/app/sickgear/lib/js2py/translators/translating_nodes.py", line 48, in inject_inlines
46)     source = inject_before_lval(source, lval, self.reps[lval])
47)   File "/app/sickgear/lib/js2py/translators/friendly_nodes.py", line 33, in inject_before_lval
48)     raise RuntimeError('No lval found "%s"' % lval)
49) RuntimeError: No lval found "PyJs_anonymous_19_"
50) During handling of the above exception, another exception occurred:
51) Traceback (most recent call last):
52)   File "/app/sickgear/lib/cfscrape/__init__.py", line 136, in solve_cf_challenge
53)     params['jschl_answer'] = str(js2py.EvalJs({'atob': atob}).eval(js))
54)   File "/app/sickgear/lib/js2py/evaljs.py", line 204, in eval
55)     self.execute(code, use_compilation_plan=use_compilation_plan)
56)   File "/app/sickgear/lib/js2py/evaljs.py", line 199, in execute
57)     exec (compiled, self._context)
58)   File "<EvalJS snippet>", line 4, in <module>
59)   File "<EvalJS snippet>", line 3, in PyJs_LONG_0_
60)   File "/app/sickgear/lib/js2py/base.py", line 949, in __call__
61)     return self.call(self.GlobalObject, args)
62)   File "/app/sickgear/lib/js2py/base.py", line 1472, in call
63)     raise MakeError('RangeError', msg)
64) js2py.internals.simplex.JsException: RangeError: RuntimeError('No lval found "PyJs_anonymous_19_"')
65) During handling of the above exception, another exception occurred:
66) Traceback (most recent call last):
67)   File "/app/sickgear/lib/sg_helpers.py", line 299, in get_url
68)     response = session.get(url, timeout=timeout, **kwargs)
69)   File "/app/sickgear/lib/requests/sessions.py", line 550, in get
70)     return self.request('GET', url, **kwargs)
71)   File "/app/sickgear/lib/cfscrape/__init__.py", line 63, in request
72)     resp = self.solve_cf_challenge(resp, **kwargs)
73)   File "/app/sickgear/lib/cfscrape/__init__.py", line 139, in solve_cf_challenge
74)     raise ValueError('Unable to parse Cloudflare anti-bot IUAM page: %r' % e)
75) ValueError: Unable to parse Cloudflare anti-bot IUAM page: JsException()
```

**Comment by JackDandy** [comment]
Dupe #1293
