### ISSUE TITLE
Cloudflare anti bots

### ISSUE THREAD

**Issue by Dillonmartine** [SickGear/SickGear#1300]
Master and Develop branches both effected. 

2020-08-06 21:31:06 WARNING  SG_HELPER :: Exception caught while loading URL https://iptorrents.com/
 1) Detail... Error #1 Cloudflare anti-bots changed, please notify SickGear for an update
 2) Traceback (most recent call last):
 3)   File "C:\SickGear\SickGear\lib\sg_helpers.py", line 299, in get_url
 4)     response = session.get(url, timeout=timeout, **kwargs)
 5)   File "C:\SickGear\SickGear\lib\requests\sessions.py", line 550, in get
 6)     return self.request('GET', url, **kwargs)
 7)   File "C:\SickGear\SickGear\lib\cfscrape\__init__.py", line 63, in request
 8)     resp = self.solve_cf_challenge(resp, **kwargs)
 9)   File "C:\SickGear\SickGear\lib\cfscrape\__init__.py", line 129, in solve_cf_challenge
10)     js = self.extract_js(body, domain)
11)   File "C:\SickGear\SickGear\lib\cfscrape\__init__.py", line 172, in extract_js
12)     raise RuntimeError('Error #1 Cloudflare anti-bots changed, please notify SickGear for an update')
13) RuntimeError: Error #1 Cloudflare anti-bots changed, please notify SickGear for an update

2020-08-06

**Comment by galant56k** [comment]
Same Issue here
