### ISSUE TITLE
Cloudflare anti-bot has changed.

### ISSUE THREAD

**Issue by ryanneufeld** [SickGear/SickGear#1306]
#### Branch version commit hash: (See the About page)

```
2020-09-15 17:55:17 INFO     BACKLOG-1:367138 :: Completed backlog search for: [Star Trek: Lower Decks]
2020-09-15 17:55:17 INFO     BACKLOG-1:367138 :: No needed episodes found during backlog search for: [Star Trek: Lower Decks]
2020-09-15 17:55:17 INFO     BACKLOG-1:367138 :: No suitable candidates
2020-09-15 17:55:17 WARNING  BACKLOG-1:367138 :: Failed 3 times, skipping provider for 0:14:57, last failure at 2020-09-15 17:55:14 with fail type: connection
2020-09-15 17:55:17 INFO     BACKLOG-1:367138 :: Performing season pack search for Star Trek: Lower Decks
2020-09-15 17:55:17 INFO     BACKLOG-1:367138 :: Falling back to season pack search ...
2020-09-15 17:55:17 WARNING  BACKLOG-1:367138 :: [TorrentDay] :: Failed 3 times, skipping provider for 0:14:57, last failure at 2020-09-15 17:55:14 with fail type: connection
2020-09-15 17:55:17 INFO     BACKLOG-1:367138 :: [TorrentDay] :: Performing episode search for Star Trek: Lower Decks
2020-09-15 17:55:17 INFO     BACKLOG-1:367138 :: Beginning backlog search for: [Star Trek: Lower Decks]
2020-09-15 17:55:15 INFO     RECENT-SEARCH :: No needed episodes found
2020-09-15 17:55:14 INFO     RECENT-SEARCH :: Beginning recent search for episodes
2020-09-15 17:55:14 INFO     RECENT-SEARCH :: Found 505 needed episodes spanning 23 shows
2020-09-15 17:55:14 INFO     RECENT-SEARCH :: Finished updating provider caches
2020-09-15 17:55:14 WARNING  RECENT-SEARCH :: [TorrentDay] :: Failed 3 times, skipping provider for 0:14:59, last failure at 2020-09-15 17:55:14 with fail type: connection
2020-09-15 17:55:14 DEBUG    RECENT-SEARCH :: [TorrentDay] :: Transaction with 168 queries executed affected 1 row
2020-09-15 17:55:14 DEBUG    RECENT-SEARCH :: [TorrentDay] :: Adding fail.connection for torrentday
2020-09-15 17:55:13 WARNING  SG_HELPER :: Connection error msg:error HTTPConnectionPool(host='td.unusualperson.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f822efd99d0>, 'Connection to td.unusualperson.com timed out. (connect timeout=30)')) while loading URL http://td.unusualperson.com/
2020-09-15 17:55:03 INFO     TORNADO :: We want 6 episodes for Star Trek: Lower Decks
2020-09-15 17:55:03 DEBUG    TORNADO :: Retrieving the last check time from the DB
2020-09-15 17:54:43 DEBUG    RECENT-SEARCH :: [TorrentDay] :: Transaction with 167 queries executed affected 1 row
2020-09-15 17:54:43 DEBUG    RECENT-SEARCH :: [TorrentDay] :: Adding fail.connection for torrentday
2020-09-15 17:54:42 WARNING  SG_HELPER :: Connection error msg:error HTTPConnectionPool(host='td.workisboring.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f822efd9250>, 'Connection to td.workisboring.com timed out. (connect timeout=30)')) while loading URL http://td.workisboring.com/
2020-09-15 17:54:12 DEBUG    RECENT-SEARCH :: [TorrentDay] :: Transaction with 166 queries executed affected 1 row
2020-09-15 17:54:12 DEBUG    RECENT-SEARCH :: [TorrentDay] :: Adding fail.other for torrentday
2020-09-15 17:54:12 WARNING  SG_HELPER :: Exception caught while loading URL https://www.torrentday.com/
 1) Detail... Error #1 Cloudflare anti-bots changed, please notify SickGear for an update
 2) Traceback (most recent call last):
 3)   File "/sickgear/lib/sg_helpers.py", line 299, in get_url
 4)     response = session.get(url, timeout=timeout, **kwargs)
 5)   File "/sickgear/lib/requests/sessions.py", line 550, in get
 6)     return self.request('GET', url, **kwargs)
 7)   File "/sickgear/lib/cfscrape/__init__.py", line 63, in request
 8)     resp = self.solve_cf_challenge(resp, **kwargs)
 9)   File "/sickgear/lib/cfscrape/__init__.py", line 129, in solve_cf_challenge
10)     js = self.extract_js(body, domain)
11)   File "/sickgear/lib/cfscrape/__init__.py", line 172, in extract_js
12)     raise RuntimeError('Error #1 Cloudflare anti-bots changed, please notify SickGear for an update')
13) RuntimeError: Error #1 Cloudflare anti-bots changed, please notify SickGear for an update

2020-09-15 17:54:11 INFO     RECENT-SEARCH :: Updating provider caches with recent upload data
2020-09-15 17:54:42 WARNING  SG_HELPER :: Connection error msg:error HTTPConnectionPool(host='td.workisboring.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f822efd9250>, 'Connection to td.workisboring.com timed out. (connect timeout=30)')) whiode FROM history AS h INNER JOIN tv_episodes AS e ON (h.indexer = e.indexer AND h.showid = e.showid AND h.season = e.season AND h.episode = e.episode) INNER JOIN tv_shows AS s ON (e.indexer = s.indexer AND e.showid = s.indexer_id) WHERE h.date >= 20200901175408 AND (h.action LIKE "%02" OR h.action LIKE "%09" OR h.action LIKE "%12" OR h.action LIKE "%04" OR h.action LIKE "%11")
2020-09-15 17:54:12 DEBUG    RECENT-SEARCH :: [TorrentDay] :: Transaction with 166 queries executed affected 1 row
2020-09-15 17:54:12 DEBUG    RECENT-SEARCH :: [TorrentDay] :: Adding fail.other for torrentday
2020-09-15 17:54:12 WARNING  SG_HELPER :: Exception caught while loading URL https://www.torrentday.com/
 1) Detail... Error #1 Cloudflare anti-bots changed, please notify SickGear for an update
 2) Traceback (most recent call last):
 3)   File "/sickgear/lib/sg_helpers.py", line 299, in get_url
 4)     response = session.get(url, timeout=timeout, **kwargs)
 5)   File "/sickgear/lib/requests/sessions.py", line 550, in get
 6)     return self.request('GET', url, **kwargs)
 7)   File "/sickgear/lib/cfscrape/__init__.py", line 63, in request
 8)     resp = self.solve_cf_challenge(resp, **kwargs)
 9)   File "/sickgear/lib/cfscrape/__init__.py", line 129, in solve_cf_challenge
10)     js = self.extract_js(body, domain)
11)   File "/sickgear/lib/cfscrape/__init__.py", line 172, in extract_js
12)     raise RuntimeError('Error #1 Cloudflare anti-bots changed, please notify SickGear for an update')
13) RuntimeError: Error #1 Cloudflare anti-bots changed, please notify SickGear for an update
```

**Comment by JackDandy** [comment]
#1293
