### ISSUE TITLE
Problems with specific media provider

### ISSUE THREAD

**Issue by corvacknl** [SickGear/SickGear#1312]
#### Python version: 2.7.18
--

Expectation | Result
------------ | -------------
Media provider (rarbg) being accessible | rarbg shows as : "Rarbg (Site Down?)" on the "Media Providers" page. Checked website on local machine and it works (theres no VPN that connects the NAS to another network / nor does my IPS block this website)

**Steps to reproduce:**
*1A)* Go To "Media Providers" page.

*1B)* Go To tv show.
*2B)* Press scan button.
*3B)* Wont be able to find anything with specified media provider.

<pre>
2020-10-11 16:48:08 CONFIGPROVIDERS^WEB_2 :: Failed to identify a "Rarbg" page with 1 URL (local network issue, site down, or ISP blocked) 
2020-10-11 12:44:34 BACKLOG-1:262754 :: [Rarbg] :: Error while searching Rarbg, skipping: api_token
2020-10-11 12:44:34 BACKLOG-1:262754 :: [Rarbg] :: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/search.py", line 771, in search_providers
    try_other_searches=try_other_searches)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/generic.py", line 1055, in find_search_results
    item_list += self._search_provider(cur_param, search_mode=search_mode, epcount=len(ep_obj_list))
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/rarbg.py", line 81, in _search_provider
    if not self._authorised(reset=True):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/rarbg.py", line 63, in _authorised
    response = self.get_url(self.urls['api_token'], parse_json=True)
KeyError: 'api_token'
</pre>

Additional notes:
does not apply

**Comment by JackDandy** [comment]
The website and the API are not the same, so you cannot create a test based on the availability of the front site vs API. We have seen reports on this from time to time, but cannot lock exactly what happened because no feedback comes given that the issue has always corrected itself. 

Therefore, at this time i can only assume it is a temporary issue that will clear itself. Also, on the history -> Layout -> "Connect fails" Rarbg is not showing any issue, therefore, the API is operating fine. 

I can only suggest to reboot your machine, as that may help.

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.
