### ISSUE TITLE
Sickgear displays error message when manually processing media.

### ISSUE THREAD

**Issue by nogardvfx** [SickGear/SickGear#1315]
#### Branch version commit hash: cef9c8e @ 0.23.0

Expectation | Result
------------ | -------------
I am processing a directory of media manually and I expect it to process all of the files. | After 1 file is processed this error screen appears:

Error
```
Traceback (most recent call last):
File "/usr/serverApps/SickGear/sickbeard/webserve.py", line 232, in async_call
return function(**kw)
File "/usr/serverApps/SickGear/sickbeard/webserve.py", line 3330, in process_files
skip_failure_processing=skip_failure_processing, client=client)
File "/usr/serverApps/SickGear/sickbeard/processTV.py", line 1201, in processDir
pp_type, cleanup, show_obj)
File "/usr/serverApps/SickGear/sickbeard/processTV.py", line 434, in process_dir
force, force_replace, use_trash=cleanup, show_obj=show_obj)
File "/usr/serverApps/SickGear/sickbeard/processTV.py", line 1062, in _process_media
file_success = processor.process()
File "/usr/serverApps/SickGear/sickbeard/postProcessor.py", line 1250, in process
notifiers.notify_update_library(ep_obj)
File "/usr/serverApps/SickGear/sickbeard/notifiers/__init__.py", line 174, in notify_update_library
n.update_library(show_obj=ep_obj.show_obj, show_name=ep_obj.show_obj.name, ep_obj=ep_obj)
File "/usr/serverApps/SickGear/sickbeard/notifiers/trakt.py", line 43, in update_library
self._update_collection(ep_obj)
File "/usr/serverApps/SickGear/sickbeard/notifiers/trakt.py", line 96, in _update_collection
resp = TraktAPI().trakt_request('sync/collection', data, send_oauth=tid)
File "/usr/serverApps/SickGear/lib/libtrakt/trakt.py", line 226, in trakt_request
self.trakt_token(refresh=True, count=0, account=send_oauth)
File "/usr/serverApps/SickGear/lib/libtrakt/trakt.py", line 191, in trakt_token
count=count, sleep_retry=0)
File "/usr/serverApps/SickGear/lib/libtrakt/trakt.py", line 315, in trakt_request
raise TraktException('Could not connect to Trakt. Code error: %s' % ex(code))
File "/usr/serverApps/SickGear/lib/exceptions_helper.py", line 38, in ex
if not e or not e.args:
AttributeError: 'int' object has no attribute 'args'
Traceback

Traceback (most recent call last):
File "/usr/serverApps/SickGear/lib/tornado_py2/web.py", line 1592, in _execute result = yield result
File "/usr/serverApps/SickGear/lib/tornado_py2/gen.py", line 1133, in run value = future.result()
File "/usr/serverApps/SickGear/lib/tornado_py2/concurrent.py", line 261, in result raise_exc_info(self._exc_info)
File "/usr/serverApps/SickGear/lib/tornado_py2/gen.py", line 1141, in run yielded = self.gen.throw(*exc_info)
File "/usr/serverApps/SickGear/sickbeard/webserve.py", line 833, in get yield self.route_method(route, use_404=True)
File "/usr/serverApps/SickGear/lib/tornado_py2/gen.py", line 1133, in run value = future.result()
File "/usr/serverApps/SickGear/lib/tornado_py2/concurrent.py", line 261, in result raise_exc_info(self._exc_info)
File "/usr/serverApps/SickGear/lib/tornado_py2/gen.py", line 1141, in run yielded = self.gen.throw(*exc_info)
File "/usr/serverApps/SickGear/sickbeard/webserve.py", line 223, in route_method result = yield self.async_call(method, request_kwargs) # method(**request_kwargs)
File "/usr/serverApps/SickGear/lib/tornado_py2/gen.py", line 1133, in run value = future.result()
File "/usr/serverApps/SickGear/lib/tornado_py2/concurrent.py", line 261, in result raise_exc_info(self._exc_info)
File "", line 3, in raise_exc_info
Exception: Traceback (most recent call last):
File "/usr/serverApps/SickGear/sickbeard/webserve.py", line 232, in async_call
return function(**kw)
File "/usr/serverApps/SickGear/sickbeard/webserve.py", line 3330, in process_files
skip_failure_processing=skip_failure_processing, client=client)
File "/usr/serverApps/SickGear/sickbeard/processTV.py", line 1201, in processDir
pp_type, cleanup, show_obj)
File "/usr/serverApps/SickGear/sickbeard/processTV.py", line 434, in process_dir
force, force_replace, use_trash=cleanup, show_obj=show_obj)
File "/usr/serverApps/SickGear/sickbeard/processTV.py", line 1062, in _process_media
file_success = processor.process()
File "/usr/serverApps/SickGear/sickbeard/postProcessor.py", line 1250, in process
notifiers.notify_update_library(ep_obj)
File "/usr/serverApps/SickGear/sickbeard/notifiers/__init__.py", line 174, in notify_update_library
n.update_library(show_obj=ep_obj.show_obj, show_name=ep_obj.show_obj.name, ep_obj=ep_obj)
File "/usr/serverApps/SickGear/sickbeard/notifiers/trakt.py", line 43, in update_library
self._update_collection(ep_obj)
File "/usr/serverApps/SickGear/sickbeard/notifiers/trakt.py", line 96, in _update_collection
resp = TraktAPI().trakt_request('sync/collection', data, send_oauth=tid)
File "/usr/serverApps/SickGear/lib/libtrakt/trakt.py", line 226, in trakt_request
self.trakt_token(refresh=True, count=0, account=send_oauth)
File "/usr/serverApps/SickGear/lib/libtrakt/trakt.py", line 191, in trakt_token
count=count, sleep_retry=0)
File "/usr/serverApps/SickGear/lib/libtrakt/trakt.py", line 315, in trakt_request
raise TraktException('Could not connect to Trakt. Code error: %s' % ex(code))
File "/usr/serverApps/SickGear/lib/exceptions_helper.py", line 38, in ex
if not e or not e.args:
AttributeError: 'int' object has no attribute 'args'

Request Info

body: process_type=manual&_xsrf=2%7C6e9962ef%7Cd81033fc1c88757624c18edc7317de40%7C1600691268&dir_name=%2Fmnt%2FentHDD6%2FDownloads%2FComplete%2F_TV%2FThe+Age+of+A.I.+%282019%29+S01+%281080p+YT+WEB-DL+H264+AAC+5.1+-+HxD%29&process_method=move
files: {}
protocol: http
connection:
body_arguments: {'_xsrf': ['2|6e9962ef|d81033fc1c88757624c18edc7317de40|1600691268'], 'dir_name': ['/mnt/entHDD6/Downloads/Complete/_TV/The Age of A.I. (2019) S01 (1080p YT WEB-DL H264 AAC 5.1 - HxD)'], 'process_type': ['manual'], 'process_method': ['move']}
uri: /home/process-media/process-files
query_arguments: {}
_start_time: 1603063781.05
headers: Origin: http://192.168.0.250:8091 Content-Length: 235 Accept-Language: en-US,en;q=0.5 Accept-Encoding: gzip, deflate Connection: keep-alive Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8 User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0 Host: 192.168.0.250:8091 Referer: http://192.168.0.250:8091/home/process-media/ Cookie: sickgear-session-93725b2e0e5289bb0eb7b4437740d59b="2|1:0|10:1603063435|49:sickgear-session-93725b2e0e5289bb0eb7b4437740d59b|60:Z3FYa1BibDRSWFc5NmsyaW9DUUxMM1pJMnB5ZFVVOGNnbWMvdDVsTm1yUT0=|53f50030a943e1b243d3f39c5083624d09323c24a174683abbe820b30cb052e4"; tautulli_token_7472e6b1be49434cad106254cd31991e=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpudWxsLCJ1c2VyIjoibm9nYXJkdmZ4IiwiZXhwIjoxNjAzMTIwNDg2LCJ1c2VyX2dyb3VwIjoiYWRtaW4ifQ.C7S4uXRy8s7yArKjWFK0RmWrkcyVxzPGOeXSTVL83ws; _xsrf=2|eedd0fe8|58545efb9ccc1871a485e3dbf353b347|1600691268; LidarrAuth=IbqQxbsF6ryNc1hQI2KJ9hMyn54K6djiEUVC1J7OY5s%3d47uyMiVgkJc%2b16Yp1wDGFOhN0w8X2oy9m8BZN6JhciJTGBKGW%2buJ%2ffxHHdxzE%2bQc Upgrade-Insecure-Requests: 1 Content-Type: application/x-www-form-urlencoded
host: 192.168.0.250:8091
version: HTTP/1.1
server_connection:
host_name: 192.168.0.250
_finish_time: None
query:
arguments: {'_xsrf': ['2|6e9962ef|d81033fc1c88757624c18edc7317de40|1600691268'], 'process_method': ['move'], 'process_type': ['manual'], 'dir_name': ['/mnt/entHDD6/Downloads/Complete/_TV/The Age of A.I. (2019) S01 (1080p YT WEB-DL H264 AAC 5.1 - HxD)']}
path: /home/process-media/process-files
_cookies: Set-Cookie: LidarrAuth=IbqQxbsF6ryNc1hQI2KJ9hMyn54K6djiEUVC1J7OY5s%3d47uyMiVgkJc%2b16Yp1wDGFOhN0w8X2oy9m8BZN6JhciJTGBKGW%2buJ%2ffxHHdxzE%2bQc Set-Cookie: _xsrf=2|eedd0fe8|58545efb9ccc1871a485e3dbf353b347|1600691268 Set-Cookie: sickgear-session-93725b2e0e5289bb0eb7b4437740d59b="2|1:0|10:1603063435|49:sickgear-session-93725b2e0e5289bb0eb7b4437740d59b|60:Z3FYa1BibDRSWFc5NmsyaW9DUUxMM1pJMnB5ZFVVOGNnbWMvdDVsTm1yUT0=|53f50030a943e1b243d3f39c5083624d09323c24a174683abbe820b30cb052e4" Set-Cookie: tautulli_token_7472e6b1be49434cad106254cd31991e=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpudWxsLCJ1c2VyIjoibm9nYXJkdmZ4IiwiZXhwIjoxNjAzMTIwNDg2LCJ1c2VyX2dyb3VwIjoiYWRtaW4ifQ.C7S4uXRy8s7yArKjWFK0RmWrkcyVxzPGOeXSTVL83ws
method: POST
remote_ip: 192.168.0.250
```

**Steps to reproduce:**
*1) Select "Process Media"
*2) Choose directory under "Browse"
3) Select "Process"

**Comment by JackDandy** [comment]
Can you disable trakt, and see if the issue still persists?

**Comment by JackDandy** [comment]
Fix [here](https://github.com/SickGear/SickGear/releases/tag/release_0.22.6)
