### ISSUE TITLE
Problem with rarbg provider

### ISSUE THREAD

**Issue by BhaalM** [SickGear/SickGear#1320]
#### Python: py2.7.18

Expectation | Result
------------ | -------------
No errors when selecting rarbg as media provider >> | Errors in the log

**Steps to reproduce:**
*1)* Select rarbg as media provider
*2)* Add a show and search for some episode

```
2020-11-01 18:13:42 ERROR    BACKLOG-1:361753 :: [Rarbg] :: Error while searching Rarbg, skipping: api_token
2020-11-01 18:13:42 ERROR    BACKLOG-1:361753 :: [Rarbg] :: Traceback (most recent call last):
  File "/opt/SickGear/app/sickbeard/search.py", line 771, in search_providers
    try_other_searches=try_other_searches)
  File "/opt/SickGear/app/sickbeard/providers/generic.py", line 1057, in find_search_results
    item_list += self._search_provider(cur_param, search_mode=search_mode, epcount=len(ep_obj_list))
  File "/opt/SickGear/app/sickbeard/providers/rarbg.py", line 81, in _search_provider
    if not self._authorised(reset=True):
  File "/opt/SickGear/app/sickbeard/providers/rarbg.py", line 63, in _authorised
    response = self.get_url(self.urls['api_token'], parse_json=True)
KeyError: 'api_token'
```

**Comment by JackDandy** [comment]
If i follow those steps, i cant replicate this issue.

**Comment by BhaalM** [comment]
It's a fresh install, are you using the same python version?

**Comment by JackDandy** [comment]
That provider is working fine on any supported Python version.

**Comment by JackDandy** [comment]
I have an idea, please come to IRC

**Comment by JackDandy** [comment]
Issue fixed, the main site cannot be reached at your side, therefore, the api was shot.

Fix [here](https://github.com/SickGear/SickGear/releases/tag/release_0.22.14)

**Comment by BhaalM** [comment]
Thanks! I'll try tomorrow.

**Comment by BhaalM** [comment]
Well, I've done a quick test, it seems to works, thanks again :)
