### ISSUE TITLE
Mainpage error

### ISSUE THREAD

**Issue by pge-01** [SickGear/SickGear#1323]
#### Branch version commit hash: 0.23.1 (0.23.0)
Synology DSM 6.2.3-25426 Update 2
Sickbeard custom 20200804-8

After the last update from 0.23.0 to 0.23.1 the main web page doesn't show but gives the error page shown below.
After the update of 145 commits (0.23.0) everything went okay. While running 0.23.0 several days I got a simular issue, but that resolved after a stop/restart of Sickbeard Custom.

Expectation | Result
Main page in browser | Error page

**Steps to reproduce:**
*1)* Stopping / restarting / rebooting didn't change anything.

Is this still solvable or do I have to reinstall?

Thanks in advance.
Greetings Paul

Screendump of Error Page:
Error

Traceback (most recent call last):
File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 238, in async_call
return function(**kw)
File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 920, in view_shows
return Home(self.application, self.request).view_shows()
File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 1494, in view_shows
return t.respond()
File "/volume1/@appstore/sickbeard-custom/var/cache/cheetah/_volume1__appstore_sickbeard_custom_var_SickBeard_gui_slick_interfaces_default_home_tmpl.py", line 102, in respond
self._handleCheetahInclude(VFN(VFFSL(SL,"os.path",True),"join",False)(VFFSL(SL,"sg_str",False)('PROG_DIR'), 'gui/slick/interfaces/default/inc_top.tmpl'), trans=trans, includeFrom="file", raw=False)
File "/var/packages/python/target/lib/python2.7/site-packages/Cheetah/Template.py", line 1615, in _handleCheetahInclude
self._CHEETAH__cheetahIncludes[_includeID].respond(trans)
File "_volume1__appstore_sickbeard_custom_var_SickBeard_gui_slick_interfaces_default_inc_top_tmpl.py", line 739, in respond
NotFound: cannot find 'status'

Traceback

Traceback (most recent call last): 
File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/tornado_py2/web.py", line 1592, in _execute result = yield result 
File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/tornado_py2/gen.py", line 1133, in run value = future.result() 
File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/tornado_py2/concurrent.py", line 261, in result raise_exc_info(self._exc_info) 
File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/tornado_py2/gen.py", line 1141, in run yielded = self.gen.throw(*exc_info) 
File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 834, in get yield self.route_method(route, use_404=True) 
File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/tornado_py2/gen.py", line 1133, in run value = future.result() 
File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/tornado_py2/concurrent.py", line 261, in result raise_exc_info(self._exc_info) 
File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/tornado_py2/gen.py", line 1141, in run yielded = self.gen.throw(*exc_info) 
File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 232, in route_method result = yield self.async_call(method, filter_kwargs) # method(**filter_kwargs) 
File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/tornado_py2/gen.py", line 1133, in run value = future.result() 
File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/tornado_py2/concurrent.py", line 261, in result raise_exc_info(self._exc_info) 
File "", line 3, in raise_exc_info 
Exception: Traceback (most recent call last):
File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 238, in async_call
return function(**kw)
File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 920, in view_shows
return Home(self.application, self.request).view_shows()
File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 1494, in view_shows
return t.respond()
File "/volume1/@appstore/sickbeard-custom/var/cache/cheetah/_volume1__appstore_sickbeard_custom_var_SickBeard_gui_slick_interfaces_default_home_tmpl.py", line 102, in respond
self._handleCheetahInclude(VFN(VFFSL(SL,"os.path",True),"join",False)(VFFSL(SL,"sg_str",False)('PROG_DIR'), 'gui/slick/interfaces/default/inc_top.tmpl'), trans=trans, includeFrom="file", raw=False)
File "/var/packages/python/target/lib/python2.7/site-packages/Cheetah/Template.py", line 1615, in _handleCheetahInclude
self._CHEETAH__cheetahIncludes[_includeID].respond(trans)
File "_volume1__appstore_sickbeard_custom_var_SickBeard_gui_slick_interfaces_default_inc_top_tmpl.py", line 739, in respond
NotFound: cannot find 'status'

Request Info

body: 
files: {}
protocol: http
connection: 
body_arguments: {}
uri: /view-shows/
query_arguments: {}
_start_time: 1605976262.51
headers: Accept-Language: nl-nl Accept-Encoding: gzip, deflate Connection: keep-alive Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 Upgrade-Insecure-Requests: 1 Dnt: 1 Host: 192.168.178.50:8083 Referer: http://192.168.178.50:5000/?forceDesktop=1 Cookie: id=rSPGZ641gh5P-i5z3d6HFZYoMpPe6sgaX_og-kAMasA7rwQbD0uJW78BGuYGaNf0MbKog6uoJ1ftUWwHAK2kME; forceDesktop=1; smid=ZLY34X4NYMJJFoa38wN_cws8YTSnOv0xrygDp9VWxFtW5Vpcuzj44O7pbTa7IunKEANEVjmN1Zccnm6zbpQH_g; stay_login=1; _xsrf=2|d6dade5a|499ba537a43e63302a657a57adb64128|1604778465; language=nl User-Agent: Mozilla/5.0 (iPad; CPU OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.0 Mobile/14G60 Safari/602.1 
host: 192.168.178.50:8083
version: HTTP/1.1
server_connection: 
host_name: 192.168.178.50
_finish_time: None
query: 
arguments: {}
path: /view-shows/
_cookies: Set-Cookie: _xsrf=2|d6dade5a|499ba537a43e63302a657a57adb64128|1604778465 Set-Cookie: forceDesktop=1 Set-Cookie: id=rSPGZ641gh5P-i5z3d6HFZYoMpPe6sgaX_og-kAMasA7rwQbD0uJW78BGuYGaNf0MbKog6uoJ1ftUWwHAK2kME Set-Cookie: language=nl Set-Cookie: smid=ZLY34X4NYMJJFoa38wN_cws8YTSnOv0xrygDp9VWxFtW5Vpcuzj44O7pbTa7IunKEANEVjmN1Zccnm6zbpQH_g Set-Cookie: stay_login=1
method: GET
remote_ip: 192.168.178.66

Either a link to gist (best as they are easily deleted) or log text wrapped in "pre" tags

Additional notes:
For example, any relevant config settings that may be help us replicate the reported issue

Targeting your info so that the issue can be reproduced is the single fastest way to get it resolved

**Comment by JackDandy** [comment]
Sounds like your installation somehow got corrupted. Yes, reinstall.

**Comment by JackDandy** [comment]
Has you system actually snatched or downloaded anything?

**Comment by pge-01** [comment]
No sure because I refreshed the page (came back to the page). Didn't watch the whole shutting down and step by step start up process (supposed it normally finishes on the server).
Reinstall will take some time, because I had over 75 shows listed.
But if it's the only way, I will.
Thanks for the quick reply and the nice program anyway!

**Comment by pge-01** [comment]
With 0.23.0 it did install okay but I saw the page there as well and solved it with a restart of SickGear

**Comment by JackDandy** [comment]
I think i see an issue, don't reinstall, i will push an update in a moment.

**Comment by JackDandy** [comment]
Fix [here](https://github.com/SickGear/SickGear/releases/tag/release_0.23.2)

**Comment by pge-01** [comment]
Thanks

**Comment by pge-01** [comment]
That's quick! 
How can I install the update on my synology?

**Comment by JackDandy** [comment]
I would take a backup of the all *.db files and the config.ini files in where ever they are stored on your syno (I don't have one so I cant say), doing this will mean that no matter what, a reinstall takes 3 mins and not 75. Then I guess you can only use the steps for an install to hope that it will overwrite files and not delete them.

**Comment by JackDandy** [comment]
There is another thing here...
if you find the db files and then rename them, you can start up sg, and do an update.

**Comment by JackDandy** [comment]
Shutdown SG,

Take a backup of the all three *.db files and the config.ini files in where ever they are stored on your syno (I don't have one so I cant say), doing this will mean that no matter what, a reinstall takes 3 mins and not 75.

Then rename the db files like... (e.g. sickbread.db_old, cache.db_old, failed.db_old). Start up SG, and then do an update inside it as usual. After the update, shutdown SG. The fix will now be in place, so you can rename the old db files back as they were and start SG to load them.

**Comment by pge-01** [comment]
Do you mean I can start an update an other way than by the web interface (after backup of the db files)?

**Comment by JackDandy** [comment]
Yeah you can force an update check using the menu item "check for updates" inside SG. But you must have already renamed your db files to prevent the UI error you reported. That is why i laid out the exact sequence of steps above.

**Comment by pge-01** [comment]
Thanks, I look into that. 
I don't use a terminal for root access often but will figure it out (maybe tomorrow).

**Comment by JackDandy** [comment]
You should be able to do all this in the file manager, no root access or terminal reqd.

**Comment by pge-01** [comment]
Because the user files are separated from the system files on the Synology (where the SG db files are) I will have to use a SSH service/terminal with root access (I think ...). Admin won't do it

**Comment by JackDandy** [comment]
Ah okay, I understand.

Well, good luck.

**Comment by JackDandy** [comment]
> Or can I do a new install and replace the 3 .db files (and the config.ini included?) after that?

Yes, that should work. Also, when you are back up, can you screengrab your history page in compact layout, i want to see what caused this.

**Comment by pge-01** [comment]
Should I replace the config.ini after reinstall?

**Comment by JackDandy** [comment]
Absolutely, to regain your settings. I cannot stress enough, file operations will only take when SG is shutdown.

**Comment by pge-01** [comment]
Okay and I look for some history as well

**Comment by pge-01** [comment]
Succeeded Thanks
79 shows are there..
Branche master @ p.23.2
Only missing the banners on first look.
I look for the log/history after dinner.

**Comment by JackDandy** [comment]
**not** the log. it's a screengrab of the actual history page in _compact_ layout.

**Comment by pge-01** [comment]
You mean in SickGear > Shows > History?
Don't what that helps

**Comment by pge-01** [comment]
I tried to upload a screenshot here but it doesn't show

**Comment by pge-01** [comment]
Groetjes Paul

**Comment by JackDandy** [comment]
SickGear... `History : Activity` Layout: 100 ... `Compact`

You can either upload an image to imgur or to any cloud in a zip file and simply post a link here.

**Comment by pge-01** [comment]
You get the image by mail?

**Comment by JackDandy** [comment]
Email wont work

**Comment by pge-01** [comment]
Before I go through the hassle of uploading an image..
The compact history only shows the last episodes I dropped in the pool and did get proccessed, which means subtitles are added. How does that help?
Example:
11/21/20, 05:08:3 | Private Eyes S02E12 | -- | -- | addic7ed / EN | SDTV
And so on e10 - e18

**Comment by JackDandy** [comment]
> How does that help?

It helps because this issue took a long time to be reported, therefore, something in your system is not common. The fix you have is for the new feature that displays history compact page items under show menu [3], that menu failed for you, therefore the main page failed, but **only** for you. I have a suspicion of why, but I want to confirm from your screenshot(s).

**Comment by pge-01** [comment]
Okay, I see.
I'll make some screenshots.
