### ISSUE TITLE
develop builds somehow delete `lib/tmdb_api` on start, then crash because it doesn't exist

### ISSUE THREAD

**Issue by aptalca** [SickGear/SickGear#1352]
#### Branch version commit hash: 373c264f38ff8bc68d7e48696d7e7557d6a93c1c

Expectation | Result
------------ | -------------
Sarts successfully via `python3 sickgear.py` | When started, it deletes `lib/tmdb_api` and then crashes because module `tmdb_api` is not found

**Steps to reproduce:**
*1)* Download the latest develop tarball
*2)* `python3 sickgear.py`

Here, the folder exists after untar:
```
~/test/SickGear-SickGear-373c264$ ls -ald lib/tmdb*
drwxr-xr-x 2 aptalca aptalca 4096 Aug  5 11:26 lib/tmdb_api
drwxr-xr-x 2 aptalca aptalca 4096 Aug  5 11:26 lib/tmdbsimple
```
Then we attempt to start and it crashes:
```
~/test/SickGear-SickGear-373c264$ python3 sickgear.py
Traceback (most recent call last):
  File "sickgear.py", line 94, in <module>
    import sickbeard
  File "/home/aptalca/test/SickGear-SickGear-373c264/sickbeard/__init__.py", line 41, in <module>
    from . import classes, db, helpers, image_cache, indexermapper, logger, metadata, naming, people_queue, providers, \
  File "/home/aptalca/test/SickGear-SickGear-373c264/sickbeard/helpers.py", line 41, in <module>
    from . import db, logger, notifiers
  File "/home/aptalca/test/SickGear-SickGear-373c264/sickbeard/notifiers/__init__.py", line 24, in <module>
    from . import emby, kodi, plex, xbmc, \
  File "/home/aptalca/test/SickGear-SickGear-373c264/sickbeard/notifiers/telegram.py", line 29, in <module>
    from sickbeard.image_cache import ImageCache
  File "/home/aptalca/test/SickGear-SickGear-373c264/sickbeard/image_cache.py", line 32, in <module>
    from .metadata.generic import GenericMetadata
  File "/home/aptalca/test/SickGear-SickGear-373c264/sickbeard/metadata/__init__.py", line 23, in <module>
    from . import kodi, mede8er, mediabrowser, ps3, tivo, wdtv, xbmc, xbmc_12plus
  File "/home/aptalca/test/SickGear-SickGear-373c264/sickbeard/metadata/kodi.py", line 23, in <module>
    from . import generic
  File "/home/aptalca/test/SickGear-SickGear-373c264/sickbeard/metadata/generic.py", line 30, in <module>
    from ..indexers import indexer_config
  File "/home/aptalca/test/SickGear-SickGear-373c264/sickbeard/indexers/__init__.py", line 19, in <module>
    from . import indexer_api, indexer_exceptions
  File "/home/aptalca/test/SickGear-SickGear-373c264/sickbeard/indexers/indexer_api.py", line 20, in <module>
    from .indexer_config import init_config, tvinfo_config
  File "/home/aptalca/test/SickGear-SickGear-373c264/sickbeard/indexers/indexer_config.py", line 4, in <module>
    from lib.tmdb_api.tmdb_api import TmdbIndexer
ModuleNotFoundError: No module named 'lib.tmdb_api'
```
Then we check the folder again and it's gone:
```
~/test/SickGear-SickGear-373c264$ ls -ald lib/tmdb*
drwxr-xr-x 3 aptalca aptalca 4096 Aug  5 13:02 lib/tmdbsimple
```

**Comment by JackDandy** [comment]
for now,
```
cd <app>
touch .cleaned006.tmp
```

**Comment by JackDandy** [comment]
Fixed [here](https://github.com/SickGear/SickGear/commit/c681f732520140697e30686496c51eb13ec9e2c3)
