### ISSUE TITLE
Filename containing a particular character breaks view-show under py2

### ISSUE THREAD

**Issue by skepticalwaves** [SickGear/SickGear#1361]
#### Branch: The name of the branch (e.g. master or develop)
master
#### Branch version commit hash: (See the About page)

BRANCH: master @ py2.7.12 / COMMIT: 3d900ba @ 0.25.6
--

Expectation | Result
------------ | -------------
Normal operation | after adding show, no details are populated, attempting to access the show page produces error

**Steps to reproduce:**
*1)* Add show
*2)* Attempt to navigate to the show page
...

Based on the error, it looks like the title might have a non-breaking space in its name.

```
Error
Traceback (most recent call last):
File "/opt/SickGear/sickbeard/webserve.py", line 251, in async_call
return function(**kw)
File "/opt/SickGear/sickbeard/webserve.py", line 2305, in view_show
return t.respond()
File "/opt/SickGear/cache/cheetah/_opt_SickGear_gui_slick_interfaces_default_displayShow_tmpl.py", line 906, in respond
_v = VFFSL(SL,"human",False)(VFFSL(SL,"get_size",False)(VFFSL(SL,"showLoc",True)[0])) # u'$human($get_size($showLoc[0]))' on line 423, col 62
File "/opt/SickGear/sickbeard/helpers.py", line 1120, in get_size
return sum(map((lambda x: x.stat(follow_symlinks=False).st_size), scantree(start_path)))
File "/opt/SickGear/lib/sg_helpers.py", line 1502, in scantree
for entry in ek.ek(scandir, path):
File "/opt/SickGear/lib/encodingKludge.py", line 159, in ek
else fixParaLists(x) for x in args], **kwargs)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 39: ordinal not in range(128)

Traceback
Traceback (most recent call last):
File "/opt/SickGear/lib/tornado_py2/web.py", line 1592, in _execute result = yield result
File "/opt/SickGear/lib/tornado_py2/gen.py", line 1133, in run value = future.result()
File "/opt/SickGear/lib/tornado_py2/concurrent.py", line 261, in result raise_exc_info(self._exc_info)
File "/opt/SickGear/lib/tornado_py2/gen.py", line 1141, in run yielded = self.gen.throw(*exc_info)
File "/opt/SickGear/sickbeard/webserve.py", line 849, in get yield self.route_method(route, use_404=True)
File "/opt/SickGear/lib/tornado_py2/gen.py", line 1133, in run value = future.result()
File "/opt/SickGear/lib/tornado_py2/concurrent.py", line 261, in result raise_exc_info(self._exc_info)
File "/opt/SickGear/lib/tornado_py2/gen.py", line 1141, in run yielded = self.gen.throw(*exc_info)
File "/opt/SickGear/sickbeard/webserve.py", line 245, in route_method result = yield self.async_call(method, filter_kwargs) # method(**filter_kwargs)
File "/opt/SickGear/lib/tornado_py2/gen.py", line 1133, in run value = future.result()
File "/opt/SickGear/lib/tornado_py2/concurrent.py", line 261, in result raise_exc_info(self._exc_info)
File "", line 3, in raise_exc_info
Exception: Traceback (most recent call last):
File "/opt/SickGear/sickbeard/webserve.py", line 251, in async_call
return function(**kw)
File "/opt/SickGear/sickbeard/webserve.py", line 2305, in view_show
return t.respond()
File "/opt/SickGear/cache/cheetah/_opt_SickGear_gui_slick_interfaces_default_displayShow_tmpl.py", line 906, in respond
_v = VFFSL(SL,"human",False)(VFFSL(SL,"get_size",False)(VFFSL(SL,"showLoc",True)[0])) # u'$human($get_size($showLoc[0]))' on line 423, col 62
File "/opt/SickGear/sickbeard/helpers.py", line 1120, in get_size
return sum(map((lambda x: x.stat(follow_symlinks=False).st_size), scantree(start_path)))
File "/opt/SickGear/lib/sg_helpers.py", line 1502, in scantree
for entry in ek.ek(scandir, path):
File "/opt/SickGear/lib/encodingKludge.py", line 159, in ek
else fixParaLists(x) for x in args], **kwargs)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 39: ordinal not in range(128)



```

Additional notes:
For example, any relevant config settings that may be help us replicate the reported issue

Targeting your info so that the issue can be reproduced is the single fastest way to get it resolved

**Comment by JackDandy** [comment]
Not the title, its actually one of the filenames in your show dir that has the issue.

**Comment by JackDandy** [comment]
Not the title, it seems like actually one of the filenames in the show dir has the issue.

Really need to identify which file it is, and then what is in that filename that is causing it

We tried adding the show from tvdb, and no reproducible issue.

Need more input from you, preferably via IRC on this one.

**Comment by JackDandy** [comment]
I wonder if you don't have utf8 enabled in your env

**Comment by skepticalwaves** [comment]
> edit: yeah marking this as invalid, it sounds like you don't have your system set up properly for utf8.

What do I need to provide to demonstrate otherwise:

```
$ locale
LANG=en_CA.UTF-8
LANGUAGE=en_CA:en
LC_CTYPE="en_CA.UTF-8"
LC_NUMERIC="en_CA.UTF-8"
LC_TIME="en_CA.UTF-8"
LC_COLLATE="en_CA.UTF-8"
LC_MONETARY="en_CA.UTF-8"
LC_MESSAGES="en_CA.UTF-8"
LC_PAPER="en_CA.UTF-8"
LC_NAME="en_CA.UTF-8"
LC_ADDRESS="en_CA.UTF-8"
LC_TELEPHONE="en_CA.UTF-8"
LC_MEASUREMENT="en_CA.UTF-8"
LC_IDENTIFICATION="en_CA.UTF-8"
LC_ALL=
```

**Comment by skepticalwaves** [comment]
SickGear is properly handling UTF-8 episode/filenames:
```
./Star Trek Voyager/Star.Trek.Voyager.S07E19.Q².nfo
```

**Comment by JackDandy** [comment]
I added show "The Mighty Ducks: Game Changers" from tvdb under ubuntu and then after adding show, i went to view show, and that worked.

**Comment by JackDandy** [comment]
So I used SNAP to install a py2 build of SG on a Linux Ubuntu VM, and I still cannot replicate an issue adding that show <img src="https://i.vgy.me/EC8Y3u.png">

**Comment by JackDandy** [comment]
Is there anything else apart from simply adding the show that you did, for example, did you set wanted episodes to a number and If if yes, then what providers have you got enabled, I ask because perhaps a new inbound file created the issue you observed, or maybe you added the show as an import with an existing folder?

**Comment by skepticalwaves** [comment]
OH, right, there is a complication.

I was running develop and something went terribly wrong to the point of the database completely corrupting itself, and I had to re-import my entire library in a fresh install which I did on master branch.

Therefore, my original report is *wrong* as this bug was triggered by an import. I conflated them because when I originally tried to add the show it was also broken, but its clear from your testing that's been fixed.

**Comment by JackDandy** [comment]
okay so...  Is there actually an issue here?

If there is an issue, please send steps to reproduce

**Comment by skepticalwaves** [comment]
So, now this could be rephrased as:

"Library imported with directory containing UTF-8 non-breaking space breaks view-show and bulk manage under py2"

At worst I guess I can purge my DB and that directory and re-import again to avoid this.

**Comment by JackDandy** [comment]
is it the **directory name** that contains the "_space_" or a particular **file name** that causes it ?

**Comment by skepticalwaves** [comment]
> is it the directory name that contains the "space" or a particular file name that causes it ?

It is the directory name, this is the entirety of the contents
```
$ find The\ Mighty* | grep -P "[^\x00-\x7F]" #grep which matches UTF-8 characters
The Mighty Ducks Game Changers
The Mighty Ducks Game Changers/poster.jpg
The Mighty Ducks Game Changers/tvshow.nfo
The Mighty Ducks Game Changers/season-all-poster.jpg
The Mighty Ducks Game Changers/banner.jpg
The Mighty Ducks Game Changers/fanart.jpg
The Mighty Ducks Game Changers/season-all-banner.jpg
```

> then you go to the import view, selected the show, and then it all seemed to import fine, but when you go view the show, it breaks, is this a correct set of steps ?

Yes, except I had imported the entire collection at that step because I was re-importing my entire collection after the DB corruption.

**Comment by JackDandy** [comment]
The issue you report cannot be replicated.

However, the best solution is to run SG with python3, and that should not present an issue for you.

If you still have an issue, then there is something wrong in your OS - we simply cannot take this any further.
