### ISSUE TITLE
Crash when looking info screen for "Agatha: House of Harkness"

### ISSUE THREAD

**Issue by csacre** [SickGear/SickGear#1367]
#### Branch: I run the docker version (latest = 0.25.19 of 2021-11-15 23:00:00 UTC)

Expectation | Result
------------ | -------------
1. Click serie "Agatha: House of Harkness" | View the serie info
2. Crash of the system
----------------------------------------------------------------------------------

Thank you for this great software :-)

**Error**
'<' not supported between instances of 'int' and 'NoneType'

**Traceback**
Traceback (most recent call last):
File "/opt/SickGear/lib/tornado_py3/web.py", line 1704, in _execute result = await result
File "/opt/SickGear/lib/tornado_py3/gen.py", line 769, in run yielded = self.gen.throw(*exc_info) # type: ignore
File "/opt/SickGear/sickbeard/webserve.py", line 849, in get yield self.route_method(route, use_404=True)
File "/opt/SickGear/lib/tornado_py3/gen.py", line 762, in run value = future.result()
File "/opt/SickGear/lib/tornado_py3/gen.py", line 769, in run yielded = self.gen.throw(*exc_info) # type: ignore
File "/opt/SickGear/sickbeard/webserve.py", line 245, in route_method result = yield self.async_call(method, filter_kwargs) # method(**filter_kwargs)
File "/opt/SickGear/lib/tornado_py3/gen.py", line 762, in run value = future.result()
File "/opt/SickGear/lib/sg_futures/py3.py", line 32, in run result = self.fn(*self.args, **self.kwargs)
File "/opt/SickGear/sickbeard/webserve.py", line 255, in async_call raise e
File "/opt/SickGear/sickbeard/webserve.py", line 251, in async_call return function(**kw)
File "/opt/SickGear/sickbeard/webserve.py", line 2305, in view_show return t.respond()
File "/data/cache/cheetah/_opt_SickGear_gui_slick_interfaces_default_displayShow_tmpl.py", line 586, in respond if VFN(VFFSL(SL,"show_obj",True),"imdb_info",True)['is_mini_series'] and 1 < VFN(VFFSL(SL,"show_obj",True),"imdb_info",True)['episode_count'] and VFFSL(SL,"runtime",True) and 90 < VFN(VFFSL(SL,"show_obj",True),"imdb_info",True)['runtimes']: # generated from line 238, col 9
TypeError: '<' not supported between instances of 'int' and 'NoneType'

**Request Info**
method: GET
uri: /home/view-show?tvid_prodid=1:412429
version: HTTP/1.1
headers: Host: 192.168.2.49:8091 Connection: keep-alive Upgrade-Insecure-Requests: 1 User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36 Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9 Referer: http://192.168.2.49:8091/view-shows/ Accept-Encoding: gzip, deflate Accept-Language: en-US,en;q=0.9,fr;q=0.8 Cookie: _xsrf=2|531c9b39|b956b16fd94195e8712e375894fc4fb6|1637267575
body: b''
remote_ip: 192.168.2.52
protocol: http
host: 192.168.2.49:8091
host_name: 192.168.2.49
files: {}
connection:
server_connection:
_start_time: 1637507721.983618
_finish_time: None
path: /home/view-show
query: tvid_prodid=1:412429
arguments: {'tvid_prodid': [b'1:412429']}
query_arguments: {'tvid_prodid': [b'1:412429']}
body_arguments: {}
_cookies: Set-Cookie: _xsrf=2|531c9b39|b956b16fd94195e8712e375894fc4fb6|1637267575

**Comment by JackDandy** [comment]
Yup, confirmed reproducible, will be fixed in the next release.

**Comment by csacre** [comment]
Thank you very much!

**Comment by JackDandy** [comment]
Fix [here](https://github.com/SickGear/SickGear/releases/tag/release_0.25.20).

Thanks for the report.
