### ISSUE TITLE
Error searching directory for episodes: '>=' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by ouija** [SickGear/SickGear#1369]
#### Branch version commit hash: 8469308

Just switch from SickChill to SickGear (on my QNAP NAS, using latest release of SickGear) and after importing files under existing library directory, I'm seeing a lot of the following error in the logs:

```
2021-12-13 16:20:57 SHOWQUEUE-ADD :: Error searching directory for episodes: '>=' not supported between instances of 'NoneType' and 'int'
2021-12-13 16:20:57 SHOWQUEUE-ADD :: Traceback (most recent call last):
  File "/share/CACHEDEV3_DATA/.qpkg/OSickGear/OSickGear/sickbeard/show_queue.py", line 1104, in run
    self.show_obj.load_episodes_from_dir()
  File "/share/CACHEDEV3_DATA/.qpkg/OSickGear/OSickGear/sickbeard/tv.py", line 2145, in load_episodes_from_dir
    ep_obj = self.ep_obj_from_file(ek.ek(os.path.join, self._location, cur_media_file))
  File "/share/CACHEDEV3_DATA/.qpkg/OSickGear/OSickGear/sickbeard/tv.py", line 2492, in ep_obj_from_file
    new_quality = Quality.fileQuality(path)
  File "/share/CACHEDEV3_DATA/.qpkg/OSickGear/OSickGear/sickbeard/common.py", line 410, in fileQuality
    if height >= tolerance(352, 5):
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
```

**Comment by JackDandy** [comment]
Fix [here](https://github.com/SickGear/SickGear/releases/tag/release_0.25.22)

Note: This could be a weird permissions issue since your switch to SickGear ... that for some reason the file can't be read/opened, therefore, the media type cannot be determined. The fix now correctly marks those files as UNKNOWN.

Thanks for the report.

**Comment by ouija** [comment]
Talk about service!  Thank you kindly!   I'm really loving this compared to what I was using before.  Keep up the great work.
