### ISSUE TITLE
Post-processing should continue to next episode if show folder does not exist

### ISSUE THREAD

**Issue by mepherion** [SickGear/SickGear#1387]
#### Branch version commit hash: cc46d04

Expectation | Result
------------ | -------------
Post-processing should continue to the next episode if the show folder does not exist | Post-processing throws an exception and stops completely when a show folder is removed

**Steps to reproduce:**

1. Add at least two different shows into SickGear (e.g., "Show A" and "Show B" as an example)
2. Go to Settings -> Media Process -> Post-processing
    a. Fill in "Completed TV downloads" directory 
    a. Choose "Move" as "Process episode method"
    a. Enable "Scan and post process files in the completed TV downloads folder"
    a. Pick any reasonable value for "Run media process every" (e.g., 5 minutes)
5. Delete the show folder for the "first" show (e.g., delete folder for "Show A" in this example)
6. Simulate a download for an episode of "Show A" and place it in the Completed TV downloads directory
7. Simulate a download for an episode of "Show B" and place it in the Completed TV downloads directory
8. Wait for Post-processing to automatically run on the schedule
9. Post-processing runs
     a. Attempts to process the episode for "Show A" but fail to move to the show folder since the folder does not exist
     b. Post-processing throws an exception and stops
8. Wait for Post-processing to automatically run on the schedule
9. Post-processing runs
     a. Attempts to process the episode for "Show A" but fail to move to the show folder since the folder does not exist
     b. Post-processing throws an exception and stops
10. ...

Episode for "Show B" and other remaining episodes will never be processed and post-processing is stuck trying to process the first episode.

Post-processing should catch the ShowDirNotFoundException, log the error, and continue to the next episode

**Log:**
<pre>
2022-06-07 17:44:28 POSTPROCESSER :: Exception generated in thread POSTPROCESSER: Show folder does not exist: 'C:\Videos\Star Trek Strange New Worlds'
2022-06-07 17:44:28 POSTPROCESSER :: 'Traceback (most recent call last):\n  File "C:\\SickGear\\SickGear\\sickbeard\\scheduler.py", line 127, in run\n    self.action.run()\n  File "C:\\SickGear\\SickGear\\sickbeard\\auto_post_processer.py", line 39, in run\n    self._main()\n  File "C:\\SickGear\\SickGear\\sickbeard\\auto_post_processer.py", line 55, in _main\n    processTV.processDir(sickbeard.TV_DOWNLOAD_DIR, is_basedir=True)\n  File "C:\\SickGear\\SickGear\\sickbeard\\processTV.py", line 1206, in processDir\n    return ProcessTVShow(webhandler, is_basedir, skip_failure_processing=skip_failure_processing,\n  File "C:\\SickGear\\SickGear\\sickbeard\\processTV.py", line 499, in process_dir\n    self._process_media(\n  File "C:\\SickGear\\SickGear\\sickbeard\\processTV.py", line 1069, in _process_media\n    file_success = processor.process()\n  File "C:\\SickGear\\SickGear\\sickbeard\\postProcessor.py", line 1101, in process\n    if not self._safe_replace(ep_obj, new_ep_quality):\n  File "C:\\SickGear\\SickGear\\sickbeard\\postProcessor.py", line 887, in _safe_replace\n    existing_show_path = ek.ek(os.path.isdir, ep_obj.show.location)\n  File "C:\\SickGear\\SickGear\\sickbeard\\tv.py", line 1630, in _get_location\n    raise exceptions_helper.ShowDirNotFoundException(\'Show folder does not exist: \\\'%s\\\'\' % self._location)\nexceptions_helper.ShowDirNotFoundException: Show folder does not exist: \'C:\\Videos\\Star Trek Strange New Worlds\'\n'
</pre>

Additional notes:

OS: Windows 10 64-bit
Python Version: 3.9.6

**Comment by JackDandy** [comment]
Fix [here](https://github.com/SickGear/SickGear/releases/tag/release_0.25.35).

Thanks for the perfectly formed report.
