### ISSUE TITLE
Traceback: database is locked

### ISSUE THREAD

**Issue by barbequesauce** [SickGear/SickGear#1419]
#### Branch version commit hash: unknown@3.27.7

Expectation | Result
------------ | -------------
Importing existing filesystem would complete successfully | Traceback on a series

**Steps to reproduce:**
*1)* Import a large number of existing series (~150) with a lot of episodes (~7000)
*2)* Experience random tracebacks due to database locking

This is on a new RasPi 4 running 64-bit Raspbian Bullseye with a newly-flashed MMC and SG in a docker image.

```
2023-03-03 00:58:04 INFO     SHOWQUEUE-ADD :: 1:328690: Loading show info [The Alienist] from TheTVDB
2023-03-03 00:58:04 DEBUG    PEOPLEQUEUE-SHOW-CAST :: Getting extra data for: Kirk Acevedo
2023-03-03 01:00:10 ERROR    PEOPLEQUEUE-SHOW-CAST :: Exception in cast update queue: database is locked
2023-03-03 01:00:10 DEBUG    PEOPLEQUEUE-SHOW-CAST :: Traceback: Traceback (most recent call last):
  File "/app/sickgear/sickgear/people_queue.py", line 198, in run
    self.show_obj.load_cast_from_tvinfo(self.show_info_cast, force=self.force, stop_event=self.stop)
  File "/app/sickgear/sickgear/tv.py", line 2997, in load_cast_from_tvinfo
    new_person = Person(
  File "/app/sickgear/sickgear/tv.py", line 409, in __init__
    self.id = sid or self._get_sid(show_obj=show_obj)  # type: integer_types
  File "/app/sickgear/sickgear/tv.py", line 506, in _get_sid
    self.get_missing_data(show_obj=show_obj)
  File "/app/sickgear/sickgear/tv.py", line 732, in get_missing_data
    t = sickgear.TVInfoAPI(cur_tv_info_src).setup(**tvinfo_config)
  File "/app/sickgear/sickgear/indexers/indexer_api.py", line 47, in setup
    return tvinfo_config[self.tvid]['module'](*args, **kwargs)
  File "/app/sickgear/lib/api_trakt/indexerapiinterface.py", line 83, in __init__
    super(TraktIndexer, self).__init__(*args, **kwargs)
  File "/app/sickgear/lib/tvinfo_base/base.py", line 885, in __init__
    self.diskcache = diskcache.Cache(directory=self._cachedir, disk_pickle_protocol=2)  # type: diskcache.Cache
  File "/app/sickgear/lib/diskcache/core.py", line 500, in __init__
    sql(query, (key, value))
  File "/app/sickgear/lib/diskcache/core.py", line 668, in _execute_with_retry
    return sql(statement, *args, **kwargs)
sqlite3.OperationalError: database is locked
```

**Comment by JackDandy** [comment]
i suggest to import fewer shows, say 50.

**Comment by JackDandy** [comment]
To set up 150 shows with 7000 episodes to even try and replicate this edge case, not practical.

This could even be down to slow device or the mmc card.

I suggest to import fewer shows, say 10, rinse repeat.

**Comment by JackDandy** [comment]
Was it okay with fewer items?
