### ISSUE TITLE
Asustor package not working after update

### ISSUE THREAD

**Issue by MSMortensen** [SickGear/SickGear#1436]
#### Package version: 20230212

Hi,

I'm trying to run your version of SickGear install on my AS6302T from the Asustor app central.

I have been using your amazing app for years without problems.
Today I got an error that I needed to update the git_path, but instead I changed the setting in app to auto update packages.

After a restart the packages were updated, but then Sickgear froze and would not be started.

I then restarted, but could not reach SickGear again (connection refused).
I have uninstalled and reinstalled, but only the same result.

Do you have any suggestion for how I can get SickGear up and running again or how to troubleshoot this?

Kind regards,
Martin

**Comment by clinton-hall** [comment]
Ah, this could be something as simple as a pid file still existing which stops the app from starting, or it could be a dependency issue that ahs failed to install / build

Can you try the following via ssh/terminal (ideally as root user)
```
/usr/local/AppCentral/SickGear/CONTROL/start-stop.sh restart
```
it may be
```
/usr/local/AppCentral/sickgear/CONTROL/start-stop.sh restart
```
(I can't recall if the package installation location uses caps in the package name).

Post the output of the command so we can see what is stopping the app from starting.

**Comment by MSMortensen** [comment]
Hi,

The second command was the correct one and this was the output:

` # /usr/local/AppCentral/sickgear/CONTROL/start-stop.sh restart
Restarting SickGear
Shutting down SickGear at Tue Aug 22 07:11:45 CEST 2023...
SickGear is not running? (Tue Aug 22 07:11:45 CEST 2023)
SickGear prestartup checks... (Tue Aug 22 07:11:45 CEST 2023)
Starting SickGearAlready up to date.
Requirement already satisfied: pip in /volume1/.@plugins/AppCentral/sickgear/env/lib/python3.8/site-packages (23.2.1)
Requirement already satisfied: CT3 in /volume1/.@plugins/AppCentral/sickgear/env/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (3.3.2)
Looking in indexes: https://pypi.org/simple, https://gitlab%2Bdeploy-token-1599941:****@gitlab.com/api/v4/projects/279215/packages/pypi/simple
Ignoring cryptography: markers '"Windows" == platform_system' don't match your environment
Ignoring cryptography: markers '"Linux" == platform_system and "x86_64" != platform_machine and "aarch64" != platform_machine' don't match your environment
Ignoring cryptography: markers '"Darwin" == platform_system and "x86_64" == platform_machine' don't match your environment
Ignoring cryptography: markers '"Darwin" == platform_system and "x86_64" != platform_machine' don't match your environment
Ignoring lxml: markers '"Windows" == platform_system' don't match your environment
Ignoring orjson: markers '"Windows" == platform_system' don't match your environment
Requirement already satisfied: cffi in /volume1/.@plugins/AppCentral/sickgear/env/lib/python3.8/site-packages (from -r recommended.txt (line 2)) (1.15.1)
Requirement already satisfied: cryptography!=38.0.2 in /volume1/.@plugins/AppCentral/sickgear/env/lib/python3.8/site-packages (from -r recommended.txt (line 4)) (41.0.3)
Requirement already satisfied: lxml in /volume1/.@plugins/AppCentral/sickgear/env/lib/python3.8/site-packages (from -r recommended.txt (line 9)) (4.9.3)
Requirement already satisfied: orjson in /volume1/.@plugins/AppCentral/sickgear/env/lib/python3.8/site-packages (from -r recommended.txt (line 11)) (3.9.5)
Requirement already satisfied: pip in /volume1/.@plugins/AppCentral/sickgear/env/lib/python3.8/site-packages (from -r recommended.txt (line 12)) (23.2.1)
Requirement already satisfied: Levenshtein in /volume1/.@plugins/AppCentral/sickgear/env/lib/python3.8/site-packages (from -r recommended.txt (line 13)) (0.21.1)
Requirement already satisfied: rapidfuzz<4.0.0 in /volume1/.@plugins/AppCentral/sickgear/env/lib/python3.8/site-packages (from -r recommended.txt (line 14)) (3.2.0)
Requirement already satisfied: regex in /volume1/.@plugins/AppCentral/sickgear/env/lib/python3.8/site-packages (from -r recommended.txt (line 15)) (2023.8.8)
Requirement already satisfied: setuptools in /volume1/.@plugins/AppCentral/sickgear/env/lib/python3.8/site-packages (from -r recommended.txt (line 16)) (47.1.0)
Requirement already satisfied: pycparser in /volume1/.@plugins/AppCentral/sickgear/env/lib/python3.8/site-packages (from cffi->-r recommended.txt (line 2)) (2.20)
Requirement already satisfied: lxml in /volume1/.@plugins/AppCentral/sickgear/env/lib/python3.8/site-packages (4.9.3)
Requirement already satisfied: regex in /volume1/.@plugins/AppCentral/sickgear/env/lib/python3.8/site-packages (2023.8.8)
ModuleNotFoundError: No module named '_cffi_backend'
thread '<unnamed>' panicked at 'Python API call failed', /github/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.18.3/src/err/mod.rs:790:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/usr/local/AppCentral/sickgear/SickGear/sickgear.py", line 93, in <module>
    import sickgear
  File "/volume1/.@plugins/AppCentral/sickgear/SickGear/sickgear/__init__.py", line 35, in <module>
    from . import classes, db, helpers, image_cache, indexermapper, logger, metadata, naming, people_queue, providers, \  File "/volume1/.@plugins/AppCentral/sickgear/SickGear/sickgear/helpers.py", line 30, in <module>
    from . import db, logger, notifiers
  File "/volume1/.@plugins/AppCentral/sickgear/SickGear/sickgear/notifiers/__init__.py", line 22, in <module>
    from . import emby, kodi, plex, xbmc, \
  File "/volume1/.@plugins/AppCentral/sickgear/SickGear/sickgear/notifiers/telegram.py", line 26, in <module>
    from sickgear.image_cache import ImageCache
  File "/volume1/.@plugins/AppCentral/sickgear/SickGear/sickgear/image_cache.py", line 28, in <module>
    from .metadata.generic import GenericMetadata
  File "/volume1/.@plugins/AppCentral/sickgear/SickGear/sickgear/metadata/__init__.py", line 21, in <module>
    from . import kodi, mede8er, mediabrowser, ps3, tivo, wdtv, xbmc, xbmc_12plus
  File "/volume1/.@plugins/AppCentral/sickgear/SickGear/sickgear/metadata/kodi.py", line 20, in <module>
    from . import generic
  File "/volume1/.@plugins/AppCentral/sickgear/SickGear/sickgear/metadata/generic.py", line 27, in <module>
    from ..indexers import indexer_config
  File "/volume1/.@plugins/AppCentral/sickgear/SickGear/sickgear/indexers/__init__.py", line 17, in <module>
    from . import indexer_api, indexer_exceptions
  File "/volume1/.@plugins/AppCentral/sickgear/SickGear/sickgear/indexers/indexer_api.py", line 18, in <module>
    from .indexer_config import init_config, tvinfo_config
  File "/volume1/.@plugins/AppCentral/sickgear/SickGear/sickgear/indexers/indexer_config.py", line 1, in <module>
    from lib.api_tvdb.tvdb_api import Tvdb
  File "/volume1/.@plugins/AppCentral/sickgear/SickGear/lib/api_tvdb/tvdb_api.py", line 30, in <module>
    from sickgear import ENV
ImportError: cannot import name 'ENV' from partially initialized module 'sickgear' (most likely due to a circular import) (/volume1/.@plugins/AppCentral/sickgear/SickGear/sickgear/__init__.py)
 Done (Tue Aug 22 07:11:58 CEST 2023)`

**Comment by clinton-hall** [comment]
I did some tests here. While I never got the issues with it not running, I got the initial issue with git and suspect yours may not be updating correctly due to issues where the git binary within the venv is not able to update the repository.

Basically I have now moved the initial git clone to happen within the venv and this is working here.

are you able to download the updated apk from here to test: https://www.dropbox.com/scl/fi/icvyn7uh21mqh1td3nuzj/sickgear_20230822_any.apk?rlkey=b88tlk2kj16r8ju0tbw7nulyi&dl=0

if that works for you, I'll submit to App Central.

**Comment by clinton-hall** [comment]
oh, and be patient. On first install this will rebuild the whole virtual environment and install all requirements. Depending on your NAS, this may take 5-10 minutes! 
If it doesn't start after 10 mins, disable and enable again in App Center and it should start ok.

**Comment by MSMortensen** [comment]
Hi,

I left it for 15 minutes, did not work.
Disabled and enabled again, waited another 15 minutes and still did not work.

I ran the command you shared yesterday with the following results:

`root@AS6302T-MSM:/volume1/.@root # /usr/local/AppCentral/sickgear/CONTROL/start-stop.sh restart
Restarting SickGear
Shutting down SickGear at Tue Aug 22 19:25:57 CEST 2023...
SickGear is not running? (Tue Aug 22 19:25:57 CEST 2023)
SickGear prestartup checks... (Tue Aug 22 19:25:57 CEST 2023)
Starting SickGeargit: error while loading shared libraries: libpcre2-8.so.0: cannot open shared object file: No such file or directory
/usr/local/AppCentral/sickgear/CONTROL/start-stop.sh: cd: line 132: can't cd to /usr/local/AppCentral/sickgear/SickGear: No such file or directory
git: error while loading shared libraries: libpcre2-8.so.0: cannot open shared object file: No such file or directory
git: error while loading shared libraries: libpcre2-8.so.0: cannot open shared object file: No such file or directory
Requirement already satisfied: pip in ./env/lib/python3.8/site-packages (23.2.1)
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'recommended.txt'
Requirement already satisfied: lxml in ./env/lib/python3.8/site-packages (4.9.3)
Requirement already satisfied: regex in ./env/lib/python3.8/site-packages (2023.8.8)
python3: can't open file '/usr/local/AppCentral/sickgear/SickGear/sickgear.py': [Errno 2] No such file or directory
 Done (Tue Aug 22 19:26:06 CEST 2023)
root@AS6302T-MSM:/volume1/.@root #`

**Comment by clinton-hall** [comment]
interesting. So git isn't even working inside the venv.

Can you please try the following commands via ssh
```
/opt/bin/opkg install git
/opt/bin/opkg install git-http
cd /usr/local/AppCentral/sickgear
rm -rf env
/usr/local/AppCentral/sickgear/CONTROL/start-stop.sh restart
```

**Comment by MSMortensen** [comment]
Hi,

Last evening I uninstalled sickgear and Entware along with any app not needed for couchpotato or basic functions.
After a restart I reinstalled Sickgear (from app central) and now everything is working.

I wonder if the problem might have been in Entware and not in Sickgear itself.

Thank you for your help!

Best,
Martin

PS: If there is any commands you would like me to test, please let me know and I will do it tonight.
