### ISSUE TITLE
Stack trace when trying to look at details of one of my shows

### ISSUE THREAD

**Issue by JimBarber** [SickGear/SickGear#1437]
#### Branch version commit hash: (See the About page)

`BRANCH: main @ py3.11.2 / COMMIT: 1c61492 @ 3.29.4`

Expectation | Result
------------ | -------------
Your expectation paragraph(s) text here. Before the bar >> | then, your result paragraph(s) text here.

I am on the latest version of SickGear running on Debian stable (bookworm).
I just added `The Simpsons` to it and it has queued episodes for it in sabnzbd.
I realised I didn't want 1080p versions since the episodes are larger than I wanted so I wanted to edit the show.
However when I choose the show which takes me to the `/home/view-show?tvid_prodid=3:83` URI path I am presented with a stack track in the browser.
Other shows display fine, it is only `The Simpsons` that I have an issue with.
There are 34 seasons of The Simpsons which is larger than anything else I have by far, so I'm wondering if some sort of overflow has happening.

The `sickgear.log` file shows the following when I click on the link to show the details of the Show:
```
2023-09-05 20:21:50 ERROR    TORNADO.APP :: Uncaught exception GET /home/view-show?tvid_prodid=3:83 (fdbb:1150:c530:1:c2fe:9d38:d18:7b77)
HTTPServerRequest(protocol='https', host='gecko.home.lan:8081', method='GET', uri='/home/view-show?tvid_prodid=3:83', version='HTTP/1.1', remote_ip='fdbb:1150:c530:1:c2fe:9d38:d18:7b77')
Traceback (most recent call last):
  File "/opt/sickgear/app/lib/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/opt/sickgear/app/lib/tornado/gen.py", line 780, in run
    yielded = self.gen.throw(exc)
              ^^^^^^^^^^^^^^^^^^^
  File "/opt/sickgear/app/sickgear/webserve.py", line 981, in get
    yield self.route_method(route, use_404=True)
  File "/opt/sickgear/app/lib/tornado/gen.py", line 767, in run
    value = future.result()
            ^^^^^^^^^^^^^^^
  File "/opt/sickgear/app/lib/tornado/gen.py", line 780, in run
    yielded = self.gen.throw(exc)
              ^^^^^^^^^^^^^^^^^^^
  File "/opt/sickgear/app/sickgear/webserve.py", line 296, in route_method
    result = yield self.async_call(method, filter_kwargs)  # method(**filter_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sickgear/app/lib/tornado/gen.py", line 767, in run
    value = future.result()
            ^^^^^^^^^^^^^^^
  File "/opt/sickgear/app/lib/sg_futures/py3.py", line 32, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sickgear/app/sickgear/webserve.py", line 304, in async_call
    raise e
  File "/opt/sickgear/app/sickgear/webserve.py", line 302, in async_call
    return function(**kw)
           ^^^^^^^^^^^^^^
  File "/opt/sickgear/app/sickgear/webserve.py", line 2469, in view_show
    return t.respond()
           ^^^^^^^^^^^
  File "/opt/sickgear/data/cache/cheetah/_opt_sickgear_app_gui_slick_interfaces_default_displayShow_tmpl.py", line 780, in respond
TypeError: sequence item 0: expected str instance, NoneType found
```

**Steps to reproduce:**
*1)* Step to take

Add `The Simpsons` to the list of shows.
I did this via the search in SickGear and if it matters I chose the `TVmaze` listing for it.

*2)* Step to take

Go to the `Show List` and click on the link for `The Simpsons`.
Then I'm presented with the stack track in my browser.

...

Either a link to gist (best as they are easily deleted) or log text wrapped in "pre" tags

Additional notes:
For example, any relevant config settings that may be help us replicate the reported issue

Targeting your info so that the issue can be reproduced is the single fastest way to get it resolved

**Comment by JimBarber** [comment]
Yep I can do that.

**Comment by JimBarber** [comment]
I assume it'll just be a case of stopping SickGear, doing a `git pull; git checkout $BRANCH_NAME` and then starting SickGear up again?

**Comment by JimBarber** [comment]
Ok I've switched.
There's still a problem but the stack trace is slightly different so I'll show it for the `dev` branch
```
HTTPServerRequest(protocol='https', host='gecko.home.lan:8081', method='GET', uri='/home/view-show?tvid_prodid=3:83', version='HTTP/1.1', remote_ip='fdbb:1150:c530:1:c2fe:9d38:d18:7b77')
Traceback (most recent call last):
  File "/opt/sickgear/app/lib/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/opt/sickgear/app/lib/tornado/gen.py", line 780, in run
    yielded = self.gen.throw(exc)
              ^^^^^^^^^^^^^^^^^^^
  File "/opt/sickgear/app/sickgear/webserve.py", line 981, in get
    yield self.route_method(route, use_404=True)
  File "/opt/sickgear/app/lib/tornado/gen.py", line 767, in run
    value = future.result()
            ^^^^^^^^^^^^^^^
  File "/opt/sickgear/app/lib/tornado/gen.py", line 780, in run
    yielded = self.gen.throw(exc)
              ^^^^^^^^^^^^^^^^^^^
  File "/opt/sickgear/app/sickgear/webserve.py", line 296, in route_method
    result = yield self.async_call(method, filter_kwargs)  # method(**filter_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sickgear/app/lib/tornado/gen.py", line 767, in run
    value = future.result()
            ^^^^^^^^^^^^^^^
  File "/opt/sickgear/app/lib/sg_futures/py3.py", line 32, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sickgear/app/sickgear/webserve.py", line 304, in async_call
    raise e
  File "/opt/sickgear/app/sickgear/webserve.py", line 302, in async_call
    return function(**kw)
           ^^^^^^^^^^^^^^
  File "/opt/sickgear/app/sickgear/webserve.py", line 2469, in view_show
    return t.respond()
           ^^^^^^^^^^^
  File "/opt/sickgear/data/cache/cheetah/_opt_sickgear_app_gui_slick_interfaces_default_displayShow_tmpl.py", line 780, in respond
    by_people = ', '.join(VFFSL(SL,"by_people",True) if 2 > len(VFFSL(SL,"by_people",True)) else VFFSL(SL,"by_people",True)[0:-1] + ['and ' + VFFSL(SL,"by_people",True)[-1]])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, NoneType found

```

**Comment by JimBarber** [comment]
I switched back to `main` and confirm that the fix has worked.
