### ISSUE TITLE
SickGear won't run anymore

### ISSUE THREAD

**Issue by PickledCucumber15** [SickGear/SickGear#1442]
#### Branch version commit hash: (See the About page)

Expectation | Result
------------ | -------------
SickGear won't run anymore. Get error below.
Pretty sure this was caused by marking an episode that was downloaded as "archived (unknown)", and the episode didn't have metadeta downloaded (it was labelled as TBA).
How to fix?

Error

'str' object has no attribute 'name'
Traceback

Traceback (most recent call last):
File "C:\SickGear\SickGear\lib\tornado\web.py", line 1786, in _execute result = await result ^^^^^^^^^^^^
File "C:\SickGear\SickGear\lib\tornado\gen.py", line 780, in run yielded = self.gen.throw(exc) ^^^^^^^^^^^^^^^^^^^
File "C:\SickGear\SickGear\sickgear\webserve.py", line 981, in get yield self.route_method(route, use_404=True)
File "C:\SickGear\SickGear\lib\tornado\gen.py", line 767, in run value = future.result() ^^^^^^^^^^^^^^^
File "C:\SickGear\SickGear\lib\tornado\gen.py", line 780, in run yielded = self.gen.throw(exc) ^^^^^^^^^^^^^^^^^^^
File "C:\SickGear\SickGear\sickgear\webserve.py", line 296, in route_method result = yield self.async_call(method, filter_kwargs) # method(**filter_kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\SickGear\SickGear\lib\tornado\gen.py", line 767, in run value = future.result() ^^^^^^^^^^^^^^^
File "C:\SickGear\SickGear\lib\sg_futures\py3.py", line 32, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\SickGear\SickGear\sickgear\webserve.py", line 304, in async_call raise e
File "C:\SickGear\SickGear\sickgear\webserve.py", line 302, in async_call return function(**kw) ^^^^^^^^^^^^^^
File "C:\SickGear\SickGear\sickgear\webserve.py", line 1077, in view_shows return Home(self.application, self.request).view_shows() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\SickGear\SickGear\sickgear\webserve.py", line 1678, in view_shows return t.respond() ^^^^^^^^^^^
File "C:\SickGear\data\cache\cheetah\_SickGear_SickGear_gui_slick_interfaces_default_home_tmpl.py", line 911, in respond
File "C:\Users\user\AppData\Roaming\Python\Python311\site-packages\Cheetah\Filters.py", line 40, in filter return unicode(val) ^^^^^^^^^^^^
File "C:\SickGear\SickGear\lib\pytvmaze\tvmaze.py", line 633, in __str__ return _valid_encoding('%s%s' % (self.name, self._get_coutnry())) ^^^^^^^^^^^^^^^^^^^
File "C:\SickGear\SickGear\lib\pytvmaze\tvmaze.py", line 626, in _get_coutnry c = ' (%s)' % self.country.name ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'name'
Request Info

method: GET
uri: /view-shows/
version: HTTP/1.1
headers: Host: localhost:8081 User-Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0 Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8 Accept-Language: en-CA,en-US;q=0.7,en;q=0.3 Accept-Encoding: gzip, deflate, br Dnt: 1 Connection: keep-alive Cookie: _xsrf=2|4eb9b551|cead05b604b221120f9bb419e594b7f0|1694692067 Upgrade-Insecure-Requests: 1 Sec-Fetch-Dest: document Sec-Fetch-Mode: navigate Sec-Fetch-Site: cross-site Sec-Fetch-User: ?1
body: b''
remote_ip: 127.0.0.1
protocol: http
host: localhost:8081
host_name: localhost
files: {}
connection:
server_connection:
_start_time: 1695270660.1238384
_finish_time: None
path: /view-shows/
query:
arguments: {}
query_arguments: {}
body_arguments: {}
_cookies: Set-Cookie: _xsrf=2|4eb9b551|cead05b604b221120f9bb419e594b7f0|1694692067

**Comment by PickledCucumber15** [comment]
I think it's main, I stay away from dev builds. Also I'm pretty sure it's latest version, I can't confirm as app won't run to find out.
thanks
