### ISSUE TITLE
No start after latest update

### ISSUE THREAD

**Issue by kevin201** [SickGear/SickGear#1460]
#### Branch version commit hash: (See the About page)

Expectation | Result
------------ | -------------
Runs | Doesn't

**Steps to reproduce:**
*1)* /opt/sickgear/.pyenv/versions/3.12.1/bin/python /opt/sickgear/sickgear.py

```
Starting up SickGear from /opt/sickgear/config.ini
Traceback (most recent call last):
  File "/opt/sickgear/sickgear.py", line 824, in <module>
    SickGear().start()
  File "/opt/sickgear/sickgear.py", line 350, in start
    sickgear.initialize(console_logging=self.console_logging)
  File "/opt/sickgear/sickgear/__init__.py", line 662, in initialize
    init_stage_1(console_logging)
  File "/opt/sickgear/sickgear/__init__.py", line 1470, in init_stage_1
    for cur_provider in filter(lambda p: abs(zlib.crc32(decode_bytes(p.name))) + 40000400 in (
  File "/opt/sickgear/sickgear/__init__.py", line 1472, in <lambda>
    ) or (p.url and abs(zlib.crc32(decode_bytes(re.sub(r'[./]', '', p.url[-10:])))) + 40000400 in (
          ^^^^^
  File "/opt/sickgear/sickgear/providers/generic.py", line 1638, in url
    self._url = self._valid_home(False)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sickgear/sickgear/providers/generic.py", line 1960, in _valid_home
    sickgear.save_config()
  File "/opt/sickgear/sickgear/__init__.py", line 1900, in save_config
    config_events.put(force)
    ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'put'

```

**Comment by kevin201** [comment]
It said there was an update,  so I clicked update! It never restarted.

**Comment by kevin201** [comment]
It said there was an update,  so I clicked update! It never restarted. For info, the CHANGES file begins with:

<U+FEFF>### 3.32.5 (2024-08-12 00:15:00 UTC)

* Fix to create initial config.ini when one doesn't exist

**Comment by kso512** [comment]
I also see this issue on the latest version, 3.32.5.

**Comment by kevin201** [comment]
It does appear to be associated with the config.ini, but I haven't been able to isolate the source of the problem.

**Comment by kevin201** [comment]
Many thanks. Good to know it's not an invalid issue. There is obviously still some problem though:

$ /opt/sickgear/.pyenv/versions/3.12.1/bin/python /opt/sickgear/sickgear.py
Starting up SickGear from /opt/sickgear/config.ini
MAIN :: saving config file failed, retrying...
MAIN :: saving config file failed, retrying...
MAIN :: saving config file failed, retrying...
MAIN :: saving config file failed, using backup file
MAIN :: saving config file failed, retrying...
MAIN :: saving config file failed, retrying...
MAIN :: saving config file failed, retrying...
MAIN :: saving config file failed, using backup file
MAIN :: saving config file failed, retrying...
MAIN :: saving config file failed, retrying...
MAIN :: saving config file failed, retrying...
MAIN :: saving config file failed, using backup file

**Comment by kso512** [comment]
I saw something similar on startup, though it did eventually come online:

```
MAIN :: saving config file failed, retrying...
MAIN :: saving config file failed, retrying...
MAIN :: saving config file failed, retrying...
MAIN :: saving config file failed, using backup file
MAIN :: saving config file failed, retrying...
MAIN :: saving config file failed, retrying...
MAIN :: saving config file failed, retrying...
MAIN :: saving config file failed, using backup file
MAIN :: Failed 3 times, skipping provider for 0:14:59, last failure at 2024-08-12 12:54:27 with fail type: connection
12:54:27 INFO TORNADO :: Starting SickGear on http://0.0.0.0:8081/
12:54:28 INFO MAIN :: Database schema is up-to-date, no upgrade required

```

**Comment by kevin201** [comment]
I've been getting spurious error messages about not being able to save the config.ini file for some time now. It didn't seem to affect anything, and only occurred every so often, so I ignored them.

I also get occasional messages about processing some rar file. Likewise ignored.

**Comment by kevin201** [comment]
> Perhaps this is a random file hanging around in a completed folder
From memory they reference a directory in  the program path (/opt/sickgear)
If I see it again I'll mention it here.
