### ISSUE TITLE
PP Fails "object of type 'NoneType' has no len()"

### ISSUE THREAD

**Issue by suttyd0lt** [SickGear/SickGear#255]
BRANCH: (master) / COMMIT: (c53a7be7adeb9c6d9d5fbaa207a7a859bad4abc1)

I've just updated to the most recent version, when manually running the post processor on the root dir of download folder I get the following error; 

<pre> Error

object of type 'NoneType' has no len()

Traceback

Traceback (most recent call last): 
File "/opt/SickGear1/tornado/web.py", line 1341, in _execute result = yield result 
File "/opt/SickGear1/tornado/gen.py", line 642, in run value = future.result() 
File "/opt/SickGear1/tornado/concurrent.py", line 110, in result raise_exc_info(self._exc_info) 
File "/opt/SickGear1/tornado/gen.py", line 174, in wrapper result = func(*args, **kwargs) 
File "/opt/SickGear1/sickbeard/webserve.py", line 206, in get self.finish(method(**kwargss)) 
File "/opt/SickGear1/sickbeard/webserve.py", line 2658, in processEpisode is_priority=is_priority, failed=failed, type=type) 
File "/opt/SickGear1/sickbeard/processTV.py", line 210, in processDir process_media(processPath, videoFiles, nzbName, process_method, force, is_priority) 
File "/opt/SickGear1/sickbeard/processTV.py", line 407, in process_media process_result = processor.process() 
File "/opt/SickGear1/sickbeard/postProcessor.py", line 920, in process myDB.mass_action(sql_l) 
File "/opt/SickGear1/sickbeard/db.py", line 87, in mass_action if len(qu) == 1: 
TypeError: object of type 'NoneType' has no len() 

</pre>

If I manually post process a sub dir with fewer files (example a tv season folder), it successfully completes.

Ways to reproduce - 
1.) Select manual PP
2.) Select root download folder
3.) Select hard link
4.) Force already / or not (doesn't matter) 

Some additional information about how I have things setup - 

-TV Downloads through rutorrent are added to manual/TV Shows
-PP is run on manual/TV Shows
-PP is set to create a hard link at manual/Processed TV Shows
-TV Shows then generally end up in my processed folder as defined within settings. 

The TV Shows folder contains thousands of files, many still active within rutorrent.

**Comment by JackDandy** [comment]
does the issue exists with pr 247
