### ISSUE TITLE
Manual PP crashes SG

### ISSUE THREAD

**Issue by Th3MadHatter** [SickGear/SickGear#257]
Had this happen a few times in a row, fairly annoying since the eps I want reprocessed come after these :P.

BRANCH: (develop) / COMMIT: (e9251b3e477712a1d2be8ddb8371865f1d243e81)
This is BETA software.
OS Windows 7
To reproduce, not a clue, do the same thing I did i guess.

```
2015-03-09 23:32:57 DEBUG    TORNADO :: Using ALL regexes
2015-03-09 23:32:57 DB       TORNADO :: sickbeard.db: SELECT season, episode FROM scene_numbering WHERE indexer = ? and indexer_id = ? and scene_season = ? and scene_episode = ? with args [1, 281700, 1, 1]
2015-03-09 23:32:57 DB       TORNADO :: sickbeard.db: SELECT last_refreshed FROM xem_refresh WHERE indexer = ? and indexer_id = ? with args [1, 281700]
2015-03-09 23:32:57 DB       TORNADO :: sickbeard.db: SELECT season, episode FROM tv_episodes WHERE indexer = ? and showid = ? and scene_season = ? and scene_episode = ? with args [1, 281700, 1, 1]
2015-03-09 23:32:57 DEBUG    TORNADO :: Converted parsed result The.Odd.Couple.2015.S01E01.720p.HDTV.X264-DIMENSION into The Odd Couple 2015 - S1E1 [GROUP: DIMENSION] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-03-09 23:32:57 DEBUG    TORNADO :: Parsed The.Odd.Couple.2015.S01E01.720p.HDTV.X264-DIMENSION into The Odd Couple 2015 - S1E1 [GROUP: DIMENSION] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-03-09 23:32:57 DEBUG    TORNADO :: Retrieving episode object for 1x1
2015-03-09 23:32:57 DEBUG    TORNADO :: 281700: An object for episode 1x1 didn't exist in the cache, trying to create it
2015-03-09 23:32:57 DEBUG    TORNADO :: 281700: Loading episode details from DB for episode 1x1
2015-03-09 23:32:57 DB       TORNADO :: sickbeard.db: SELECT * FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [281700, 1, 1]
2015-03-09 23:32:57 DB       TORNADO :: sickbeard.db: SELECT last_refreshed FROM xem_refresh WHERE indexer = ? and indexer_id = ? with args [1, 281700]
2015-03-09 23:32:57 DEBUG    TORNADO :: Snatch history had a quality in it, using that: HD TV
2015-03-09 23:32:57 DEBUG    TORNADO :: Quality of the episode we're processing: 4
2015-03-09 23:32:57 DEBUG    TORNADO :: Is ep a priority download: True
2015-03-09 23:32:57 DEBUG    TORNADO :: There is no existing file so there's no worries about replacing it
2015-03-09 23:32:57 DEBUG    TORNADO :: This download is marked a priority download so I'm going to replace an existing file if I find one
2015-03-09 23:32:57 DEBUG    TORNADO :: Found release name The.Odd.Couple.2015.S01E01.720p.HDTV.X264-DIMENSION
2015-03-09 23:32:57 DEBUG    TORNADO :: 281700: Not creating SQL queue - record is not dirty
2015-03-09 23:32:57 ERROR    TORNADO :: Uncaught exception POST /home/postprocess/processEpisode (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:43728', method='POST', uri='/home/postprocess/processEpisode', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Content-Length': '102', 'Accept-Language': 'nl,en-US;q=0.7,en;q=0.3', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:43728', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0', 'Connection': 'keep-alive', 'Cookie': 'sickgear-session="2|1:0|10:1425939561|16:sickgear-session|60:ZnAwMjFkTGlUZDYzbUszWE56QVpYZHlxWFJ3ZjlFVU9rUkNFZzZ1Tm5jcz0=|abaa902341d4d28f9af81e681db7bdbcd2dd1ce8077eb7424fbe367f5785796a"; snatched_view2=list; soon_view2=thumbs; suggestions_charts_menu_selected=suggestions; late_view2=list; advanced_toggle_checked=1', 'Content-Type': 'application/x-www-form-urlencoded'})
Traceback (most recent call last):
  File "C:\SickGear\tornado\web.py", line 1341, in _execute
    result = yield result
  File "C:\SickGear\tornado\gen.py", line 642, in run
    value = future.result()
  File "C:\SickGear\tornado\concurrent.py", line 110, in result
    raise_exc_info(self._exc_info)
  File "C:\SickGear\tornado\gen.py", line 174, in wrapper
    result = func(*args, **kwargs)
  File "C:\SickGear\sickbeard\webserve.py", line 292, in get
    result = method(**kwargss)
  File "C:\SickGear\sickbeard\webserve.py", line 1944, in processEpisode
    is_priority=is_priority, failed=failed, type=type)
  File "C:\SickGear\sickbeard\processTV.py", line 180, in processDir
    process_result = process_media(path, [video], nzbName, process_method, force, is_priority)
  File "C:\SickGear\sickbeard\processTV.py", line 420, in process_media
    process_result = processor.process()
  File "C:\SickGear\sickbeard\postProcessor.py", line 920, in process
    myDB.mass_action(sql_l)
  File "C:\SickGear\sickbeard\db.py", line 87, in mass_action
    if len(qu) == 1:
TypeError: object of type 'NoneType' has no len()
```

**Comment by JackDandy** [comment]
plz, no more pp issues raised against devel, only against PR #247

**Comment by Th3MadHatter** [comment]
That makes it even worse Jack. Now it doesn't hang anymore but it start relabelling downloaded files as snatched in my db that where previously set to download.... Ok it doesn't hang anymore, I give you that.

**Comment by JackDandy** [comment]
i cannot see how to do the steps, i need you to be clear so that i can even begin to look at this for you.  saying
```
do as i did
```
just doesnt help me to help you.

**Comment by Th3MadHatter** [comment]
Ok lemmi explain, first of all, the auto PPing doesn't work at all,
it runs on start up but after that, any time I set it to, not
happening, not even if i set it to every minute.

Then the actual PPing itself, after switching to your PR it actually
started marking things I already PPed properly as snatched again,
hence, making it worse.
I was able to set them all back manually but it's such a drag because
I have a sh*tload of episodes being PPed because my system was down
for 3 weeks and I watch too much tv shows lol.

As to how to reproduce it, well, just letting it manually post processing my entire dir with both options enabled triggered it for me so I assume it will for you as well.

The error from The Odd Couple was gone though, I haven't really
checked if it works yet (haven't started watching the show yet) but I
assume it just does.

**Comment by JackDandy** [comment]
```
As to how to reproduce it, well, just letting it manually post processing my entire dir with both options enabled triggered it for me so I assume it will for you as well.
```
This is why i asked for steps, because unlike for you, **manual pp** and  **automated pp** (using scripts in the **autoProcessTV/** folder and not the timed - which I will test) is working pretty well for me and other testers. So, again, without you supplying what i have asked for, then i cannot help.

**Comment by JackDandy** [comment]
as i havent heard anything else on this, i can only assume you are sorted

**Comment by Th3MadHatter** [comment]
Sorry I didn't get an email about the previous message.

I set up TTM again so that handles when and what SR PP's from now on again but I'm still cleaning up the fallout from my previous run. A lot of stuff IS PPed while sickgear says its snatched so I'm working my way through my list by watching things and seeing what works or not but like I said I watch waaaay to many shows so lol, it takes a while.

Scan and PP was enabled, it's disabled now because of TTM.

Postpone has never been enabled because I don't use !sync.

I'll get on IRC later when I have some more time so you can explain me what steps you exactly want me to take without f-ing up what I restored so far. Like I said, I don't use the standard PPing process anymore but other users still do so I don't mind running a test for that.

As for the auto process working on your end, well that is weird. I restart my SR a lot on Windows because of reboots, and various other reasons. It usually auto PPed at startup, that went just fine but the automatic timer did nothing, even after switching up between start times every couple of restarts. 
I'll have a look at that as well, see what's going on :).
