### ISSUE TITLE
Add show error

### ISSUE THREAD

**Issue by Th3MadHatter** [SickGear/SickGear#276]
Problems adding new shows

BRANCH: (pull/247/feature/ChangePPFileOrder) / COMMIT: (63caa11e1aa8632b74a3c42d1ff807c002e8a9cd) 
OS Win 7
Reproduce, Try adding "Good Witch" or "Dig" for example:

```
Error

addNewShow() got an unexpected keyword argument 'wanted-begin'
Traceback

Traceback (most recent call last):
File "C:\SickGear\tornado\web.py", line 1341, in _execute result = yield result
File "C:\SickGear\tornado\gen.py", line 642, in run value = future.result()
File "C:\SickGear\tornado\concurrent.py", line 110, in result raise_exc_info(self._exc_info)
File "C:\SickGear\tornado\gen.py", line 174, in wrapper result = func(*args, **kwargs)
File "C:\SickGear\sickbeard\webserve.py", line 292, in get result = method(**kwargss)
TypeError: addNewShow() got an unexpected keyword argument 'wanted-begin'
Request Info

body: indexerLang=en&providedIndexer=0&whichSeries=theTVDB%7C1%7Chttp%3A%2F%2Fthetvdb.com%2F%3Ftab%3Dseries%26id%3D%7C289855%7CGood+Witch%7C2015-02-28&rootDir=G%3A%5Cvideos%5Ctv&defaultStatus=3&anyQualities=4&anyQualities=16&anyQualities=32&anyQualities=64&anyQualities=128&anyQualities=256&wanted-begin=0&wanted-latest=0&subtitles=on&whitelist=&blacklist=&skipShow=
files: {}
protocol: http
connection:
body_arguments: {'defaultStatus': ['3'], 'providedIndexer': ['0'], 'skipShow': [''], 'anyQualities': ['4', '16', '32', '64', '128', '256'], 'indexerLang': ['en'], 'wanted-begin': ['0'], 'blacklist': [''], 'rootDir': ['G:\\videos\\tv'], 'whichSeries': ['theTVDB|1|http://thetvdb.com/?tab=series&id=|289855|Good Witch|2015-02-28'], 'wanted-latest': ['0'], 'whitelist': [''], 'subtitles': ['on']}
uri: /home/addShows/addNewShow
query_arguments: {}
_start_time: 1426425871.36
headers: {'Content-Length': '360', 'Accept-Language': 'nl,en-US;q=0.7,en;q=0.3', 'Accept-Encoding': 'gzip, deflate', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0', 'Host': 'localhost:43728', 'Cookie': 'sickgear-session="2|1:0|10:1426420709|16:sickgear-session|60:SU9nUTk5R1NTOStVVTEwcy9UYkRHZGZ3aDY0dUpFZVdqazRWbmI5bzAyQT0=|905c1e08978f8e7915b8efcbf63a8d08e3d3b8581bc0e0595f2bc2cc989d0a5b"', 'Content-Type': 'application/x-www-form-urlencoded'}
host: localhost:43728
version: HTTP/1.1
arguments: {'defaultStatus': '3', 'providedIndexer': '0', 'skipShow': '', 'anyQualities': ['4', '16', '32', '64', '128', '256'], 'indexerLang': 'en', 'wanted-begin': '0', 'blacklist': '', 'rootDir': 'G:\\videos\\tv', 'whichSeries': 'theTVDB|1|http://thetvdb.com/?tab=series&id=|289855|Good Witch|2015-02-28', 'wanted-latest': '0', 'whitelist': '', 'subtitles': 'on'}
_finish_time: None
query:
path: /home/addShows/addNewShow
_cookies: Set-Cookie: sickgear-session="2|1:0|10:1426420709|16:sickgear-session|60:SU9nUTk5R1NTOStVVTEwcy9UYkRHZGZ3aDY0dUpFZVdqazRWbmI5bzAyQT0=|905c1e08978f8e7915b8efcbf63a8d08e3d3b8581bc0e0595f2bc2cc989d0a5b"
method: POST
remote_ip: 127.0.0.1
```

**Comment by Th3MadHatter** [comment]
Fixed in new update.
