### ISSUE TITLE
PPing recognizing files as wrong episodes

### ISSUE THREAD

**Issue by Th3MadHatter** [SickGear/SickGear#326]
BRANCH: (develop) / COMMIT: (a6274c59109b2374f779a697366915293b4f0eba) 

Snatching them works just fine but as you can see it tries to rename episodes to different numbers like ep 22 turns into ep 21 for example which either errors out or overwrites the previous episode which did PP properly.

```
2015-04-15 15:02:29 WARNING  TORNADO :: Processing failed for G:\downloads\complete\processed\tv\the.thundermans.s02e19.its.not.what.you.link.720p.hdtv.x264-w4f.mkv\the.thundermans.s02e19.its.not.what.you.link.720p.hdtv.x264-w4f.mkv: 
2015-04-15 15:02:29 DEBUG    TORNADO :: File exists and new file is smaller, marking it unsafe to replace
2015-04-15 15:02:29 DEBUG    TORNADO :: File G:\videos\tv\The Thundermans\The Thundermans - S02E18 - Mall Time Crooks.mkv is larger than G:\downloads\complete\processed\tv\the.thundermans.s02e19.its.not.what.you.link.720p.hdtv.x264-w4f.mkv\the.thundermans.s02e19.its.not.what.you.link.720p.hdtv.x264-w4f.mkv
2015-04-15 15:02:29 DEBUG    TORNADO :: Is ep a priority download: False
2015-04-15 15:02:29 DEBUG    TORNADO :: Quality of the episode we're processing: 4
2015-04-15 15:02:29 DEBUG    TORNADO :: Snatch history had a quality in it, using that: HD TV
2015-04-15 15:02:29 DEBUG    TORNADO :: Checking if G:\videos\tv\The Thundermans\The Thundermans - S02E18 - Mall Time Crooks-thumb.jpg exists: False
2015-04-15 15:02:29 DEBUG    TORNADO :: Checking if G:\videos\tv\The Thundermans\The Thundermans - S02E18 - Mall Time Crooks.nfo exists: True
2015-04-15 15:02:29 DEBUG    TORNADO :: Setter sets location to G:\videos\tv\The Thundermans\The Thundermans - S02E18 - Mall Time Crooks.mkv
2015-04-15 15:02:29 DEBUG    TORNADO :: 274283: Loading episode details from DB for episode 2x18
2015-04-15 15:02:29 DEBUG    TORNADO :: 274283: An object for episode 2x18 didn't exist in the cache, trying to create it
2015-04-15 15:02:29 DEBUG    TORNADO :: Retrieving episode object for 2x18
2015-04-15 15:02:29 DEBUG    TORNADO :: Parsed the.thundermans.s02e19.its.not.what.you.link.720p.hdtv.x264-w4f into the thundermans - S2E18 [GROUP: w4f] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-04-15 15:02:29 DEBUG    TORNADO :: Converted parsed result the.thundermans.s02e19.its.not.what.you.link.720p.hdtv.x264-w4f into the thundermans - S2E18 [GROUP: w4f] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-04-15 15:02:29 DEBUG    TORNADO :: Using ALL regexes
2015-04-15 15:02:29 INFO     TORNADO :: Analyzing name 'the.thundermans.s02e19.its.not.what.you.link.720p.hdtv.x264-w4f.mkv'
2015-04-15 15:02:29 INFO     TORNADO :: Processing G:\downloads\complete\processed\tv\the.thundermans.s02e19.its.not.what.you.link.720p.hdtv.x264-w4f.mkv\the.thundermans.s02e19.its.not.what.you.link.720p.hdtv.x264-w4f.mkv (the.thundermans.s02e19.its.not.what.you.link.720p.hdtv.x264-w4f.mkv)
2015-04-15 15:02:29 DEBUG    TORNADO :: Using ALL regexes
2015-04-15 15:02:29 DEBUG    TORNADO :: PostProcessing VideoInRar: []
2015-04-15 15:02:29 DEBUG    TORNADO :: PostProcessing RarContent: []
2015-04-15 15:02:29 DEBUG    TORNADO :: PostProcessing VideoFiles: [u'G:\\downloads\\complete\\processed\\tv\\the.thundermans.s02e19.its.not.what.you.link.720p.hdtv.x264-w4f.mkv\\the.thundermans.s02e19.its.not.what.you.link.720p.hdtv.x264-w4f.mkv']
2015-04-15 15:02:29 DEBUG    TORNADO :: PostProcessing Files: [u'G:\\downloads\\complete\\processed\\tv\\the.thundermans.s02e19.its.not.what.you.link.720p.hdtv.x264-w4f.mkv\\the.thundermans.s02e19.its.not.what.you.link.720p.hdtv.x264-w4f.mkv']
2015-04-15 15:02:29 DEBUG    TORNADO :: PostProcessing Dirs: []
2015-04-15 15:02:29 DEBUG    TORNADO :: PostProcessing Path: G:\downloads\complete\processed\tv
2015-04-15 15:02:29 DEBUG    TORNADO :: TV_DOWNLOAD_DIR: 
2015-04-15 15:02:29 DEBUG    TORNADO :: Processing folder G:\downloads\complete\processed\tv\the.thundermans.s02e19.its.not.what.you.link.720p.hdtv.x264-w4f.mkv
2015-04-15 14:58:56 WARNING  TORNADO :: Problem(s) during processing
2015-04-15 14:58:56 INFO     TORNADO :: Processing succeeded for G:\downloads\complete\processed\tv\a\the.thundermans.s02e22.one.hit.thunder.720p.hdtv.x264-w4f.mkv
2015-04-15 14:58:56 DEBUG    TORNADO :: KODI: JSON response: {u'jsonrpc': u'2.0', u'id': 1, u'result': u'OK'}
2015-04-15 14:58:55 DEBUG    TORNADO :: KODI: Contacting via url: http://192.168.1.116:8080/jsonrpc
2015-04-15 14:58:55 DEBUG    TORNADO :: KODI: JSON command: {"jsonrpc":"2.0","method":"VideoLibrary.Scan","params":{"directory":"nfs://192.168.1.120/TVShows/The Thundermans/"},"id":1}
2015-04-15 14:58:55 DEBUG    TORNADO :: KODI: Updating The Thundermans on 192.168.1.116:8080 at nfs://192.168.1.120/TVShows/The Thundermans/
2015-04-15 14:58:55 DEBUG    TORNADO :: KODI: Received Show: The Thundermans with ID: 9 Path: nfs://192.168.1.120/TVShows/The Thundermans/
2015-04-15 14:58:55 DEBUG    TORNADO :: KODI: JSON response: {u'jsonrpc': u'2.0', u'id': 1, u'result': {u'tvshowdetails': {u'tvshowid': 9, u'file': u'nfs://192.168.1.120/TVShows/The Thundermans/', u'label': u'The Thundermans'}}}
2015-04-15 14:58:55 DEBUG    TORNADO :: KODI: Contacting via url: http://192.168.1.116:8080/jsonrpc
2015-04-15 14:58:55 DEBUG    TORNADO :: KODI: JSON command: {"jsonrpc":"2.0","method":"VideoLibrary.GetTVShowDetails","params":{"tvshowid":9, "properties": ["file"]},"id":1}
2015-04-15 14:58:55 DEBUG    TORNADO :: KODI: JSON response: {u'jsonrpc': u'2.0', u'id': 1, u'result': {u'limits': {u'start': 0, u'total': 136, u'end': 136}, u'tvshows': [{u'tvshowid': 1, u'label': u'Young & Hungry'}, {u'tvshowid': 2, u'label': u'Yonderland'}, {u'tvshowid': 3, u'label': u'Wizards vs Aliens'}, {u'tvshowid': 4, u'label': u'Under the Dome'}, {u'tvshowid': 5, u'label': u'Undateable (2014)'}, {u'tvshowid': 6, u'label': u'Two and a Half Men'}, {u'tvshowid': 7, u'label': u'The Wrong Mans'}, {u'tvshowid': 8, u'label': u'The Vampire Diaries'}, {u'tvshowid': 9, u'label': u'The Thundermans'}, {u'tvshowid': 10, u'label': u'The Strain'}, {u'tvshowid': 11, u'label': u'The Simpsons'}, {u'tvshowid': 12, u'label': u'The Originals'}, {u'tvshowid': 13, u'label': u'The Musketeers'}, {u'tvshowid': 14, u'label': u'The Millers'}, {u'tvshowid': 16, u'label': u'The McCarthys'}, {u'tvshowid': 17, u'label': u'The Librarians (2014)'}, {u'tvshowid': 18, u'label': u'The Last Ship'}, {u'tvshowid': 19, u'label': u'The Goldbergs (2013)'}, {u'tvshowid': 20, u'label': u'The Flash (2014)'}, {u'tvshowid': 21, u'label': u'The Exes'}, {u'tvshowid': 22, u'label': u'The Blacklist'}, {u'tvshowid': 23, u'label': u'The Big Bang Theory'}, {u'tvshowid': 24, u'label': u'The Awesomes'}, {u'tvshowid': 25, u'label': u'The 100'}, {u'tvshowid': 26, u'label': u'Teen Wolf'}, {u'tvshowid': 27, u'label': u'Supernatural'}, {u'tvshowid': 28, u'label': u'Supah Ninjas'}, {u'tvshowid': 29, u'label': u'Suits'}, {u'tvshowid': 30, u'label': u'Steven Universe'}, {u'tvshowid': 31, u'label': u'Star Wars Rebels'}, {u'tvshowid': 32, u'label': u'Star vs. the Forces of Evil'}, {u'tvshowid': 33, u'label': u'Stalker'}, {u'tvshowid': 34, u'label': u'Spooksville'}, {u'tvshowid': 35, u'label': u'Space Dandy'}, {u'tvshowid': 36, u'label': u'South Park'}, {u'tvshowid': 37, u'label': u'Sleepy Hollow'}, {u'tvshowid': 38, u'label': u'Sirens (2014)'}, {u'tvshowid': 39, u'label': u'Silicon Valley'}, {u'tvshowid': 40, u'label': u'Scorpion'}, {u'tvshowid': 41, u'label': u'Salem'}, {u'tvshowid': 42, u'label': u'Rick and Morty'}, {u'tvshowid': 43, u'label': u'Resurrection'}, {u'tvshowid': 44, u'label': u'Regular Show'}, {u'tvshowid': 45, u'label': u'Quick Draw'}, {u'tvshowid': 46, u'label': u'Pretty Little Liars'}, {u'tvshowid': 47, u'label': u'Phineas and Ferb'}, {u'tvshowid': 48, u'label': u'Person of Interest'}, {u'tvshowid': 49, u'label': u'Penny Dreadful'}, {u'tvshowid': 50, u'label': u'Over The Garden Wall'}, {u'tvshowid': 51, u'label': u'Once Upon a Time (2011)'}, {u'tvshowid': 52, u'label': u'New Girl'}, {u'tvshowid': 53, u'label': u'Naruto Shippuden'}, {u'tvshowid': 54, u'label': u'My Little Pony: Friendship is Magic'}, {u'tvshowid': 55, u'label': u'Mr. Pickles'}, {u'tvshowid': 56, u'label': u'Mom'}, {u'tvshowid': 57, u'label': u'Mike Tyson Mysteries'}, {u'tvshowid': 58, u'label': u'Melissa & Joey'}, {u'tvshowid': 59, u'label': u'Max & Shred'}, {u'tvshowid': 60, u'label': u"Marvel's Agents of S.H.I.E.L.D."}, {u'tvshowid': 61, u'label': u"Marvel's Agent Carter"}, {u'tvshowid': 62, u'label': u'Marry Me'}, {u'tvshowid': 63, u'label': u'Lost Girl'}, {u'tvshowid': 64, u'label': u'Liv and Maddie'}, {u'tvshowid': 65, u'label': u'Legends (2014)'}, {u'tvshowid': 66, u'label': u'Last Man Standing (2011)'}, {u'tvshowid': 67, u'label': u'Lab Rats (2012)'}, {u'tvshowid': 68, u'label': u'K.C. Undercover'}, {u'tvshowid': 69, u'label': u'Jessie (2011)'}, {u'tvshowid': 70, u'label': u"I Didn't Do It (2014)"}, {u'tvshowid': 71, u'label': u'How to Get Away With Murder'}, {u'tvshowid': 72, u'label': u'Hot in Cleveland'}, {u'tvshowid': 73, u'label': u'Hollands Hoop'}, {u'tvshowid': 74, u'label': u'Hemlock Grove'}, {u'tvshowid': 75, u'label': u'Helix'}, {u'tvshowid': 76, u'label': u'Haven'}, {u'tvshowid': 77, u'label': u'Grimm'}, {u'tvshowid': 78, u'label': u'Gravity Falls'}, {u'tvshowid': 79, u'label': u'Gotham'}, {u'tvshowid': 80, u'label': u'Give Out Girls'}, {u'tvshowid': 81, u'label': u'Girl Meets World'}, {u'tvshowid': 82, u'label': u'Galavant'}, {u'tvshowid': 83, u'label': u'From Dusk Till Dawn: The Series'}, {u'tvshowid': 84, u'label': u'Forever (2014)'}, {u'tvshowid': 85, u'label': u'Fargo'}, {u'tvshowid': 86, u'label': u'Family Guy'}, {u'tvshowid': 87, u'label': u'Falling Skies'}, {u'tvshowid': 88, u'label': u'Faking It (2014)'}, {u'tvshowid': 89, u'label': u'Fairy Tail'}, {u'tvshowid': 90, u'label': u'Extant'}, {u'tvshowid': 91, u'label': u'Every Witch Way'}, {u'tvshowid': 92, u'label': u'Elementary'}, {u'tvshowid': 93, u'label': u'Dominion'}, {u'tvshowid': 94, u'label': u'Dog with a Blog'}, {u'tvshowid': 95, u'label': u'Doctor Who (2005)'}, {u'tvshowid': 96, u'label': u'Defiance'}, {u'tvshowid': 97, u'label': u'Deadtime Stories'}, {u'tvshowid': 98, u'label': u'Deadbeat'}, {u'tvshowid': 99, u'label': u"Da Vinci's Demons"}, {u'tvshowid': 101, u'label': u'Continuum'}, {u'tvshowid': 102, u'label': u'Constantine'}, {u'tvshowid': 103, u'label': u'Castle (2009)'}, {u'tvshowid': 104, u'label': u'Brooklyn Nine-Nine'}, {u'tvshowid': 105, u'label': u'Brickleberry'}, {u'tvshowid': 106, u'label': u'Bones'}, {u'tvshowid': 107, u'label': u'BoJack Horseman'}, {u'tvshowid': 108, u'label': u'Black Dynamite'}, {u'tvshowid': 109, u'label': u'Bitten'}, {u'tvshowid': 110, u'label': u'Bella and the Bulldogs'}, {u'tvshowid': 111, u'label': u'Beauty and the Beast (2012)'}, {u'tvshowid': 112, u'label': u'Banshee'}, {u'tvshowid': 113, u'label': u'Baby Daddy'}, {u'tvshowid': 114, u'label': u'Awkward.'}, {u'tvshowid': 115, u'label': u'Atlantis (2013)'}, {u'tvshowid': 116, u'label': u'Arrow'}, {u'tvshowid': 117, u'label': u'Archer (2009)'}, {u'tvshowid': 118, u'label': u'American Dad!'}, {u'tvshowid': 119, u'label': u'All Hail King Julien'}, {u'tvshowid': 120, u'label': u'Adventure Time'}, {u'tvshowid': 121, u'label': u'2 Broke Girls'}, {u'tvshowid': 122, u'label': u'12 Monkeys'}, {u'tvshowid': 123, u'label': u'Unbreakable Kimmy Schmidt'}, {u'tvshowid': 124, u'label': u'The Odd Couple (2015)'}, {u'tvshowid': 125, u'label': u'Perception'}, {u'tvshowid': 126, u'label': u'Good Witch'}, {u'tvshowid': 127, u'label': u'Dig'}, {u'tvshowid': 128, u'label': u'One Big Happy'}, {u'tvshowid': 129, u'label': u'iZombie'}, {u'tvshowid': 130, u'label': u'Powers (2015)'}, {u'tvshowid': 131, u'label': u'Battle Creek'}, {u'tvshowid': 132, u'label': u'The Mentalist'}, {u'tvshowid': 133, u'label': u'Weird Loners'}, {u'tvshowid': 134, u'label': u'Cougar Town'}, {u'tvshowid': 135, u'label': u'Olympus'}, {u'tvshowid': 136, u'label': u'The Lizzie Borden Chronicles'}, {u'tvshowid': 137, u'label': u"Marvel's Daredevil"}, {u'tvshowid': 138, u'label': u'Tatau'}]}}
2015-04-15 14:58:54 DEBUG    TORNADO :: KODI: Contacting via url: http://192.168.1.116:8080/jsonrpc
2015-04-15 14:58:54 DEBUG    TORNADO :: KODI: JSON command: {"jsonrpc":"2.0","method":"VideoLibrary.GetTVShows","id":1}
2015-04-15 14:58:54 DEBUG    TORNADO :: KODI: Updating library for show The Thundermans
2015-04-15 14:58:54 INFO     TORNADO :: KODI: Updating library on host: 192.168.1.116:8080
2015-04-15 14:58:54 DEBUG    TORNADO :: Notification for NMJ scan update not enabled, skipping this notification
2015-04-15 14:58:54 DEBUG    TORNADO :: Notification for XBMC not enabled, skipping this notification
2015-04-15 14:58:54 DEBUG    TORNADO :: formatting pattern: %SN - %Sx%0E - %EN - %QN -> The Thundermans - 2x21 - Call of Lunch Duty - HD TV
2015-04-15 14:58:54 DEBUG    TORNADO :: Using cached parse result for: the.thundermans.s02e22.one.hit.thunder.720p.hdtv.x264-w4f
2015-04-15 14:58:54 DEBUG    TORNADO :: Using NORMAL regexs
2015-04-15 14:58:53 DEBUG    TORNADO :: Checking if G:\videos\tv\The Thundermans\The Thundermans - S02E21 - Call of Lunch Duty-thumb.jpg exists: False
2015-04-15 14:58:53 DEBUG    TORNADO :: Checking if G:\videos\tv\The Thundermans\The Thundermans - S02E21 - Call of Lunch Duty.nfo exists: True
2015-04-15 14:58:53 DEBUG    TORNADO :: No thumb is available for this episode, not creating a thumb
2015-04-15 14:58:53 DEBUG    TORNADO :: Metadata provider XBMC 12+ creating episode thumbnail for The Thundermans - 2x21 - Call of Lunch Duty
2015-04-15 14:58:53 DEBUG    TORNADO :: formatting pattern: %SN - %Sx%0E - %EN -> The Thundermans - 2x21 - Call of Lunch Duty
2015-04-15 14:58:53 DEBUG    TORNADO :: Using cached parse result for: the.thundermans.s02e22.one.hit.thunder.720p.hdtv.x264-w4f
2015-04-15 14:58:53 DEBUG    TORNADO :: Using NORMAL regexs
2015-04-15 14:58:53 DEBUG    TORNADO :: Checking if G:\videos\tv\The Thundermans\The Thundermans - S02E21 - Call of Lunch Duty-thumb.jpg exists: False
2015-04-15 14:58:53 DEBUG    TORNADO :: Writing episode nfo file to G:\videos\tv\The Thundermans\The Thundermans - S02E21 - Call of Lunch Duty.nfo
2015-04-15 14:58:53 DEBUG    TORNADO :: Creating metadata for episode 2x21
2015-04-15 14:58:53 DEBUG    TORNADO :: Metadata provider XBMC 12+ creating episode metadata for The Thundermans - 2x21 - Call of Lunch Duty
2015-04-15 14:58:53 DEBUG    TORNADO :: formatting pattern: %SN - %Sx%0E - %EN -> The Thundermans - 2x21 - Call of Lunch Duty
2015-04-15 14:58:53 DEBUG    TORNADO :: Using cached parse result for: the.thundermans.s02e22.one.hit.thunder.720p.hdtv.x264-w4f
2015-04-15 14:58:53 DEBUG    TORNADO :: Using NORMAL regexs
2015-04-15 14:58:53 DEBUG    TORNADO :: Checking if G:\videos\tv\The Thundermans\The Thundermans - S02E21 - Call of Lunch Duty.nfo exists: False
2015-04-15 14:58:53 DEBUG    TORNADO :: Transaction with 1 queries executed
2015-04-15 14:58:53 DEBUG    TORNADO :: Setter sets location to G:\videos\tv\The Thundermans\The Thundermans - S02E21 - Call of Lunch Duty.mkv
2015-04-15 14:58:53 DEBUG    TORNADO :: Notification for NMJ scan update not enabled, skipping this notification
2015-04-15 14:58:53 DEBUG    TORNADO :: formatting pattern: %SN - %Sx%0E - %EN -> The Thundermans - 2x21 - Call of Lunch Duty
2015-04-15 14:58:53 DEBUG    TORNADO :: Using cached parse result for: the.thundermans.s02e22.one.hit.thunder.720p.hdtv.x264-w4f
2015-04-15 14:58:53 DEBUG    TORNADO :: Using NORMAL regexs
2015-04-15 14:58:53 DEBUG    TORNADO :: 274283: Downloaded English subtitles for episode 2x21
2015-04-15 14:58:52 DEBUG    TORNADO :: STATUS IS 404
2015-04-15 14:58:52 DEBUG    TORNADO :: 274283: Saving episode details to database
AATypeError: %d format: a number is required, not NoneType
AA    r = self.session.get('%s/tvshow-%d-%d.html' % (self.server_url, series_id, season))
AA  File "C:\SickGear\lib\subliminal\services\tvsubtitles.py", line 76, in get_episode_id
AA    result = function(*args)
AA  File "C:\SickGear\lib\subliminal\cache.py", line 127, in cached
AA    ep_id = self.get_episode_id(sid, season, episode)
AA  File "C:\SickGear\lib\subliminal\services\tvsubtitles.py", line 123, in query
AA    return self.query(video.path or video.release, languages, get_keywords(video.guess), video.series, video.season, video.episode)
AA  File "C:\SickGear\lib\subliminal\services\tvsubtitles.py", line 116, in list_checked
AA    return self.list_checked(video, languages)
AA  File "C:\SickGear\lib\subliminal\services\__init__.py", line 155, in list
AA    result = service.list(task.video, task.languages)
AA  File "C:\SickGear\lib\subliminal\core.py", line 131, in consume_task
AA    result = consume_task(task, service_instances)
AA  File "C:\SickGear\lib\subliminal\api.py", line 57, in list_subtitles
AATraceback (most recent call last):
2015-04-15 14:58:52 ERROR    SUBLIMINAL :: Error consuming task ListTask(Episode(G:\videos\tv\The Thundermans\The Thundermans - S02E21 - Call of Lunch Duty.mkv), language_set([Language(Dutch; Flemish), Language(English)]), tvsubtitles, ServiceConfig(True, C:\SickGear\cache))
2015-04-15 14:58:52 DEBUG    TORNADO :: 274283: Downloading subtitles for episode 2x21
2015-04-15 14:58:52 DEBUG    TORNADO :: Setter sets location to G:\videos\tv\The Thundermans\The Thundermans - S02E21 - Call of Lunch Duty.mkv
2015-04-15 14:58:52 DEBUG    TORNADO :: Moving file from G:\downloads\complete\processed\tv\a\the.thundermans.s02e22.one.hit.thunder.720p.hdtv.x264-w4f.mkv to G:\videos\tv\The Thundermans\The Thundermans - S02E21 - Call of Lunch Duty.mkv
2015-04-15 14:58:52 DEBUG    TORNADO :: Checking if the path G:\videos\tv\The Thundermans already exists
2015-04-15 14:58:52 DEBUG    TORNADO :: Destination folder for this episode: G:\videos\tv\The Thundermans
2015-04-15 14:58:52 DEBUG    TORNADO :: formatting pattern: %SN - S%0SE%0E - %EN -> The Thundermans - S02E21 - Call of Lunch Duty
2015-04-15 14:58:52 DEBUG    TORNADO :: Using cached parse result for: the.thundermans.s02e22.one.hit.thunder.720p.hdtv.x264-w4f
2015-04-15 14:58:52 DEBUG    TORNADO :: Using NORMAL regexs
2015-04-15 14:58:52 WARNING  TORNADO :: Couldn't find release in snatch history
2015-04-15 14:58:52 DEBUG    TORNADO :: Unable to parse the filename a into a valid show
2015-04-15 14:58:52 DEBUG    TORNADO :: Using ALL regexes
2015-04-15 14:58:52 DEBUG    TORNADO :: Transaction with 1 queries executed
2015-04-15 14:58:52 DEBUG    TORNADO :: Found release name the.thundermans.s02e22.one.hit.thunder.720p.hdtv.x264-w4f
2015-04-15 14:58:52 INFO     TORNADO :: Trying to clean any empty folders under G:\videos\tv\The Thundermans
2015-04-15 14:58:51 DEBUG    TORNADO :: Deleting file G:\videos\tv\The Thundermans\The Thundermans - S02E21 - Call of Lunch Duty.nfo
2015-04-15 14:58:51 DEBUG    TORNADO :: Deleting file G:\videos\tv\The Thundermans\The Thundermans - S02E21 - Call of Lunch Duty.mkv
2015-04-15 14:58:51 DEBUG    TORNADO :: This download is marked a priority download so I'm going to replace an existing file if I find one
2015-04-15 14:58:51 DEBUG    TORNADO :: File G:\videos\tv\The Thundermans\The Thundermans - S02E21 - Call of Lunch Duty.mkv is the same size as G:\downloads\complete\processed\tv\a\the.thundermans.s02e22.one.hit.thunder.720p.hdtv.x264-w4f.mkv
2015-04-15 14:58:51 DEBUG    TORNADO :: Is ep a priority download: True
2015-04-15 14:58:51 DEBUG    TORNADO :: Quality of the episode we're processing: 4
2015-04-15 14:58:51 DEBUG    TORNADO :: Snatch history had a quality in it, using that: HD TV
2015-04-15 14:58:51 DEBUG    TORNADO :: Checking if G:\videos\tv\The Thundermans\The Thundermans - S02E21 - Call of Lunch Duty-thumb.jpg exists: False
2015-04-15 14:58:51 DEBUG    TORNADO :: Checking if G:\videos\tv\The Thundermans\The Thundermans - S02E21 - Call of Lunch Duty.nfo exists: True
2015-04-15 14:58:51 DEBUG    TORNADO :: Setter sets location to G:\videos\tv\The Thundermans\The Thundermans - S02E21 - Call of Lunch Duty.mkv
2015-04-15 14:58:51 DEBUG    TORNADO :: 274283: Loading episode details from DB for episode 2x21
2015-04-15 14:58:51 DEBUG    TORNADO :: 274283: An object for episode 2x21 didn't exist in the cache, trying to create it
2015-04-15 14:58:51 DEBUG    TORNADO :: Retrieving episode object for 2x21
2015-04-15 14:58:51 DEBUG    TORNADO :: Parsed the.thundermans.s02e22.one.hit.thunder.720p.hdtv.x264-w4f into the thundermans - S2E21 [GROUP: w4f] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-04-15 14:58:51 DEBUG    TORNADO :: Converted parsed result the.thundermans.s02e22.one.hit.thunder.720p.hdtv.x264-w4f into the thundermans - S2E21 [GROUP: w4f] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-04-15 14:58:51 DEBUG    TORNADO :: Using ALL regexes
2015-04-15 14:58:51 INFO     TORNADO :: Analyzing name u'the.thundermans.s02e22.one.hit.thunder.720p.hdtv.x264-w4f.mkv'
2015-04-15 14:58:51 INFO     TORNADO :: Analyzing name None
2015-04-15 14:58:51 INFO     TORNADO :: Processing G:\downloads\complete\processed\tv\a\the.thundermans.s02e22.one.hit.thunder.720p.hdtv.x264-w4f.mkv (None)
2015-04-15 14:58:51 INFO     TORNADO :: Processing succeeded for G:\downloads\complete\processed\tv\a\the.thundermans.s02e15.doubles.trouble.720p.hdtv.x264-w4f.mk
```

**Comment by JackDandy** [comment]
no pp issues will be taken unless tested positive against pr 247
