### ISSUE TITLE
Postprocessing causes an exception when processing directories that look like releases

### ISSUE THREAD

**Issue by ressu** [SickGear/SickGear#430]
This has been reproduced with BRANCH: (develop) / COMMIT: (df6975833f082d4de0b48391fa1ea16fe69b570c) 

When postrpocessing is being run, the run is terminated with an exception error in the logs.

```
2015-06-20 11:48:55 DEBUG    POSTPROCESSER :: Converted parsed result How.Do.They.Do.It.S01.TVRip.x264-NoGroup into How Do They Do It - S1 [GROUP: NoGroup] [ABD: False] [ANIME: False] [whichReg: ['season_only']]
2015-06-20 11:48:55 DEBUG    POSTPROCESSER :: Parsed /srv/videos/incoming/downloaded/Sick-TV/How.Do.They.Do.It.S01.TVRip.x264-NoGroup into How Do They Do It - S1 [GROUP: NoGroup] [ABD: False] [ANIME: False] [whichReg: ['season_only']]
2015-06-20 11:48:55 DB       POSTPROCESSER :: sickbeard.db: SELECT * FROM tv_episodes WHERE release_name = ? with args [u'/srv/videos/incoming/downloaded/Sick-TV/How.Do.They.Do.It.S01.TVRip.x264-NoGroup']
2015-06-20 11:48:56 DB       POSTPROCESSER :: sickbeard.db: SELECT * FROM tv_episodes WHERE release_name = ? with args [u'How.They.Do.It.S01E06.TVRip.x264']
2015-06-20 11:48:56 DEBUG    POSTPROCESSER :: Found a video, but that release for "How Do They Do It" was already processed, skipping: How.They.Do.It.S01E06.TVRip.x264.mp4
2015-06-20 11:48:56 ERROR    POSTPROCESSER :: Exception generated in thread POSTPROCESSER: list index out of range
2015-06-20 11:48:56 DEBUG    POSTPROCESSER :: 'Traceback (most recent call last):\n  File "/opt/sickgear/sickbeard/scheduler.py", line 90, in run\n    self.action.run()\n  File "/opt/sickgear/sickbeard/autoPostProcesser.py", line 46, in run\n    processTV.processDir(sickbeard.TV_DOWNLOAD_DIR)\n  File "/opt/sickgear/sickbeard/processTV.py", line 585, in processDir\n    return ProcessTVShow().process_dir(dir_name, nzb_name, process_method, force, force_replace, failed, type, cleanup)\n  File "/opt/sickgear/sickbeard/processTV.py", line 271, in process_dir\n    self._process_media(process_path, video_pick, nzb_name, process_method, force, force_replace, use_trash=cleanup)\n  File "/opt/sickgear/sickbeard/processTV.py", line 502, in _process_media\n    if self._already_postprocessed(process_path, cur_video_file, force):\n  File "/opt/sickgear/sickbeard/processTV.py", line 475, in _already_postprocessed\n    parse_result.episode_numbers[0])\nIndexError: list index out of range\n'
```

After  a bit of debugging, the origin of the problem is in the directory name. I have the following structure in my incoming directory:
```
in/How.Do.They.Do.It.S01.TVRip.x264-NoGroup/
in/How.Do.They.Do.It.S01.TVRip.x264-NoGroup/How.They.Do.It.S01E06.TVRip.x264.mp4
```
This causes the postprocessing run to fail on the second attempt. The reason is that the directory name is used to parse the episode information. The problem is that the directory name doesn't contain an episode number and the postprocess tries to invoke reset_status unconditionally.

I would have submitted a pull request with a fix, but I still don't really undestand the reasoning behind reset_status and I can't figure out the right way to fix this.

**Comment by alazare619** [comment]
I can also confirm this as well..Season packs seem to be a big problem.

**Comment by alazare619** [comment]
I can confirm that removing the group and format (x264) seems to fix the issue

**Comment by alazare619** [comment]
can we get a status update on this.

**Comment by JackDandy** [comment]
Yeah, I also see the issue as very well described. I noticed that if i simply navigate to inside the folder with the media on hitting the "Browse..." button the video is processed fine.

**Comment by JackDandy** [comment]
#488
