### ISSUE TITLE
Error searching directory for episodes: can only concatenate list (not "int") to list

### ISSUE THREAD

**Issue by aMvEL2** [SickGear/SickGear#506]
BRANCH: (develop) / COMMIT: (1f148c25d134f216746f5697a53c467484bfd4c9) 

<b>Issue:</b>
Existing files in show directory not found when adding new existing show. Also rescanning the show afterwards does not work.

<b>Reproduction:</b>
1. Add a new existing show in SickGear containing already downloaded episodes in the show folder.
2. Wait for it to be added and check show page in SickGear. No files added.

It seems to error out according to the log file.

<b>Log:</b>
<pre>
2015-09-10 23:21:50 ERROR    SHOWQUEUE-ADD :: Error searching directory for episodes: can only concatenate list (not "int") to list
2015-09-10 23:21:50 DEBUG    SHOWQUEUE-ADD :: Traceback (most recent call last):
  File "e:\Program\SickGear-develop\sickbeard\show_queue.py", line 401, in run
    self.show.loadEpisodesFromDir()
  File "e:\Program\SickGear-develop\sickbeard\tv.py", line 414, in loadEpisodesFromDir
    curEpisode = self.makeEpFromFile(ek.ek(os.path.join, self._location, mediaFile))
  File "e:\Program\SickGear-develop\sickbeard\tv.py", line 729, in makeEpFromFile
    % (cur_ep.status, Quality.compositeStatus(Quality.DOWNLOADED, new_quality)), logger.DEBUG)
  File "e:\Program\SickGear-develop\sickbeard\common.py", line 283, in compositeStatus
    return status + 100 * quality
TypeError: can only concatenate list (not "int") to list
</pre>

It happens on my Synology NAS, and also on a fresh install on windows (which is where the log snippet is from)

**Comment by JackDandy** [comment]
#508
