### ISSUE TITLE
Post processing (notification?) error with more than one plex media server host

### ISSUE THREAD

**Issue by jillmess** [SickGear/SickGear#556]
BRANCH: (master) / COMMIT: (1e6c1618871f8cb5781d35114f21d249c270245f)

Added a second plex media server to my local network and included it in the Plex Media Server notifications section (now 2 x ip:port entries separated by comma).
'Test Plex Server' reports Successful test of Plex server(s), but I now get the following post processing errors reported.
Note that the file is actually correctly processed except that an empty folder is left in the Sabnzbd 'completed downloads' location.

<pre>
2015-11-13 15:12:20 DEBUG    TORNADO :: Notification for NMJ scan update not enabled, skipping this notification
2015-11-13 15:12:20 ERROR    TORNADO :: Uncaught exception GET /home/postprocess/processEpisode?nzbName=Life.in.Pieces.S01E07.HDTV.x264-KILLERS.nzb&failed=0&quiet=1&dir=%2Fc%2F.sabnzbd%2Fdownloads%2Fcomplete%2FLife.in.Pieces.S01E07.HDTV.x264-KILLERS (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:8088', method='GET', uri='/home/postprocess/processEpisode?nzbName=Life.in.Pieces.S01E07.HDTV.x264-KILLERS.nzb&failed=0&quiet=1&dir=%2Fc%2F.sabnzbd%2Fdownloads%2Fcomplete%2FLife.in.Pieces.S01E07.HDTV.x264-KILLERS', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Cookie': 'sickgear-session="2|1:0|10:1447391531|16:sickgear-session|60:Q2tiUWdLTnNST0d6RmlxdHc2NTU1UFpYYzcrSGEwUGR2QzI5NVhTd2lEZz0=|ec164d13d022c3ebe1580a1a6906e2c24e73a116999654668b724e99a991e919"', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8088', 'Accept': '*/*', 'User-Agent': 'python-requests/2.7.0 CPython/2.7.3 Linux/2.6.37.6.RNx86_64.2.4'})
Traceback (most recent call last):
  File "/c/.sickgear/tornado/web.py", line 1418, in _execute
    result = yield result
  File "/c/.sickgear/tornado/gen.py", line 870, in run
    value = future.result()
  File "/c/.sickgear/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/c/.sickgear/tornado/gen.py", line 215, in wrapper
    result = func(*args, **kwargs)
  File "/c/.sickgear/sickbeard/webserve.py", line 294, in get
    result = method(**kwargss)
  File "/c/.sickgear/sickbeard/webserve.py", line 2009, in processEpisode
    failed=not '0' == failed)
  File "/c/.sickgear/sickbeard/processTV.py", line 585, in processDir
    return ProcessTVShow().process_dir(dir_name, nzb_name, process_method, force, force_replace, failed, type, cleanup)
  File "/c/.sickgear/sickbeard/processTV.py", line 271, in process_dir
    self._process_media(process_path, video_pick, nzb_name, process_method, force, force_replace, use_trash=cleanup)
  File "/c/.sickgear/sickbeard/processTV.py", line 510, in _process_media
    file_success = processor.process()
  File "/c/.sickgear/sickbeard/postProcessor.py", line 1018, in process
    notifiers.plex_notifier.update_library(ep_obj)
  File "/c/.sickgear/sickbeard/notifiers/plex.py", line 250, in update_library
    hosts_try = (hosts_all.copy(), hosts_match.copy())[len(hosts_match)]
IndexError: tuple index out of range
2015-11-13 15:13:48 INFO     TORNADO :: PLEX: Updating all hosts with TV sections: 192.168.2.75:32400, 192.168.2.30:32400
</pre>

**Comment by adam111316** [comment]
@JackDandy: Your lines of code, you can fix it :P

**Comment by JackDandy** [comment]
More info needed, what did you have in the field ?

**Comment by jillmess** [comment]
A screenshot of the relevant setup page from SickGear is below.
Both servers are online 24/7 and accessable from a variety of media devices.
Everything works as normal with either of these servers entered individually, but with both added the error occurs.

SickGear config
![plex media server notification setup](https://cloud.githubusercontent.com/assets/6894183/11165457/8a847ab2-8b5b-11e5-9522-08bec60843d0.jpg)


Only 192.168.2.30:32400 setup
<pre>
2015-11-15 05:57:01 DEBUG    TORNADO :: Parsed Bosch.S01E10.DVDRip.x264-DEMAND into Bosch - S1E10 [GROUP: DEMAND] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-11-15 05:57:01 DEBUG    TORNADO :: formatting pattern: %SN - %Sx%0E - %EN - %QN -> Bosch - 1x10 - Us and Them - SD DVD
2015-11-15 05:57:01 DEBUG    TORNADO :: Notification for NMJ scan update not enabled, skipping this notification
2015-11-15 05:57:02 INFO     TORNADO :: PLEX: Updating hosts where TV section paths match the downloaded show: 192.168.2.30:32400
2015-11-15 05:57:02 INFO     TORNADO :: Successfully processed Bosch.S01E10.DVDRip.x264-DEMAND.mkv
2015-11-15 05:57:02 DEBUG    TORNADO :: Deleted file bosch.s01e10.dvdrip.x264-demand.proof.jpg
2015-11-15 05:57:02 DEBUG    TORNADO :: Deleted file Bosch.S01E10.DVDRip.x264-DEMAND.sub
2015-11-15 05:57:02 DEBUG    TORNADO :: Deleted file Bosch.S01E10.DVDRip.x264-DEMAND.idx
2015-11-15 05:57:02 INFO     TORNADO :: Deleted folder /c/media/Downloads/Bosch.S01E10.DVDRip.x264-DEMAND
2015-11-15 05:57:02 INFO     TORNADO :: Successfully processed.
</pre>

Only 192.168.2.75:32400 setup
<pre>
2015-11-15 06:14:29 DEBUG    TORNADO :: Parsed Bosch.S01E01.DVDRip.x264-DEMAND into Bosch - S1E1 [GROUP: DEMAND] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-11-15 06:14:29 DEBUG    TORNADO :: formatting pattern: %SN - %Sx%0E - %EN - %QN -> Bosch - 1x01 - Tis the Season - SD DVD
2015-11-15 06:14:29 DEBUG    TORNADO :: Notification for NMJ scan update not enabled, skipping this notification
2015-11-15 06:14:30 INFO     TORNADO :: PLEX: Updating hosts where TV section paths match the downloaded show: 192.168.2.30:32400
2015-11-15 06:14:30 INFO     TORNADO :: Successfully processed Bosch.S01E01.DVDRip.x264-DEMAND.mkv
2015-11-15 06:14:30 DEBUG    TORNADO :: Deleted file bosch.s01e01.dvdrip.x264-demand.proof.jpg
2015-11-15 06:14:30 DEBUG    TORNADO :: Deleted file Bosch.S01E01.DVDRip.x264-DEMAND.sub
2015-11-15 06:14:30 DEBUG    TORNADO :: Deleted file Bosch.S01E01.DVDRip.x264-DEMAND.idx
2015-11-15 06:14:30 INFO     TORNADO :: Deleted folder /c/media/Downloads/Bosch.S01E01.DVDRip.x264-DEMAND
2015-11-15 06:14:30 INFO     TORNADO :: Successfully processed.
</pre>

With both setup
<pre>
2015-11-15 06:22:00 DEBUG    TORNADO :: Parsed Bosch.S01E02.DVDRip.x264-DEMAND into Bosch - S1E2 [GROUP: DEMAND] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-11-15 06:22:00 DEBUG    TORNADO :: formatting pattern: %SN - %Sx%0E - %EN - %QN -> Bosch - 1x02 - Lost Light - SD DVD
2015-11-15 06:22:00 DEBUG    TORNADO :: Notification for NMJ scan update not enabled, skipping this notification
2015-11-15 06:22:01 ERROR    TORNADO :: Uncaught exception GET /home/postprocess/processEpisode?nzbName=Bosch.S01E02.DVDRip.x264-DEMAND.nzb&failed=0&quiet=1&dir=%2Fc%2F.sabnzbd%2Fdownloads%2Fcomplete%2FBosch.S01E02.DVDRip.x264-DEMAND (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:8088', method='GET', uri='/home/postprocess/processEpisode?nzbName=Bosch.S01E02.DVDRip.x264-DEMAND.nzb&failed=0&quiet=1&dir=%2Fc%2F.sabnzbd%2Fdownloads%2Fcomplete%2FBosch.S01E02.DVDRip.x264-DEMAND', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Cookie': 'sickgear-session="2|1:0|10:1447532516|16:sickgear-session|60:Q2tiUWdLTnNST0d6RmlxdHc2NTU1UFpYYzcrSGEwUGR2QzI5NVhTd2lEZz0=|5b30493e9267cdaa9934b422c262d8db8c0375c3b22cb7109c2eb0f549381220"', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8088', 'Accept': '*/*', 'User-Agent': 'python-requests/2.7.0 CPython/2.7.3 Linux/2.6.37.6.RNx86_64.2.4'})
Traceback (most recent call last):
  File "/c/.sickgear/tornado/web.py", line 1418, in _execute
    result = yield result
  File "/c/.sickgear/tornado/gen.py", line 870, in run
    value = future.result()
  File "/c/.sickgear/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/c/.sickgear/tornado/gen.py", line 215, in wrapper
    result = func(*args, **kwargs)
  File "/c/.sickgear/sickbeard/webserve.py", line 294, in get
    result = method(**kwargss)
  File "/c/.sickgear/sickbeard/webserve.py", line 2009, in processEpisode
    failed=not '0' == failed)
  File "/c/.sickgear/sickbeard/processTV.py", line 585, in processDir
    return ProcessTVShow().process_dir(dir_name, nzb_name, process_method, force, force_replace, failed, type, cleanup)
  File "/c/.sickgear/sickbeard/processTV.py", line 271, in process_dir
    self._process_media(process_path, video_pick, nzb_name, process_method, force, force_replace, use_trash=cleanup)
  File "/c/.sickgear/sickbeard/processTV.py", line 510, in _process_media
    file_success = processor.process()
  File "/c/.sickgear/sickbeard/postProcessor.py", line 1018, in process
    notifiers.plex_notifier.update_library(ep_obj)
  File "/c/.sickgear/sickbeard/notifiers/plex.py", line 250, in update_library
    hosts_try = (hosts_all.copy(), hosts_match.copy())[len(hosts_match)]
IndexError: tuple index out of range
</pre>

**Comment by JackDandy** [comment]
Repeated IPs for both tests, accidental IP data entry for the setting on the second (192.168.2.75) test ?

**Comment by jillmess** [comment]
Yes, same show on both servers.

Sorry, I don't understand your question re the repeated IPs?

**Comment by JackDandy** [comment]
I edited my post inline to hopefully read more clearly, see above

**Comment by jillmess** [comment]
Thanks - I 'thought' I had changed the server setup in SickRage in between the 2 downloads but obviously hadn't.  Have just downloaded another episode - log extract below showing successful processing with server 192.168.75:32400 only.

<pre>
2015-11-15 12:47:34 DEBUG    TORNADO :: Parsed Bosch.S01E10.DVDRip.x264-DEMAND into Bosch - S1E10 [GROUP: DEMAND] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-11-15 12:47:34 DEBUG    TORNADO :: formatting pattern: %SN - %Sx%0E - %EN - %QN -> Bosch - 1x10 - Us and Them - SD DVD
2015-11-15 12:47:34 DEBUG    TORNADO :: Notification for NMJ scan update not enabled, skipping this notification
2015-11-15 12:47:34 INFO     TORNADO :: PLEX: Updating hosts where TV section paths match the downloaded show: 192.168.2.75:32400
2015-11-15 12:47:34 INFO     TORNADO :: Successfully processed Bosch.S01E10.DVDRip.x264-DEMAND.mkv
2015-11-15 12:47:34 DEBUG    TORNADO :: Deleted file bosch.s01e10.dvdrip.x264-demand.proof.jpg
2015-11-15 12:47:34 DEBUG    TORNADO :: Deleted file Bosch.S01E10.DVDRip.x264-DEMAND.sub
2015-11-15 12:47:34 DEBUG    TORNADO :: Deleted file Bosch.S01E10.DVDRip.x264-DEMAND.idx
2015-11-15 12:47:34 INFO     TORNADO :: Deleted folder /c/media/Downloads/Bosch.S01E10.DVDRip.x264-DEMAND
2015-11-15 12:47:34 INFO     TORNADO :: Successfully processed.
</pre>

**Comment by jillmess** [comment]
Manual post processing has the same error.  Log extract below.

<pre>
2015-11-15 13:07:14 DEBUG    TORNADO :: Parsed Bosch.S01E05.DVDRip.x264-DEMAND into Bosch - S1E5 [GROUP: DEMAND] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-11-15 13:07:14 DEBUG    TORNADO :: formatting pattern: %SN - %Sx%0E - %EN - %QN -> Bosch - 1x05 - Mama's Boy - SD DVD
2015-11-15 13:07:14 DEBUG    TORNADO :: Notification for NMJ scan update not enabled, skipping this notification
2015-11-15 13:07:14 ERROR    TORNADO :: Uncaught exception POST /home/postprocess/processEpisode (192.168.2.50)
HTTPServerRequest(protocol='http', host='192.168.2.75:8088', method='POST', uri='/home/postprocess/processEpisode', version='HTTP/1.1', remote_ip='192.168.2.50', headers={'Origin': 'http://192.168.2.75:8088', 'Content-Length': '120', 'Accept-Language': 'en-US,en;q=0.8', 'Accept-Encoding': 'gzip, deflate', 'Host': '192.168.2.75:8088', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Upgrade-Insecure-Requests': '1', 'Dnt': '1', 'Connection': 'keep-alive', 'Referer': 'http://192.168.2.75:8088/home/postprocess/', 'Cache-Control': 'max-age=0', 'Cookie': '__utma=224192987.1255018411.1395369389.1398336930.1398392846.13; _ga=GA1.1.1255018411.1395369389; sdmenu_my_menu=0000000001', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36', 'Content-Type': 'application/x-www-form-urlencoded'})
Traceback (most recent call last):
  File "/c/.sickgear/tornado/web.py", line 1418, in _execute
    result = yield result
  File "/c/.sickgear/tornado/gen.py", line 870, in run
    value = future.result()
  File "/c/.sickgear/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/c/.sickgear/tornado/gen.py", line 215, in wrapper
    result = func(*args, **kwargs)
  File "/c/.sickgear/sickbeard/webserve.py", line 294, in get
    result = method(**kwargss)
  File "/c/.sickgear/sickbeard/webserve.py", line 2009, in processEpisode
    failed=not '0' == failed)
  File "/c/.sickgear/sickbeard/processTV.py", line 585, in processDir
    return ProcessTVShow().process_dir(dir_name, nzb_name, process_method, force, force_replace, failed, type, cleanup)
  File "/c/.sickgear/sickbeard/processTV.py", line 230, in process_dir
    self._process_media(path, video_pick, nzb_name, process_method, force, force_replace, use_trash=cleanup)
  File "/c/.sickgear/sickbeard/processTV.py", line 510, in _process_media
    file_success = processor.process()
  File "/c/.sickgear/sickbeard/postProcessor.py", line 1018, in process
    notifiers.plex_notifier.update_library(ep_obj)
  File "/c/.sickgear/sickbeard/notifiers/plex.py", line 250, in update_library
    hosts_try = (hosts_all.copy(), hosts_match.copy())[len(hosts_match)]
IndexError: tuple index out of range
</pre>

**Comment by adam111316** [comment]
Try changing the line len(hosts_match) to bool(hosts_match). While SG is shut down ofc.

**Comment by JackDandy** [comment]
ummm, this isn't sickrage.

**Comment by JackDandy** [comment]
bool is a mask, it may be correct, but i have to check why that value is actually out of range.

**Comment by jillmess** [comment]
@JackDandy  - sorry, mistype - I changed to SickGear (from SickRage) about 6 months ago.

I assume you mean to change line 250 in plex.py?  Now as below but same error (I think).
<pre>
 hosts_try = (hosts_all.copy(), hosts_match.copy())[bool(hosts_match)]
</pre>
<pre>
2015-11-15 13:19:26 DEBUG    TORNADO :: Parsed Bosch.S01E05.DVDRip.x264-DEMAND into Bosch - S1E5 [GROUP: DEMAND] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-11-15 13:19:26 DEBUG    TORNADO :: formatting pattern: %SN - %Sx%0E - %EN - %QN -> Bosch - 1x05 - Mama's Boy - SD DVD
2015-11-15 13:19:26 DEBUG    TORNADO :: Notification for NMJ scan update not enabled, skipping this notification
2015-11-15 13:19:26 ERROR    TORNADO :: Uncaught exception POST /home/postprocess/processEpisode (192.168.2.1)
HTTPServerRequest(protocol='http', host='jillmess.dyndns.tv:8088', method='POST', uri='/home/postprocess/processEpisode', version='HTTP/1.1', remote_ip='192.168.2.1', headers={'Origin': 'http://jillmess.dyndns.tv:8088', 'Content-Length': '120', 'Accept-Language': 'en-US,en;q=0.8', 'Accept-Encoding': 'gzip, deflate', 'Host': 'jillmess.dyndns.tv:8088', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Upgrade-Insecure-Requests': '1', 'Dnt': '1', 'Connection': 'keep-alive', 'Referer': 'http://jillmess.dyndns.tv:8088/home/postprocess/', 'Cache-Control': 'max-age=0', 'Cookie': 'plushContainerWidth=100%25; plushNoTopMenu=0; _ga=GA1.3.675945602.1416785602', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36', 'Content-Type': 'application/x-www-form-urlencoded'})
Traceback (most recent call last):
  File "/c/.sickgear/tornado/web.py", line 1418, in _execute
    result = yield result
  File "/c/.sickgear/tornado/gen.py", line 870, in run
    value = future.result()
  File "/c/.sickgear/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/c/.sickgear/tornado/gen.py", line 215, in wrapper
    result = func(*args, **kwargs)
  File "/c/.sickgear/sickbeard/webserve.py", line 294, in get
    result = method(**kwargss)
  File "/c/.sickgear/sickbeard/webserve.py", line 2009, in processEpisode
    failed=not '0' == failed)
  File "/c/.sickgear/sickbeard/processTV.py", line 585, in processDir
    return ProcessTVShow().process_dir(dir_name, nzb_name, process_method, force, force_replace, failed, type, cleanup)
  File "/c/.sickgear/sickbeard/processTV.py", line 230, in process_dir
    self._process_media(path, video_pick, nzb_name, process_method, force, force_replace, use_trash=cleanup)
  File "/c/.sickgear/sickbeard/processTV.py", line 510, in _process_media
    file_success = processor.process()
  File "/c/.sickgear/sickbeard/postProcessor.py", line 1018, in process
    notifiers.plex_notifier.update_library(ep_obj)
  File "/c/.sickgear/sickbeard/notifiers/plex.py", line 250, in update_library
    hosts_try = (hosts_all.copy(), hosts_match.copy())[bool(hosts_match)]
IndexError: tuple index out of range
</pre>

**Comment by JackDandy** [comment]
as i suspected. I will take a investigate.

**Comment by JackDandy** [comment]
Hi @jillmess

Can you first stop SG, make the following change to line #250 of plex.py, save, then start SG... 
[pre]hosts_try = (hosts_all.copy(), hosts_match.copy())[any(hosts_match)][/pre]
(the change is **"len"** to **"any"**)

And then let us know how that goes for you.

**Comment by jillmess** [comment]
Looks good - no errors reported and no left over undeleted folders now.
The following post-processing was happening at the same time as a backlog search so I cut all the "BACKLOG" lines.  Hopefully I left everything important.  
<pre>
2015-11-21 09:14:19 DEBUG    TORNADO :: 299972: Saving episode details to database
2015-11-21 09:14:19 DEBUG    TORNADO :: STATUS IS 104
2015-11-21 09:14:19 DB       TORNADO :: sickbeard.db: UPDATE [tv_episodes] SET status = ?, release_name = ?, release_group = ?, name = ?, airdate = ?, hastbn = ?, location = ?, indexer = ?, version = ?, hasnfo = ?, absolute_number = ?, file_size = ?, subtitles_searchcount = ?, indexerid = ?, is_proper = ?, subtitles_lastsearch = ?, subtitles = ?, description = ? WHERE season = ? AND showid = ? AND episode = ? with args [104, u'The.Art.of.More.S01E02.HDTV.x264-2HD', u'2HD', u'Whodunnit?', 735921, False, u'/c/media/Videos/TV_A-K/Art of More/S01E02 - Whodunnit.mp4', 1, -1, False, 0, 276000186L, 1, 5408701, False, '2015-11-21 09:14:19', '', '', 1, 299972, 2]
2015-11-21 09:14:19 DEBUG    TORNADO :: 299972: No subtitles downloaded for episode 1x2
2015-11-21 09:14:19 DB       TORNADO :: sickbeard.db: SELECT episode_id FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [299972, 1, 2]
2015-11-21 09:14:19 DEBUG    TORNADO :: Transaction with 1 queries executed
2015-11-21 09:14:19 DB       TORNADO :: sickbeard.db: INSERT INTO history (action, date, showid, season, episode, quality, resource, provider, version) VALUES (?,?,?,?,?,?,?,?,?) with args [104, '20151121091419', 299972, 1, 2, 1, u'/c/media/Downloads/The.Art.of.More.S01E02.HDTV.x264-2HD/the.art.of.more.s01e02.hdtv.x264-2hd.mp4', u'2HD', -1]
2015-11-21 09:14:19 DEBUG    TORNADO :: Using NORMAL regexs
2015-11-21 09:14:19 DEBUG    TORNADO :: Parsed The.Art.of.More.S01E02.HDTV.x264-2HD into The Art of More - S1E2 [GROUP: 2HD] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-11-21 09:14:19 DEBUG    TORNADO :: formatting pattern: %SN - %Sx%0E - %EN - %QN -> The Art of More - 1x02 - Whodunnit - SD TV
2015-11-21 09:14:19 DEBUG    TORNADO :: Notification for NMJ scan update not enabled, skipping this notification
2015-11-21 09:14:19 INFO     TORNADO :: PLEX: Updating hosts where TV section paths match the downloaded show: 192.168.2.75:32400, 192.168.2.30:32400
2015-11-21 09:14:19 INFO     TORNADO :: Successfully processed the.art.of.more.s01e02.hdtv.x264-2hd.mp4
2015-11-21 09:14:19 INFO     TORNADO :: Deleted folder /c/media/Downloads/The.Art.of.More.S01E02.HDTV.x264-2HD
2015-11-21 09:14:19 INFO     TORNADO :: Successfully processed.
</pre>

**Comment by JackDandy** [comment]
That's great, thanks for the quick feedback.
