### ISSUE TITLE
Add Existing Show > "TV info source" is empty

### ISSUE THREAD

**Issue by Bm4n** [SickGear/SickGear#625]
When an existing show is added the "TV info source" box is blank and prevented from continuing by an error in the browser.

BRANCH: master / COMMIT: 2505cb469e0b5183f8b8d81887fc87474b43f33c

**Comment by JackDandy** [comment]
[How to report issues](https://github.com/SickGear/SickGear/wiki/%5BHow-to%5D-Report-Issues)

**Comment by Bm4n** [comment]
This is what I see in both versions running on Synology NAS (DS114) from any PC/Browser. Before updating the master version was not the problem, with the development version I've always had that problem.

- BRANCH: master / COMMIT: 2505cb469e0b5183f8b8d81887fc87474b43f33c
- BRANCH: develop / COMMIT: e6fa3e360608d6d3bb47c2ebcb41f87751a63eae

Screenshots:
http://cl.ly/eYvY
http://cl.ly/eYp8

Browser screen:
<pre>Error

invalid literal for int() with base 10: 'null'
Traceback

Traceback (most recent call last):
File "/volume1/@appstore/sickbeard-custom/var/SickBeard/tornado/web.py", line 1417, in _execute result = yield result
File "/volume1/@appstore/sickbeard-custom/var/SickBeard/tornado/gen.py", line 920, in run value = future.result()
File "/volume1/@appstore/sickbeard-custom/var/SickBeard/tornado/concurrent.py", line 223, in result raise_exc_info(self._exc_info)
File "/volume1/@appstore/sickbeard-custom/var/SickBeard/tornado/gen.py", line 235, in wrapper result = func(*args, **kwargs)
File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 307, in get result = method(**kwargss)
File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 2959, in addExistingShows return self.newShow(dirs_only[0], dirs_only[1:])
File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 2353, in newShow t.provided_indexer = int(indexer or sickbeard.INDEXER_DEFAULT)
ValueError: invalid literal for int() with base 10: 'null'
Request Info

body:
files: {}
protocol: http
connection:
body_arguments: {}
uri: /home/addShows/addExistingShows?promptForSettings=off&shows_to_add=null%7C%2Fvolume1%2Fvideo%2FSeries%2FAttack%20on%20Titan
query_arguments: {'promptForSettings': ['off'], 'shows_to_add': ['null|/volume1/video/Series/Attack on Titan']}
_start_time: 1452630820.29
headers: {'Accept-Language': 'es-ES,es;q=0.8,en-US;q=0.5,en;q=0.3', 'Accept-Encoding': 'gzip, deflate', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:43.0) Gecko/20100101 Firefox/43.0', 'Host': '192.168.1.140:8083', 'Referer': 'http://192.168.1.140:8083/home/addShows/existingShows/', 'Cookie': 'stay_login=0; sickgear-session="2|1:0|10:1452630693|16:sickgear-session|60:Y2VidmdFdm5UY1dKNlRDa0ZYdWpZc0JucUNTdTYwRGhrS1JaNXJKWVpwRT0=|8b38e54a89758e60d491c094cb1b3c50c5c5ff2caac6c9a9a3af8a5be947629f"'}
host: 192.168.1.140:8083
version: HTTP/1.1
arguments: {'promptForSettings': 'off', 'shows_to_add': 'null|/volume1/video/Series/Attack on Titan'}
_finish_time: None
query: promptForSettings=off&shows_to_add=null%7C%2Fvolume1%2Fvideo%2FSeries%2FAttack%20on%20Titan
path: /home/addShows/addExistingShows
_cookies: Set-Cookie: sickgear-session="2|1:0|10:1452630693|16:sickgear-session|60:Y2VidmdFdm5UY1dKNlRDa0ZYdWpZc0JucUNTdTYwRGhrS1JaNXJKWVpwRT0=|8b38e54a89758e60d491c094cb1b3c50c5c5ff2caac6c9a9a3af8a5be947629f" Set-Cookie: stay_login=0
method: GET
remote_ip: 192.168.1.5</pre>

The log:
<pre>2016-01-12 21:43:30 DB       TORNADO :: sickbeard.db: SELECT (SELECT COUNT(*) FROM tv_episodes WHERE season > 0 AND episode > 0 AND airdate > 1 AND status IN (2,3276802,202,402,102,802,12802,25602,1602,3202,6402,9,3276809,209,409,109,809,12809,25609,1609,3209,6409)) AS ep_snatched, (SELECT COUNT(*) FROM tv_episodes WHERE season > 0 AND episode > 0 AND airdate > 1 AND status IN (4,3276804,204,404,104,804,12804,25604,1604,3204,6404,6)) AS ep_downloaded, (SELECT COUNT(*) FROM tv_episodes WHERE season > 0 AND episode > 0 AND airdate > 1  AND ((airdate <= 735975 AND (status = 5 OR status = 3))  OR (status IN (2,3276802,202,402,102,802,12802,25602,1602,3202,6402,9,3276809,209,409,109,809,12809,25609,1609,3209,6409)) OR (status IN (4,3276804,204,404,104,804,12804,25604,1604,3204,6404,6)))) AS ep_total FROM tv_episodes tv_eps LIMIT 1
AAValueError: invalid literal for int() with base 10: 'null'
AA    t.provided_indexer = int(indexer or sickbeard.INDEXER_DEFAULT)
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 2353, in newShow
AA    return self.newShow(dirs_only[0], dirs_only[1:])
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 2959, in addExistingShows
AA    result = method(**kwargss)
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 307, in get
AA    result = func(*args, **kwargs)
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/tornado/gen.py", line 235, in wrapper
AA    raise_exc_info(self._exc_info)
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/tornado/concurrent.py", line 223, in result
AA    value = future.result()
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/tornado/gen.py", line 920, in run
AA    result = yield result
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/tornado/web.py", line 1417, in _execute
AATraceback (most recent call last):
AAHTTPServerRequest(protocol='http', host='192.168.1.140:8083', method='GET', uri='/home/addShows/addExistingShows?promptForSettings=off&shows_to_add=null%7C%2Fvolume1%2Fvideo%2FSeries%2FAttack%20on%20Titan', version='HTTP/1.1', remote_ip='192.168.1.5', headers={'Accept-Language': 'es-es', 'Accept-Encoding': 'gzip, deflate', 'Host': '192.168.1.140:8083', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9', 'Dnt': '1', 'Connection': 'keep-alive', 'Cookie': '_ga=GA1.1.315230301.1450826612; id=Tx1oi3wpPU5Ks13B0LRN000554; sickgear-session="2|1:0|10:1452630661|16:sickgear-session|60:Y2VidmdFdm5UY1dKNlRDa0ZYdWpZc0JucUNTdTYwRGhrS1JaNXJKWVpwRT0=|04256bf0b7a7926ef513623a442a9fa1e102b85739f8605beef8cfdea2457c86"; stay_login=1', 'Referer': 'http://192.168.1.140:8083/home/addShows/existingShows/'})
2016-01-12 21:43:23 ERROR    TORNADO :: Uncaught exception GET /home/addShows/addExistingShows?promptForSettings=off&shows_to_add=null%7C%2Fvolume1%2Fvideo%2FSeries%2FAttack%20on%20Titan (192.168.1.5)
2016-01-12 21:43:17 DEBUG    TORNADO :: Loading show info from metadata file in /volume1/video/Series/House of Cards (US)
2016-01-12 21:43:17 DB       TORNADO :: sickbeard.db: SELECT * FROM tv_shows WHERE location = ? with args [u'/volume1/video/Series/House of Cards (US)']
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Scream Queens (2015)/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Scream Queens (2015)/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Scream Queens (2015)/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DB       TORNADO :: sickbeard.db: SELECT * FROM tv_shows WHERE location = ? with args [u'/volume1/video/Series/Scream Queens (2015)']
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Fresh Off the Boat/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Fresh Off the Boat/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Fresh Off the Boat/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DB       TORNADO :: sickbeard.db: SELECT * FROM tv_shows WHERE location = ? with args [u'/volume1/video/Series/Fresh Off the Boat']
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Better Call Saul/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Better Call Saul/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Better Call Saul/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DB       TORNADO :: sickbeard.db: SELECT * FROM tv_shows WHERE location = ? with args [u'/volume1/video/Series/Better Call Saul']
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Homeland/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Homeland/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Homeland/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DB       TORNADO :: sickbeard.db: SELECT * FROM tv_shows WHERE location = ? with args [u'/volume1/video/Series/Homeland']
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/How to Get Away With Murder/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/How to Get Away With Murder/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/How to Get Away With Murder/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DB       TORNADO :: sickbeard.db: SELECT * FROM tv_shows WHERE location = ? with args [u'/volume1/video/Series/How to Get Away With Murder']
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Silicon Valley/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Silicon Valley/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Silicon Valley/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DB       TORNADO :: sickbeard.db: SELECT * FROM tv_shows WHERE location = ? with args [u'/volume1/video/Series/Silicon Valley']
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/True Detective/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/True Detective/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/True Detective/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DB       TORNADO :: sickbeard.db: SELECT * FROM tv_shows WHERE location = ? with args [u'/volume1/video/Series/True Detective']
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Game of Thrones/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Game of Thrones/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Game of Thrones/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DB       TORNADO :: sickbeard.db: SELECT * FROM tv_shows WHERE location = ? with args [u'/volume1/video/Series/Game of Thrones']
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Psycho-Pass/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Psycho-Pass/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Psycho-Pass/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DB       TORNADO :: sickbeard.db: SELECT * FROM tv_shows WHERE location = ? with args [u'/volume1/video/Series/Psycho-Pass']
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Space Dandy/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Space Dandy/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Space Dandy/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DB       TORNADO :: sickbeard.db: SELECT * FROM tv_shows WHERE location = ? with args [u'/volume1/video/Series/Space Dandy']
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Durarara!/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Durarara!/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Durarara!/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DB       TORNADO :: sickbeard.db: SELECT * FROM tv_shows WHERE location = ? with args [u'/volume1/video/Series/Durarara!']
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Sidonia no Kishi/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Sidonia no Kishi/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Sidonia no Kishi/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DB       TORNADO :: sickbeard.db: SELECT * FROM tv_shows WHERE location = ? with args [u'/volume1/video/Series/Sidonia no Kishi']
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Attack on Titan/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Attack on Titan/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Attack on Titan/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DB       TORNADO :: sickbeard.db: SELECT * FROM tv_shows WHERE location = ? with args [u'/volume1/video/Series/Attack on Titan']
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Elementary/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Elementary/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Elementary/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DB       TORNADO :: sickbeard.db: SELECT * FROM tv_shows WHERE location = ? with args [u'/volume1/video/Series/Elementary']
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Gotham/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Gotham/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Gotham/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DB       TORNADO :: sickbeard.db: SELECT * FROM tv_shows WHERE location = ? with args [u'/volume1/video/Series/Gotham']
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/@eaDir/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/@eaDir/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/@eaDir/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DB       TORNADO :: sickbeard.db: SELECT * FROM tv_shows WHERE location = ? with args [u'/volume1/video/Series/@eaDir']
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Outlander/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Outlander/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Outlander/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DB       TORNADO :: sickbeard.db: SELECT * FROM tv_shows WHERE location = ? with args [u'/volume1/video/Series/Outlander']
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Tokyo Magnitude/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Tokyo Magnitude/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Tokyo Magnitude/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DB       TORNADO :: sickbeard.db: SELECT * FROM tv_shows WHERE location = ? with args [u'/volume1/video/Series/Tokyo Magnitude']
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Person of Interest/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Person of Interest/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Person of Interest/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DB       TORNADO :: sickbeard.db: SELECT * FROM tv_shows WHERE location = ? with args [u'/volume1/video/Series/Person of Interest']
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Modern Family/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Modern Family/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Modern Family/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DB       TORNADO :: sickbeard.db: SELECT * FROM tv_shows WHERE location = ? with args [u'/volume1/video/Series/Modern Family']
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/One-Punch Man/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/One-Punch Man/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/One-Punch Man/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DB       TORNADO :: sickbeard.db: SELECT * FROM tv_shows WHERE location = ? with args [u'/volume1/video/Series/One-Punch Man']
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Big Bang Theory/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Big Bang Theory/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Big Bang Theory/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DB       TORNADO :: sickbeard.db: SELECT * FROM tv_shows WHERE location = ? with args [u'/volume1/video/Series/Big Bang Theory']
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Fargo/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Fargo/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Fargo/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DB       TORNADO :: sickbeard.db: SELECT * FROM tv_shows WHERE location = ? with args [u'/volume1/video/Series/Fargo']
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Quantico/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Quantico/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Quantico/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DB       TORNADO :: sickbeard.db: SELECT * FROM tv_shows WHERE location = ? with args [u'/volume1/video/Series/Quantico']
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Mr. Robot/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Mr. Robot/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DEBUG    TORNADO :: Can't load the metadata file from u'/volume1/video/Series/Mr. Robot/tvshow.nfo', it doesn't exist
2016-01-12 21:43:17 DB       TORNADO :: sickbeard.db: SELECT * FROM tv_shows WHERE location = ? with args [u'/volume1/video/Series/Mr. Robot']
2016-01-12 21:43:16 DB       TORNADO :: sickbeard.db: SELECT (SELECT COUNT(*) FROM tv_episodes WHERE season > 0 AND episode > 0 AND airdate > 1 AND status IN (2,3276802,202,402,102,802,12802,25602,1602,3202,6402,9,3276809,209,409,109,809,12809,25609,1609,3209,6409)) AS ep_snatched, (SELECT COUNT(*) FROM tv_episodes WHERE season > 0 AND episode > 0 AND airdate > 1 AND status IN (4,3276804,204,404,104,804,12804,25604,1604,3204,6404,6)) AS ep_downloaded, (SELECT COUNT(*) FROM tv_episodes WHERE season > 0 AND episode > 0 AND airdate > 1  AND ((airdate <= 735975 AND (status = 5 OR status = 3))  OR (status IN (2,3276802,202,402,102,802,12802,25602,1602,3202,6402,9,3276809,209,409,109,809,12809,25609,1609,3209,6409)) OR (status IN (4,3276804,204,404,104,804,12804,25604,1604,3204,6404,6)))) AS ep_total FROM tv_episodes tv_eps LIMIT 1
2016-01-12 21:43:11 DB       TORNADO :: sickbeard.db: SELECT (SELECT COUNT(*) FROM tv_episodes WHERE season > 0 AND episode > 0 AND airdate > 1 AND status IN (2,3276802,202,402,102,802,12802,25602,1602,3202,6402,9,3276809,209,409,109,809,12809,25609,1609,3209,6409)) AS ep_snatched, (SELECT COUNT(*) FROM tv_episodes WHERE season > 0 AND episode > 0 AND airdate > 1 AND status IN (4,3276804,204,404,104,804,12804,25604,1604,3204,6404,6)) AS ep_downloaded, (SELECT COUNT(*) FROM tv_episodes WHERE season > 0 AND episode > 0 AND airdate > 1  AND ((airdate <= 735975 AND (status = 5 OR status = 3))  OR (status IN (2,3276802,202,402,102,802,12802,25602,1602,3202,6402,9,3276809,209,409,109,809,12809,25609,1609,3209,6409)) OR (status IN (4,3276804,204,404,104,804,12804,25604,1604,3204,6404,6)))) AS ep_total FROM tv_episodes tv_eps LIMIT 1
2016-01-12 21:43:08 DB       TORNADO :: sickbeard.db: SELECT (SELECT COUNT(*) FROM tv_episodes WHERE season > 0 AND episode > 0 AND airdate > 1 AND status IN (2,3276802,202,402,102,802,12802,25602,1602,3202,6402,9,3276809,209,409,109,809,12809,25609,1609,3209,6409)) AS ep_snatched, (SELECT COUNT(*) FROM tv_episodes WHERE season > 0 AND episode > 0 AND airdate > 1 AND status IN (4,3276804,204,404,104,804,12804,25604,1604,3204,6404,6)) AS ep_downloaded, (SELECT COUNT(*) FROM tv_episodes WHERE season > 0 AND episode > 0 AND airdate > 1  AND ((airdate <= 735975 AND (status = 5 OR status = 3))  OR (status IN (2,3276802,202,402,102,802,12802,25602,1602,3202,6402,9,3276809,209,409,109,809,12809,25609,1609,3209,6409)) OR (status IN (4,3276804,204,404,104,804,12804,25604,1604,3204,6404,6)))) AS ep_total FROM tv_episodes tv_eps LIMIT 1
2016-01-12 21:43:08 DB       TORNADO :: sickbeard.db: SELECT showid, (SELECT COUNT(*) FROM tv_episodes WHERE showid=tv_eps.showid AND season > 0 AND episode > 0 AND airdate > 1 AND status IN (2,3276802,202,402,102,802,12802,25602,1602,3202,6402,9,3276809,209,409,109,809,12809,25609,1609,3209,6409)) AS ep_snatched, (SELECT COUNT(*) FROM tv_episodes WHERE showid=tv_eps.showid AND season > 0 AND episode > 0 AND airdate > 1 AND status IN (4,3276804,204,404,104,804,12804,25604,1604,3204,6404,6)) AS ep_downloaded, (SELECT COUNT(*) FROM tv_episodes WHERE showid=tv_eps.showid AND season > 0 AND episode > 0 AND airdate > 1 AND ((airdate <= 735975 AND (status IN (5, 3, 11))) OR (status IN (2,3276802,202,402,102,802,12802,25602,1602,3202,6402,9,3276809,209,409,109,809,12809,25609,1609,3209,6409)) OR (status IN (4,3276804,204,404,104,804,12804,25604,1604,3204,6404,6)))) AS ep_total, (SELECT airdate FROM tv_episodes WHERE showid=tv_eps.showid AND airdate >= 735975 AND (status = 1  OR status = 3) ORDER BY airdate ASC LIMIT 1) AS ep_airs_next  FROM tv_episodes tv_eps GROUP BY showid
2016-01-12 21:42:51 DB       TORNADO :: sickbeard.db: SELECT (SELECT COUNT(*) FROM tv_episodes WHERE season > 0 AND episode > 0 AND airdate > 1 AND status IN (2,3276802,202,402,102,802,12802,25602,1602,3202,6402,9,3276809,209,409,109,809,12809,25609,1609,3209,6409)) AS ep_snatched, (SELECT COUNT(*) FROM tv_episodes WHERE season > 0 AND episode > 0 AND airdate > 1 AND status IN (4,3276804,204,404,104,804,12804,25604,1604,3204,6404,6)) AS ep_downloaded, (SELECT COUNT(*) FROM tv_episodes WHERE season > 0 AND episode > 0 AND airdate > 1  AND ((airdate <= 735975 AND (status = 5 OR status = 3))  OR (status IN (2,3276802,202,402,102,802,12802,25602,1602,3202,6402,9,3276809,209,409,109,809,12809,25609,1609,3209,6409)) OR (status IN (4,3276804,204,404,104,804,12804,25604,1604,3204,6404,6)))) AS ep_total FROM tv_episodes tv_eps LIMIT 1
2016-01-12 21:42:41 DB       TORNADO :: sickbeard.db: SELECT (SELECT COUNT(*) FROM tv_episodes WHERE season > 0 AND episode > 0 AND airdate > 1 AND status IN (2,3276802,202,402,102,802,12802,25602,1602,3202,6402,9,3276809,209,409,109,809,12809,25609,1609,3209,6409)) AS ep_snatched, (SELECT COUNT(*) FROM tv_episodes WHERE season > 0 AND episode > 0 AND airdate > 1 AND status IN (4,3276804,204,404,104,804,12804,25604,1604,3204,6404,6)) AS ep_downloaded, (SELECT COUNT(*) FROM tv_episodes WHERE season > 0 AND episode > 0 AND airdate > 1  AND ((airdate <= 735975 AND (status = 5 OR status = 3))  OR (status IN (2,3276802,202,402,102,802,12802,25602,1602,3202,6402,9,3276809,209,409,109,809,12809,25609,1609,3209,6409)) OR (status IN (4,3276804,204,404,104,804,12804,25604,1604,3204,6404,6)))) AS ep_total FROM tv_episodes tv_eps LIMIT 1
2016-01-12 21:38:40 DB       TORNADO :: sickbeard.db: SELECT (SELECT COUNT(*) FROM tv_episodes WHERE season > 0 AND episode > 0 AND airdate > 1 AND status IN (2,3276802,202,402,102,802,12802,25602,1602,3202,6402,9,3276809,209,409,109,809,12809,25609,1609,3209,6409)) AS ep_snatched, (SELECT COUNT(*) FROM tv_episodes WHERE season > 0 AND episode > 0 AND airdate > 1 AND status IN (4,3276804,204,404,104,804,12804,25604,1604,3204,6404,6)) AS ep_downloaded, (SELECT COUNT(*) FROM tv_episodes WHERE season > 0 AND episode > 0 AND airdate > 1  AND ((airdate <= 735975 AND (status = 5 OR status = 3))  OR (status IN (2,3276802,202,402,102,802,12802,25602,1602,3202,6402,9,3276809,209,409,109,809,12809,25609,1609,3209,6409)) OR (status IN (4,3276804,204,404,104,804,12804,25604,1604,3204,6404,6)))) AS ep_total FROM tv_episodes tv_eps LIMIT 1
2016-01-12 21:38:38 WARNING  POSTPROCESSER :: Failed! Did not process any files.</pre>

If you need additional information, just say so.
Thank you.

**Comment by JackDandy** [comment]
Hiya, 

This looks like a db issue, can you come to IRC so that I can help to you personally.

**Comment by JackDandy** [comment]
Issue fixed on master, [readme](https://github.com/SickGear/SickGear/blob/master/CHANGES.md)
