### ISSUE TITLE
Client Auth fail + Search Settings error

### ISSUE THREAD

**Issue by Th3MadHatter** [SickGear/SickGear#628]
Branch latest dev and latest master

I randomly got client authentication fails today (or even yesterday, i'm not sure) so I went to my "Search settings" to check out whats wrong but it gave me the following error page:

```

Error

'NoneType' object has no attribute 'strip'
Traceback

Traceback (most recent call last):
File "D:\SickGear\tornado\web.py", line 1417, in _execute result = yield result
File "D:\SickGear\tornado\gen.py", line 920, in run value = future.result()
File "D:\SickGear\tornado\concurrent.py", line 223, in result raise_exc_info(self._exc_info)
File "D:\SickGear\tornado\gen.py", line 235, in wrapper result = func(*args, **kwargs)
File "D:\SickGear\sickbeard\webserve.py", line 307, in get result = method(**kwargss)
File "D:\SickGear\sickbeard\webserve.py", line 4069, in index for show in sickbeard.showList if show.rls_ignore_words.strip()]
AttributeError: 'NoneType' object has no attribute 'strip'
Request Info

body:
files: {}
protocol: http
connection:
body_arguments: {}
uri: /config/search/
query_arguments: {}
_start_time: 1452915619.7
headers: {'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0', 'Dnt': '1', 'Host': 'localhost:43728', 'Referer': 'http://localhost:43728/home/showlistView/'}
host: localhost:43728
version: HTTP/1.1
arguments: {}
_finish_time: None
query:
path: /config/search/
method: GET
remote_ip: 127.0.0.1
```

I then tried to switch to the master branch because I've had it before in dev and switching, tweaking and moving back fixed it back then but now I get the exact same error page on the master branch.

All searches found trying to authenticate with my client give me an Auth faied.

**Comment by JackDandy** [comment]
Fixed.
