### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by jillmess** [SickGear/SickGear#630]
Version:                   BRANCH: master / COMMIT: ab457c78c0605fc4f6038c2e3fa059481f5a1ca3
Python Version:	2.7.10 (default, Aug 17 2015, 22:55:51) [GCC 4.3.2]

Getting the following error when trying to install the latest update:
<pre>
2016-01-19 08:30:56 DEBUG    TORNADO :: cur_commit = ab457c78c0605fc4f6038c2e3fa059481f5a1ca3, newest_commit = 87b915e450f5bb2a5e384599248a6d2414688425, num_commits_behind = 2
2016-01-19 08:30:56 INFO     TORNADO :: Clearing out update folder /usr/share/sickgear/sg-update before extracting
2016-01-19 08:30:56 INFO     TORNADO :: Creating update folder /usr/share/sickgear/sg-update before extracting
2016-01-19 08:30:56 INFO     TORNADO :: Downloading update from 'http://github.com/SickGear/SickGear/tarball/master'
2016-01-19 08:31:18 INFO     TORNADO :: Extracting file /usr/share/sickgear/sg-update/sg-update.tar
2016-01-19 08:31:19 ERROR    TORNADO :: Error while trying to update: ascii : /usr/share/sickgear/sg-update/SickGear-SickGear-87b915e/gui/slick/images/network/×§×©×ª.png : error 81 : error 84 : ordinal not in range(128)
2016-01-19 08:31:19 DEBUG    TORNADO :: Traceback: Traceback (most recent call last):
  File "/c/.sickgear/sickbeard/version_checker.py", line 583, in update
    tar.extractall(sg_update_dir)
  File "/usr/lib/python2.7/tarfile.py", line 2072, in extractall
    self.extract(tarinfo, path)
  File "/usr/lib/python2.7/tarfile.py", line 2109, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "/usr/lib/python2.7/tarfile.py", line 2185, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/lib/python2.7/tarfile.py", line 2225, in makefile
    with bltn_open(targetpath, "wb") as target:
UnicodeEncodeError: 'ascii' codec can't encode characters in position 81-83: ordinal not in range(128)
</pre>

**Comment by JackDandy** [comment]
Your OS is not set up correctly to use unicode characters in file names and when tar tried to extract one it fails, therefore you need to consult how to set up your locale to correctly accept utf-8.
