### ISSUE TITLE
PiSexy is Broken

### ISSUE THREAD

**Issue by rbhamilton** [SickGear/SickGear#668]
2016-03-19 07:38:32 BACKLOG-295684 :: [PiSexy] :: Failed to parse. Traceback: Traceback (most recent call last):
  File "C:\SickGear\sickbeard\providers\pisexy.py", line 80, in _search_provider
    rc['seeders'].findall(seeders)[0], rc['leechers'].findall(leechers)[0]]]
IndexError: list index out of range

2016-03-19 07:38:25 BACKLOG-295684 :: [PiSexy] :: Failed to parse. Traceback: Traceback (most recent call last):
  File "C:\SickGear\sickbeard\providers\pisexy.py", line 80, in _search_provider
    rc['seeders'].findall(seeders)[0], rc['leechers'].findall(leechers)[0]]]
IndexError: list index out of range

2016-03-19 07:38:24 BACKLOG-295684 :: [PiSexy] :: Failed to parse. Traceback: Traceback (most recent call last):
  File "C:\SickGear\sickbeard\providers\pisexy.py", line 80, in _search_provider
    rc['seeders'].findall(seeders)[0], rc['leechers'].findall(leechers)[0]]]
IndexError: list index out of range

**Comment by JackDandy** [comment]
Hello @rbhamilton 

False alarm, it is not broken.

The page simply failed to parse at that time. I think the because there was no valid character parsed for the see/pee,  Most importantly, that data will have appeared some time later and then there will have been no more issues reported in the log.

I'll add something so that this doesn't alarm anyone else, and will change the misleading title of this thread.

Thanks.
