### ISSUE TITLE
Index out of range error on General Config page.

### ISSUE THREAD

**Issue by Apocrathia** [SickGear/SickGear#684]
Every time that I attempt to display the general config page, I am greeted with the following error:

**Error**
tuple index out of range

**Traceback**
Traceback (most recent call last):
File "/home/sickgear/tornado/web.py", line 1417, in _execute result = yield result
File "/home/sickgear/tornado/gen.py", line 920, in run value = future.result()
File "/home/sickgear/tornado/concurrent.py", line 223, in result raise_exc_info(self._exc_info)
File "/home/sickgear/tornado/gen.py", line 235, in wrapper result = func(*args, **kwargs)
File "/home/sickgear/sickbeard/webserve.py", line 307, in get result = method(**kwargss)
File "/home/sickgear/sickbeard/webserve.py", line 3862, in index return t.respond()
File "/home/sickgear/cache/cheetah/_home_sickgear_gui_slick_interfaces_default_config_general_tmpl.py", line 950, in respond _v = ('', VFSL([locals()]+SL+[globals(), builtin],"checked",True))[VFSL([locals()]+SL+[globals(), builtin],"sickbeard.ENCRYPTION_VERSION",True)]
IndexError: tuple index out of range 

I have tried to completely delete my cache and cache.db in order to regenerate them and fix whatever may be causing this, but the error has persisted. Any ideas?

**Comment by JackDandy** [comment]
Hello @Apocrathia 

This sounds like a config.ini imported from another sick* fork as this issue does not occur normally.

Your **config.ini** has an issue with "encryption_version" and should have a line... 
`encryption_version = 0` in the [General] section. Check the file, and if change is needed, exit SG, edit config.ini, edit or add the line, start SG over.

You don't need to delete caches, the Cheetah Template framework is stable and does not need the user to take such a drastic course of action.

Good luck

**Comment by Apocrathia** [comment]
That did it. The value was set to 2. I've been trying to avoid completely rebuilding my instance, but it's looking like I need to. Hopefully this issue will help anyone out on Google with the same problem. Thanks!

**Comment by JackDandy** [comment]
Last tip: You may need to reset your username and password under Interface/Web tab on /config/general/ to remove those previously used values created from the removed encryption_value.
