### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by Siebjee** [SickGear/SickGear#750]
Hi,

When i try to re-scan a show dir i get the error listed below.
Running checkout: bad5c443aa26723b09ca104ebd9741f29c52d143
OS: Ubuntu 16.04.1

```
19:58:02 INFO::SHOWQUEUE-REFRESH :: Performing refresh on Criminal Minds
19:58:02 INFO::SHOWQUEUE-REFRESH :: 75710: Loading all episodes from the show directory /mnt/raid/TV/Criminal Minds
Exception in thread SHOWQUEUE-REFRESH:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/opt/SickGear/sickbeard/show_queue.py", line 503, in run
    self.show.refreshDir()
  File "/opt/SickGear/sickbeard/tv.py", line 1102, in refreshDir
    self.loadEpisodesFromDir()
  File "/opt/SickGear/sickbeard/tv.py", line 414, in loadEpisodesFromDir
    curEpisode = self.makeEpFromFile(ek.ek(os.path.join, self._location, mediaFile))
  File "/opt/SickGear/sickbeard/tv.py", line 698, in makeEpFromFile
    new_quality = Quality.fileQuality(file)
  File "/opt/SickGear/sickbeard/common.py", line 245, in fileQuality
    parser = createParser(filename)
  File "/opt/SickGear/lib/hachoir_parser/guess.py", line 136, in createParser 
    stream = FileInputStream(filename, real_filename, tags=tags)
  File "/opt/SickGear/lib/hachoir_core/stream/input_helper.py", line 17, in FileInputStream 
    inputio = open(real_filename, 'rb')
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 70: ordinal not in range(128)
```

**Comment by JackDandy** [comment]
Hi, @Siebjee 

Can you come to IRC, I need more information,

Thanks.

**Comment by JackDandy** [comment]
Already fixed in develop ;)
