### ISSUE TITLE
Post Processor error: execv() arg 2 must contain only strings

### ISSUE THREAD

**Issue by billyohgren** [SickGear/SickGear#822]
I'm not sure which episode caused this, hopefully the stack trace could help you guys to solve it.

Error

execv() arg 2 must contain only strings

Traceback

Traceback (most recent call last): 
File "/opt/SickGear/tornado/web.py", line 1417, in _execute 
File "/opt/SickGear/tornado/gen.py", line 920, in run 
File "/opt/SickGear/tornado/concurrent.py", line 223, in result 
File "/opt/SickGear/tornado/gen.py", line 235, in wrapper 
File "/opt/SickGear/sickbeard/webserve.py", line 318, in get result = method(**kwargss) 
File "/opt/SickGear/sickbeard/webserve.py", line 2300, in processEpisode showObj=showObj) 
File "/opt/SickGear/sickbeard/processTV.py", line 855, in processDir return ProcessTVShow(webhandler).process_dir(dir_name, nzb_name, process_method, force, force_replace, failed, type, cleanup, showObj) 
File "/opt/SickGear/sickbeard/processTV.py", line 310, in process_dir self._process_media(walk_path, video_pick, nzb_name, process_method, force, force_replace, use_trash=cleanup, showObj=showObj) 
File "/opt/SickGear/sickbeard/processTV.py", line 780, in _process_media file_success = processor.process() 
File "/opt/SickGear/sickbeard/postProcessor.py", line 1006, in process self._copy(**args_cpmv) 
File "/opt/SickGear/sickbeard/postProcessor.py", line 364, in _copy subtitles=subtitles, action_tmpl=action_tmpl) 
File "/opt/SickGear/sickbeard/postProcessor.py", line 322, in _combined_file_operation action(cur_file_path, new_file_path, action_tmpl) 
File "/opt/SickGear/sickbeard/postProcessor.py", line 356, in _int_copy helpers.copyFile(cur_file_path, new_file_path) 
File "/opt/SickGear/sickbeard/helpers.py", line 301, in copyFile subprocess.call(['cp', srcFile, destFile]) 
File "/usr/lib/python2.7/subprocess.py", line 523, in call return Popen(*popenargs, **kwargs).wait() 
File "/usr/lib/python2.7/subprocess.py", line 711, in __init__ errread, errwrite) 
File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child raise child_exception 
TypeError: execv() arg 2 must contain only strings

**Comment by JackDandy** [comment]
Sorry, that doesn't help, essential help on [[How-to] Report Issues](https://github.com/SickGear/SickGear/wiki/%5BHow-to%5D-Report-Issues)

Marking invalid unless you come back with proper details.
