### ISSUE TITLE
Error while searching for new episodes

### ISSUE THREAD

**Issue by joshoram80** [SickGear/SickGear#906]
I am getting the following error when searching for S05E02 of Black Sails on iptorrents.
Using the search URL from the log, there is episodes there, SickGear is just not picking them up.

2017-02-06 15:29:03 INFO     MANUAL-262407 :: Unable to find a download for: [Black Sails - 4x02 - XXX]
2017-02-06 15:29:03 INFO     MANUAL-262407 :: [IPTorrents] :: No episode items in response from https://iptorrents.eu/t?4;5;22;23;24;25;26;55;65;66;78;79;99;q=Black.Sails S04E02;qf=ti;o=seeders#torrents
2017-02-06 15:29:03 ERROR    MANUAL-262407 :: [IPTorrents] :: Failed to parse. Traceback: Traceback (most recent call last):
 ```
1)   File "C:\SickGear\sickbeard\providers\iptorrents.py", line 82, in _search_provider
 2)     with BS4Parser(html, features=['html5lib', 'permissive']) as soup:
 3)   File "C:\SickGear\sickbeard\bs4_parser.py", line 21, in __init__
 4)     self.soup = BeautifulSoup(*args, **kwargs_new)
 5)   File "C:\SickGear\lib\bs4\__init__.py", line 228, in __init__
 6)     self._feed()
 7)   File "C:\SickGear\lib\bs4\__init__.py", line 289, in _feed
 8)     self.builder.feed(self.markup)
 9)   File "C:\SickGear\lib\bs4\builder\_html5lib.py", line 72, in feed
10)     doc = parser.parse(markup, **extra_kwargs)
11)   File "C:\SickGear\lib\html5lib\html5parser.py", line 235, in parse
12)     self._parse(stream, False, None, *args, **kwargs)
13)   File "C:\SickGear\lib\html5lib\html5parser.py", line 85, in _parse
14)     self.tokenizer = _tokenizer.HTMLTokenizer(stream, parser=self, **kwargs)
15)   File "C:\SickGear\lib\html5lib\_tokenizer.py", line 36, in __init__
16)     self.stream = HTMLInputStream(stream, **kwargs)
17)   File "C:\SickGear\lib\html5lib\_inputstream.py", line 151, in HTMLInputStream
18)     return HTMLBinaryInputStream(source, **kwargs)
19) TypeError: __init__() got an unexpected keyword argument 'encoding'

```
2017-02-06 15:29:00 INFO     MANUAL-262407 :: [IPTorrents] :: Performing episode search for Black Sails
2017-02-06 15:29:00 INFO     MANUAL-262407 :: Beginning manual search for: [Black Sails - 4x02 - XXX]

**Comment by JackDandy** [comment]
Delete the file in the base of your sg called, .cleaned. Then restart.

**Comment by JackDandy** [comment]
#908
