### ISSUE TITLE
Errors when path to a show contains utf-8

### ISSUE THREAD

**Issue by MCMic** [SickGear/SickGear#919]
BRANCH: master / COMMIT: b5e771e008ecc78214bfa87414773653842a11f8

When a show is in a path with UTF-8 chars like «é» or «ç», I get this kind of errors in the logs:
`2017-02-22 03:54:53 SHOWQUEUE-UPDATE :: Fatal error executing query: You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings.`

I’m not sure if this is something that needs to get fixed in sickgear code or in my python settings maybe?

**Comment by JackDandy** [comment]
Hello,

Essential help on [[How-to] Report Issues](https://github.com/SickGear/SickGear/wiki/%5BHow-to%5D-Report-Issues)

Please enter details on this thread, no need to open another.

Thanks.

**Comment by MCMic** [comment]
Reproducing steps:
1- Add a show
2- Change folder to one with a é or ç in the name
3- It crashes with this error
4- The same error appear again when it tries to search for episodes for this show

**Comment by JackDandy** [comment]
You cannot simply change a folder name by adding either character you mention, SG wont change the name. Therefore, the steps you said to reproduce the issue appear incorrect (at least on windows).

**Comment by MCMic** [comment]
1- Click on the show
2- Click on edit
3- Go in «Other» tab
4- In «Location for files» click browse
5- Select a folder which name contains an é
6- Click «Update show»

<pre>
Error

You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings.
Traceback

Traceback (most recent call last):
File "/opt/yunohost/sickgear/app/lib/tornado/web.py", line 1469, in _execute result = yield result
File "/opt/yunohost/sickgear/app/lib/tornado/gen.py", line 1034, in run value = future.result()
File "/opt/yunohost/sickgear/app/lib/tornado/concurrent.py", line 237, in result raise_exc_info(self._exc_info)
File "/opt/yunohost/sickgear/app/lib/tornado/gen.py", line 289, in wrapper result = func(*args, **kwargs)
File "/opt/yunohost/sickgear/app/sickbeard/webserve.py", line 314, in get result = method(**kwargss)
File "/opt/yunohost/sickgear/app/sickbeard/webserve.py", line 1866, in editShow showObj.saveToDB()
File "/opt/yunohost/sickgear/app/sickbeard/tv.py", line 1307, in saveToDB myDB.upsert('tv_shows', newValueDict, controlValueDict)
File "/opt/yunohost/sickgear/app/sickbeard/db.py", line 193, in upsert self.action(query, valueDict.values() + keyDict.values())
File "/opt/yunohost/sickgear/app/sickbeard/db.py", line 157, in action sqlResult = self.connection.execute(query, args)
ProgrammingError: You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings. 
</pre>

**Comment by JackDandy** [comment]
Yes, that method was tried, the new folder name was ignored after clicking update.
You're OS locale is set to use utf8 ?

**Comment by MCMic** [comment]
Yeah locale is UTF-8 on a Linux system (debian based)
Folder name is not ignored I get this crash and the change of folder seems to be saved until sickgear is restarted.

I’m pretty sure this problem was not there in SickBeard.
