### ISSUE TITLE
Speed CD provider issues

### ISSUE THREAD

**Issue by pears0** [SickGear/SickGear#928]
Hi,

I've tried configuring Speed.cd as a search provider, but I'm getting the following error when sickgear tries to complete a search:

2017-04-23 22:01:12 INFO     BACKLOG-284210 :: [SpeedCD] :: Performing season pack search for Colony
2017-04-23 22:01:12 DB       BACKLOG-284210 :: [SpeedCD] :: cache.db: SELECT 1 FROM sqlite_master WHERE name = ?; with args ('lastUpdate',)
2017-04-23 22:01:12 DB       BACKLOG-284210 :: [SpeedCD] :: cache.db: SELECT time FROM lastSearch WHERE provider = ? with args ['speedcd']
2017-04-23 22:01:12 DB       BACKLOG-284210 :: [SpeedCD] :: cache.db: SELECT 1 FROM sqlite_master WHERE name = ?; with args ('lastUpdate',)
2017-04-23 22:01:12 DB       BACKLOG-284210 :: [SpeedCD] :: cache.db: SELECT time FROM lastUpdate WHERE provider = ? with args ['speedcd']
2017-04-23 22:01:12 DB       BACKLOG-284210 :: [SpeedCD] :: cache.db: SELECT 1 FROM sqlite_master WHERE name = ?; with args ('lastUpdate',)
2017-04-23 22:01:12 DB       BACKLOG-284210 :: [SpeedCD] :: cache.db: DELETE FROM provider_cache WHERE provider = ? with args ['speedcd']
2017-04-23 22:01:12 DB       BACKLOG-284210 :: [SpeedCD] :: cache.db: SELECT 1 FROM sqlite_master WHERE name = ?; with args ('lastUpdate',)
2017-04-23 22:01:12 DB       BACKLOG-284210 :: [SpeedCD] :: cache.db: SELECT * FROM provider_cache WHERE provider = ? AND indexerid = ? AND season = ? AND episodes LIKE ? with args ['speedcd', 284210, 2, '%|1|%'
]
2017-04-23 22:01:12 DB       BACKLOG-284210 :: [SpeedCD] :: cache.db: SELECT 1 FROM sqlite_master WHERE name = ?; with args ('lastUpdate',)
2017-04-23 22:01:12 DB       BACKLOG-284210 :: [SpeedCD] :: cache.db: UPDATE [lastSearch] SET time = ? WHERE provider = ? with args [1492981272, 'speedcd']
2017-04-23 22:01:12 DB       BACKLOG-284210 :: [SpeedCD] :: sickbeard.db: SELECT show_name FROM scene_exceptions WHERE indexer_id = ? and season = ? with args [284210, -1]
2017-04-23 22:01:12 DB       BACKLOG-284210 :: [SpeedCD] :: sickbeard.db: SELECT show_name FROM scene_exceptions WHERE indexer_id = ? and season = ? with args [284210, -1]
2017-04-23 22:01:12 ERROR    BACKLOG-284210 :: [SpeedCD] :: Error while searching SpeedCD, skipping: dictionary update sequence element #2 has length 4; 2 is required
2017-04-23 22:01:12 DEBUG    BACKLOG-284210 :: [SpeedCD] :: Traceback (most recent call last):
  File "/opt/sickgear/app/sickbeard/search.py", line 522, in search_providers
    try_other_searches=try_other_searches)
  File "/opt/sickgear/app/sickbeard/providers/generic.py", line 447, in find_search_results
    item_list += self._search_provider(cur_param, search_mode=search_mode, epcount=len(episodes))
  File "/opt/sickgear/app/sickbeard/providers/speedcd.py", line 55, in _search_provider
    if not self._authorised():
  File "/opt/sickgear/app/sickbeard/providers/speedcd.py", line 50, in _authorised
    failed_msg=(lambda y=None: u'Invalid cookie details for %s. Check settings'))
  File "/opt/sickgear/app/sickbeard/providers/generic.py", line 1022, in _authorised
    success, msg = self._check_cookie()
  File "/opt/sickgear/app/sickbeard/providers/generic.py", line 663, in _check_cookie
    if self.check_auth_cookie():
  File "/opt/sickgear/app/sickbeard/providers/generic.py", line 654, in check_auth_cookie
    if x != ''])),
ValueError: dictionary update sequence element #2 has length 4; 2 is required

Can you help, this appears to be a bug, but may be wrong as I don't have a working knowledge of python.

**Comment by JackDandy** [comment]
Looks like you haven't set up your cookie details correctly.. see wiki, 2nd item.

> dictionary update sequence element #2 has length 4; 2 is required

and also see the tip under the cookie setting for that provider.

**Comment by pears0** [comment]
I have set the 2 cookies that appear to be correct (the tool tip is currently in correct as only 1 of the cookies is available). The 2 I tried are:

__cfduid and inSpeed_speedian. The only other one that I can see is inSpeed_ssl

With these in place I now get an invalid cookie detail error:

2017-04-24 10:45:02 BACKLOG-263365 :: [SpeedCD] :: Invalid cookie details for SpeedCD. Check settings
2017-04-24 10:44:59 BACKLOG-114801 :: [SpeedCD] :: Invalid cookie details for SpeedCD. Check settings
2017-04-24 10:44:56 BACKLOG-114801 :: [SpeedCD] :: Invalid cookie details for SpeedCD. Check settings
2017-04-24 10:44:53 BACKLOG-114801 :: [SpeedCD] :: Invalid cookie details for SpeedCD. Check settings
2017-04-24 10:44:50 BACKLOG-114801 :: [SpeedCD] :: Invalid cookie details for SpeedCD. Check settings
2017-04-24 10:44:47 BACKLOG-114801 :: [SpeedCD] :: Invalid cookie details for SpeedCD. Check settings
2017-04-24 10:44:44 BACKLOG-114801 :: [SpeedCD] :: Invalid cookie details for SpeedCD. Check settings
2017-04-24 10:44:41 BACKLOG-114801 :: [SpeedCD] :: Invalid cookie details for SpeedCD. Check settings

I do not believe that this is working correctly at this time. (Note that the Speed CD team have recently been changing over servers and server setup, so it's likely that the code is now out of date to the tracker setup.

**Comment by JackDandy** [comment]
Like i said, tests were done and it works, therfore you have done something wrong or you are not on the latest build of SG.
<img src=https://vgy.me/Z5vha1.png>

**Comment by pears0** [comment]
Tell me what I might be doing wrong then. I don't have your knowledge of the system, and the log is basically useless at telling me where the issue might be.

As I also pointed out, the key at the bottom as shown in your screen shot show's cookies that are not available on my side (Specifically inSpeed_uid). Am I supposed to get this another way?

**Comment by JackDandy** [comment]
How can the log be "_useless_" when it is clearly telling you, "Invalid cookie details for SpeedCD".

Try a different browser to get the cookies, I got them myself only last night so you have something wrong locally. As I said, make sure you are the latest SG. There is no issue here. This thread will now be locked. If you want assistance, come to IRC.

**Comment by JackDandy** [comment]
ok, so i did another test, i see that they removed one of the cookies, but if you still follow the tip and add it, it will work

**Comment by JackDandy** [comment]
https://github.com/SickGear/SickGear/releases/tag/release_0.12.13
