### ISSUE TITLE
Error after system crash: database disk image is malformed

### ISSUE THREAD

**Issue by barbequesauce** [SickGear/SickGear#951]
Hi - I had a system crash today and had to restore from a dd image. On resumption, I'm getting this error in the log as it works through the backlog - once with each provider. Any ideas on a remedy?

```
2017-07-07 16:30:19 BACKLOG-257655 :: [omgwtfnzbs] :: Fatal error executing query: database disk image is malformed
2017-07-07 16:30:19 BACKLOG-257655 :: [omgwtfnzbs] :: Error while searching omgwtfnzbs, skipping: database disk image is malformed
2017-07-07 16:30:19 BACKLOG-257655 :: [omgwtfnzbs] :: Traceback (most recent call last):
  File "/opt/sickgear/app/sickbeard/search.py", line 521, in search_providers
    cur_provider.cache._clearCache()
  File "/opt/sickgear/app/sickbeard/tvcache.py", line 63, in _clearCache
    myDB.action('DELETE FROM provider_cache WHERE provider = ?', [self.providerID])
  File "/opt/sickgear/app/sickbeard/db.py", line 157, in action
    sqlResult = self.connection.execute(query, args)
DatabaseError: database disk image is malformed

2017-07-07 16:28:34 BACKLOG-257655 :: [LimeTorrents] :: Fatal error executing query: database disk image is malformed

```

**Comment by JackDandy** [comment]
Your SG db is corrupt. start over or restore your main sickbeard.db from a backup.
