### ISSUE TITLE
Show folder doesn't exist, you shouldn't be using it errors

### ISSUE THREAD

**Issue by jabbyjim** [SickGear/SickGear#990]
after upgrade to BRANCH: master / COMMIT: da1cab1e3930bb56aacdefcc71ebae6bf8cf75f4

**Expectation**: process media
**Result**: media not getting processed, exception error saying folder does not exist (when source and destination does.. and this worked before upgrade). Now shows are not getting processed anymore, everything else appears to work as before.

To reproduce, click [manage] then [process media] then [process]

```
Error
Show folder doesn't exist, you shouldn't be using it

Traceback

Traceback (most recent call last): 
File "/home/SickGear/tornado/web.py", line 1417, in _execute 
File "/home/SickGear/tornado/gen.py", line 920, in run 
File "/home/SickGear/tornado/concurrent.py", line 223, in result 
File "/home/SickGear/tornado/gen.py", line 235, in wrapper 
File "/home/SickGear/sickbeard/webserve.py", line 314, in get result = method(**kwargss) 
File "/home/SickGear/sickbeard/webserve.py", line 2529, in processEpisode showObj=showObj) 
File "/home/SickGear/sickbeard/processTV.py", line 855, in processDir return ProcessTVShow(webhandler).process_dir(dir_name, nzb_name, process_method, force, force_replace, failed, type, cleanup, showObj) 
File "/home/SickGear/sickbeard/processTV.py", line 261, in process_dir self._process_media(path, video_pick, nzb_name, process_method, force, force_replace, use_trash=cleanup, showObj=showObj) 
File "/home/SickGear/sickbeard/processTV.py", line 780, in _process_media file_success = processor.process() 
File "/home/SickGear/sickbeard/postProcessor.py", line 894, in process if not ek.ek(os.path.isdir, ep_obj.show.location) and sickbeard.CREATE_MISSING_SHOW_DIRS: 
File "/home/SickGear/sickbeard/tv.py", line 205, in _getLocation raise exceptions.ShowDirNotFoundException('Show folder doesn\'t exist, you shouldn\'t be using it') 
ShowDirNotFoundException: Show folder doesn't exist, you shouldn't be using it 

----------------

2017-09-26 18:36:15 ERROR    TORNADO.APP :: Uncaught exception POST /home/postprocess/processEpisode (192.168.15.113)
 1) HTTPServerRequest(protocol='http', host='test.test.biz:8081', method='POST', uri='/home/postprocess/processEpisode', version='HTTP/1.1', remote_ip='192.168.15.113', headers={'Origin': 'http://test.test.biz:8081', 'Content-Length': '94', 'Accept-Language': 'en-US,en;q=0.8', 'Accept-Encoding': 'gzip, deflate', 'Host': 'test.test.biz:8081', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'Upgrade-Insecure-Requests': '1', 'Connection': 'keep-alive', 'Referer': 'http://test.test.biz:8081/home/postprocess/', 'Cache-Control': 'max-age=0', 'Cookie': 'advanced_toggle_checked=1; wanted_view=list; manage_view=list; user="2|1:0|10:1506387659|4:user|44:NTBjZWU5NGFlZjdkNDQyNzk2ZjhmMWE4MjFhMDk2YmM=|d8201996e4f8106a6756597363d20557e3384797ab940db94f34568276ccec06"; snatched_view=list; soon_view=thumb; suggest_view=thumb; late_view=list; blu_ray_com_new_releases_view=thumb; imdb_box_office_view=thumb; imdb_top_dvd_rentals_view=thumb; imdb_top_250_movies_view=thumb; sickgear-session-005912512ace23b1ed2c2474afe04491="2|1:0|10:1506465068|49:sickgear-session-005912512ace23b1ed2c2474afe04491|60:R2U0KzN0bE5RZStZckgwTzBMQURIS0NyWnZURGEwMHFqMk52ekdxVmxHZz0=|fa5048dc283719b3143fde12f7d5d05fdf7d541623623e9c911d37daeae5dda6"', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36', 'Content-Type': 'application/x-www-form-urlencoded'})
 2) Traceback (most recent call last):
 3)   File "/home/SickGear/tornado/web.py", line 1417, in _execute
 4)   File "/home/SickGear/tornado/gen.py", line 920, in run
 5)   File "/home/SickGear/tornado/concurrent.py", line 223, in result
 6)   File "/home/SickGear/tornado/gen.py", line 235, in wrapper
 7)   File "/home/SickGear/sickbeard/webserve.py", line 314, in get
 8)     result = method(**kwargss)
 9)   File "/home/SickGear/sickbeard/webserve.py", line 2529, in processEpisode
10)     showObj=showObj)
11)   File "/home/SickGear/sickbeard/processTV.py", line 855, in processDir
12)     return ProcessTVShow(webhandler).process_dir(dir_name, nzb_name, process_method, force, force_replace, failed, type, cleanup, showObj)
13)   File "/home/SickGear/sickbeard/processTV.py", line 261, in process_dir
14)     self._process_media(path, video_pick, nzb_name, process_method, force, force_replace, use_trash=cleanup, showObj=showObj)
15)   File "/home/SickGear/sickbeard/processTV.py", line 780, in _process_media
16)     file_success = processor.process()
17)   File "/home/SickGear/sickbeard/postProcessor.py", line 894, in process
18)     if not ek.ek(os.path.isdir, ep_obj.show.location) and sickbeard.CREATE_MISSING_SHOW_DIRS:
19)   File "/home/SickGear/sickbeard/tv.py", line 205, in _getLocation
20)     raise exceptions.ShowDirNotFoundException('Show folder doesn\'t exist, you shouldn\'t be using it')
21) ShowDirNotFoundException: Show folder doesn't exist, you shouldn't be using it
```

**Comment by JackDandy** [comment]
Sounds like you need to display the show concerned in the browser, check if the path is highlighted red, if yes, click the edit btn, and finally update its folder location so that the red turns back to the normal color.

**Comment by rollemira** [comment]
Is it possible to add a filter to see which shows might be in this state? Or even better, an option under config/postprocessing to enable creation of folders that don't exist automatically?

I realize that option would require the correct permissions. My setup has the correct permissions where the folder could be created by the postprocessor automatically.

**Comment by JackDandy** [comment]
hi @rollemira 

in the config.ini there is an option that may work for you... try to find and set `create_missing_show_dirs = 1`

**Comment by rollemira** [comment]
Many thanks JackDandy!
