### ISSUE TITLE
Removing duplicated show results in episode page listing errors

### ISSUE THREAD

**Issue by tomwitt2** [SickGear/SickGear#991]
Version:  BRANCH: master / COMMIT: e96f5420216cd32ddc0576ed69e4c3d743e3dc2b

What happened:  Quite awhile ago I had added "Star Trek: Discovery" to my shows (when I'd first read about it).  Sick Gear found the show, created the directory and, as the showed neared airtime, never updated the "Next Episode" start date.

The first show date came and went and there were still no updates to my listing of Star Trek: Discovery; no episode listings, no next episode date.

I visited the Trakt cards and saw that Star Trek: Discovery was listed and I was offered the opportunity to add the show, so I did.  Now I had two listings for Star Trek: Discovery; luckily, there were writing to directories on separate drives.

The new, Trakt version of ST:D (... unfortunate acronym) had episode listings and next episode dates so I decided to delete the original show for ST:D.  

The deletion was apparently successful. Unfortunately, the logs are no longer available for the deletion.

The new ST:D appears to be updating.

<pre>
2017-10-02 05:23:50 INFO     SHOWQUEUE-UPDATE :: Beginning update of Star Trek: Discovery
2017-10-02 05:23:50 DEBUG    SHOWQUEUE-UPDATE :: Retrieving show info from TheTVDB
2017-10-02 05:23:50 INFO     SHOWQUEUE-UPDATE :: 328711: Loading show info from TheTVDB
2017-10-02 05:23:50 DEBUG    SHOWQUEUE-UPDATE :: TVDB_API :: Configured language en override show language of en
2017-10-02 05:23:50 DEBUG    SHOWQUEUE-UPDATE :: TVDB_API :: Getting all series data for 328711
2017-10-02 05:23:50 DEBUG    SHOWQUEUE-UPDATE :: TVDB_API :: Retrieving URL http://thetvdb.com/api/<apikey>/series/328711/en.xml
2017-10-02 05:23:50 DEBUG    SHOWQUEUE-UPDATE :: 328711: Saving show info to database
2017-10-02 05:23:50 DB       SHOWQUEUE-UPDATE :: sickbeard.db: UPDATE [tv_shows] SET rls_ignore_words = ?, rls_require_words = ?, classification = ?, overview = ?, scene = ?, paused = ?, tag = ?, quality = ?, last_update_indexer = ?, net
work = ?, indexer = ?, sports = ?, airs = ?, location = ?, status = ?, archive_firstmatch = ?, startyear = ?, dvdorder = ?, imdb_id = ?, flatten_folders = ?, genre = ?, subtitles = ?, lang = ?, show_name = ?, air_by_date = ?, anime = ?, runtime = ? WHERE indexer_id = ? with args ['', '', 'Scripted', u"Set roughly ten years before the events of the original Star Trek, the series follows the crew of the USS Discovery as they discover new worlds and civilizations, while exploring the franchise's signature contemporary themes. The season-long story line revolves around an incident and an event in Star Trek history that's been talked about but never been explored.", 0, 0, 'Show List', 22282404, 736603, u'CBS All Access', 1, 0, u'Sunday 8:30 PM', u'/home/user1/mounts/sd2_bafs/Managed/TV Shows/Star Trek Discovery', u'Continuing', 0, 2017, 0, u'tt5171438', 0, u'|Science-Fiction|', 1, 'en', u'Star Trek: Discovery', 0, 0, u'45', 328711]
2017-10-02 05:23:50 DB       SHOWQUEUE-UPDATE :: sickbeard.db: UPDATE [imdb_info] SET rating = ?, votes = ?, countries = ?, title = ?, genres = ?, imdb_id = ?, country_codes = ?, year = ?, certificates = ?, runtimes = ?, akas = ?, last_update = ? WHERE indexer_id = ? with args [7.2, 10441, u'USA', u'Star Trek: Discovery', u'Sci-Fi', u'tt5171438', u'us', 2017, u'TV-MA', u'60', u'\u0417\u0432\u0451\u0437\u0434\u043d\u044b\u0439 \u043f\u0443\u0442\u044c: \u0414\u0438\u0441\u043a\u0430\u0432\u0435\u0440\u0438::Russia|Star Trek: Discovery::Brazil (imdb display title)|Star Trek: Discovery::Spain (imdb display title)', 736604, 328711]
</pre>

Now, however, when I click on the remaining show ST:D to view the episodes, I get this error.

<pre>
Error

Language does not exist

Traceback

Traceback (most recent call last): 
File "/home/user1/.sickgear/tornado/web.py", line 1417, in _execute 
File "/home/user1/.sickgear/tornado/gen.py", line 920, in run 
File "/home/user1/.sickgear/tornado/concurrent.py", line 223, in result 
File "/home/user1/.sickgear/tornado/gen.py", line 235, in wrapper 
File "/home/user1/.sickgear/sickbeard/webserve.py", line 314, in get result = method(**kwargss) 
File "/home/user1/.sickgear/sickbeard/webserve.py", line 1486, in displayShow return t.respond() 
File "/home/user1/.sickgear/cache/cheetah/_home_user1__sickgear_gui_slick_interfaces_default_displayShow_tmpl.py", line 1010, in respond self._handleCheetahInclude(VFN(VFFSL(SL,"os.path",True),"join",False)(VFFSL(SL,"sg_str",False)('PROG_DIR'), 'gui/slick/interfaces/default/inc_displayShow.tmpl'), trans=trans, includeFrom="file", raw=False) 
File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1615, in _handleCheetahInclude self._CHEETAH__cheetahIncludes[_includeID].respond(trans) 
File "_home_user1__sickgear_gui_slick_interfaces_default_inc_displayShow_tmpl.py", line 292, in respond 
File "/home/user1/.sickgear/lib/subliminal/language.py", line 1034, in __init__ items.append(Language(i, languages=languages, strict=strict)) 
File "/home/user1/.sickgear/lib/subliminal/language.py", line 884, in __init__ raise ValueError('Language %s does not exist' % language) 
ValueError: Language does not exist 

Request Info

body: 
files: {}
protocol: http
connection: 
body_arguments: {}
uri: /home/displayShow?show=328711
query_arguments: {'show': ['328711']}
_start_time: 1506957976.97
headers: {'Accept-Language': 'en-US,en;q=0.8', 'Accept-Encoding': 'gzip, deflate, br', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36', 'Host': 'localhost:10481', 'Referer': 'http://localhost:10481/home/showlistView/', 'Cookie': 'ys-torrentGrid=o%3Acolumns%3Da%253Ao%25253Aid%25253Ds%2525253Aqueue%25255Ewidth%25253Dn%2525253A30%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Ds%2525253Aname%25255Ewidth%25253Dn%2525253A891%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A2%25255Ewidth%25253Dn%2525253A75%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A3%25255Ewidth%25253Dn%2525253A150%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A7%25255Ewidth%25253Dn%2525253A60%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A8%25255Ewidth%25253Dn%2525253A60%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A4%25255Ewidth%25253Dn%2525253A80%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A5%25255Ewidth%25253Dn%2525253A80%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A6%25255Ewidth%25253Dn%2525253A60%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A12%25255Ewidth%25253Dn%2525253A120%25255Ehidden%25253Db%2525253A1%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A13%25255Ewidth%25253Dn%2525253A120%25255Ehidden%25253Db%2525253A1%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A14%25255Ewidth%25253Dn%2525253A75%25255Ehidden%25253Db%2525253A1%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A15%25255Ewidth%25253Dn%2525253A75%25255Ehidden%25253Db%2525253A1%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A16%25255Ewidth%25253Dn%2525253A75%25255Ehidden%25253Db%2525253A1%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A17%25255Ewidth%25253Dn%2525253A75%25255Ehidden%25253Db%2525253A1%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A18%25255Ewidth%25253Dn%2525253A75%25255Ehidden%25253Db%2525253A1%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A10%25255Ewidth%25253Dn%2525253A60%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A9%25255Ewidth%25253Dn%2525253A60%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A11%25255Ewidth%25253Dn%2525253A80%25255Esortable%25253Db%2525253A1%255Eo%25253Aid%25253Dn%2525253A19%25255Ewidth%25253Dn%2525253A100%25255Ehidden%25253Db%2525253A1%5Esort%3Do%253Afield%253Ds%25253Aqueue%255Edirection%253Ds%25253AASC; ys-detailsPanel=o%3Aheight%3Dn%253A397', 'Upgrade-Insecure-Requests': '1'}
host: localhost:10481
version: HTTP/1.1
arguments: {'show': '328711'}
_finish_time: None
query: show=328711
path: /home/displayShow
method: GET
remote_ip: 192.168.1.XXX
</pre>

**Comment by JackDandy** [comment]
I suggest you go Config/General/Advanced, and switch to "develop". There has been a lot of change there and this type of scenario has been covered.

**Comment by itachemy** [comment]
BRANCH: develop / COMMIT: 76f766fb5d8fbd7f27f16a97ce0326ea91aec62d

Same scenario, same issue with the same show. I switched to Dev branch, but still getting the same error:

```
2017-10-18 15:21:59 ERROR    TORNADO.APP :: Uncaught exception GET /home/displayShow?show=328711 (192.168.0.242)
 1) HTTPServerRequest(protocol='http', host='192.168.0.30:8081', method='GET', uri='/home/displayShow?show=328711', version='HTTP/1.1', remote_ip='192.168.0.242', headers={'Accept-Language': 'en-us', 'Accept-Encoding': 'gzip', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Upgrade-Insecure-Requests': '1', 'Host': '192.168.0.30:8081', 'Referer': 'http://192.168.0.30:8081/home/showlistView/', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38'})
 2) Traceback (most recent call last):
 3)   File "/opt/sickgear/app/lib/tornado/web.py", line 1511, in _execute
 4)     result = yield result
 5)   File "/opt/sickgear/app/lib/tornado/gen.py", line 1055, in run
 6)     value = future.result()
 7)   File "/opt/sickgear/app/lib/tornado/concurrent.py", line 238, in result
 8)     raise_exc_info(self._exc_info)
 9)   File "/opt/sickgear/app/lib/tornado/gen.py", line 292, in wrapper
10)     result = func(*args, **kwargs)
11)   File "/opt/sickgear/app/sickbeard/webserve.py", line 319, in get
12)     result = method(**kwargss)
13)   File "/opt/sickgear/app/sickbeard/webserve.py", line 1506, in displayShow
14)     return t.respond()
15)   File "/opt/sickgear/data/cache/cheetah/_opt_sickgear_app_gui_slick_interfaces_default_displayShow_tmpl.py", line 1010, in respond
16)     self._handleCheetahInclude(VFN(VFFSL(SL,"os.path",True),"join",False)(VFFSL(SL,"sg_str",False)('PROG_DIR'), 'gui/slick/interfaces/default/inc_displayShow.tmpl'), trans=trans, includeFrom="file", raw=False)
17)   File "/opt/sickgear/.pyenv/versions/2.7.13/lib/python2.7/site-packages/Cheetah/Template.py", line 1615, in _handleCheetahInclude
18)     self._CHEETAH__cheetahIncludes[_includeID].respond(trans)
19)   File "_opt_sickgear_app_gui_slick_interfaces_default_inc_displayShow_tmpl.py", line 292, in respond
20)   File "/opt/sickgear/app/lib/subliminal/language.py", line 1034, in __init__
21)     items.append(Language(i, languages=languages, strict=strict))
22)   File "/opt/sickgear/app/lib/subliminal/language.py", line 884, in __init__
23)     raise ValueError('Language %s does not exist' % language)
24) ValueError: Language  does not exist
```

**Comment by JackDandy** [comment]
Not enough data for me to replicate. 

Essential help on [[How-to] Report Issues](https://github.com/SickGear/SickGear/wiki/%5BHow-to%5D-Report-Issues)

Thanks.

**Comment by itachemy** [comment]
# BRANCH: develop / COMMIT: 76f766fb5d8fbd7f27f16a97ce0326ea91aec62d


Expectation | Result
------------ | -------------
Added Star Trek: Discovery before show actually started. Once show started and episodes were downloaded, wanted to access information about the show from the Show List. | When trying to access the show informations, I get an error in my web browser, saying the "Language Does not Exist"

**Steps to reproduce:**
*1)* Click "Shows" drop down and choose "Show List"
*2)* In "Show List" click on listing for "Star Trek: Discovery"

Web Browser Error:
<pre>
Error

Language does not exist

Traceback

Traceback (most recent call last): 
File "/opt/sickgear/app/lib/tornado/web.py", line 1511, in _execute result = yield result 
File "/opt/sickgear/app/lib/tornado/gen.py", line 1055, in run value = future.result() 
File "/opt/sickgear/app/lib/tornado/concurrent.py", line 238, in result raise_exc_info(self._exc_info) 
File "/opt/sickgear/app/lib/tornado/gen.py", line 292, in wrapper result = func(*args, **kwargs) 
File "/opt/sickgear/app/sickbeard/webserve.py", line 319, in get result = method(**kwargss) 
File "/opt/sickgear/app/sickbeard/webserve.py", line 1506, in displayShow return t.respond() 
File "/opt/sickgear/data/cache/cheetah/_opt_sickgear_app_gui_slick_interfaces_default_displayShow_tmpl.py", line 1010, in respond self._handleCheetahInclude(VFN(VFFSL(SL,"os.path",True),"join",False)(VFFSL(SL,"sg_str",False)('PROG_DIR'), 'gui/slick/interfaces/default/inc_displayShow.tmpl'), trans=trans, includeFrom="file", raw=False) 
File "/opt/sickgear/.pyenv/versions/2.7.13/lib/python2.7/site-packages/Cheetah/Template.py", line 1615, in _handleCheetahInclude self._CHEETAH__cheetahIncludes[_includeID].respond(trans) 
File "_opt_sickgear_app_gui_slick_interfaces_default_inc_displayShow_tmpl.py", line 292, in respond 
File "/opt/sickgear/app/lib/subliminal/language.py", line 1034, in __init__ items.append(Language(i, languages=languages, strict=strict)) 
File "/opt/sickgear/app/lib/subliminal/language.py", line 884, in __init__ raise ValueError('Language %s does not exist' % language) 
ValueError: Language does not exist 
</pre>

Logs Set to "Db and next 4 levels"

<pre>
2017-10-19 15:27:49 DB       TORNADO :: sickbeard.db: SELECT (SELECT COUNT(*) FROM tv_episodes WHERE season > 0 AND episode > 0 AND airdate > 1 AND status IN (2,3276802,202,402,102,802,12802,25602,1602,3202,102402,6402,9,3276809,209,409,109,809,12809,25609,1609,3209,102409,6409)) AS ep_snatched, (SELECT COUNT(*) FROM tv_episodes WHERE season > 0 AND episode > 0 AND airdate > 1 AND status IN (4,3276804,204,404,104,804,12804,25604,1604,3204,102404,6404,6)) AS ep_downloaded, (SELECT COUNT(*) FROM tv_episodes WHERE season > 0 AND episode > 0 AND airdate > 1  AND ((airdate <= 736621 AND (status = 5 OR status = 3))  OR (status IN (2,3276802,202,402,102,802,12802,25602,1602,3202,102402,6402,9,3276809,209,409,109,809,12809,25609,1609,3209,102409,6409)) OR (status IN (4,3276804,204,404,104,804,12804,25604,1604,3204,102404,6404,6)))) AS ep_total FROM tv_episodes tv_eps LIMIT 1
2017-10-19 15:27:42 ERROR    TORNADO.APP :: Uncaught exception GET /home/displayShow?show=328711 (192.168.0.242)
 1) HTTPServerRequest(protocol='http', host='192.168.0.30:8081', method='GET', uri='/home/displayShow?show=328711', version='HTTP/1.1', remote_ip='192.168.0.242', headers={'Accept-Language': 'en-us', 'Accept-Encoding': 'gzip', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Upgrade-Insecure-Requests': '1', 'Host': '192.168.0.30:8081', 'Referer': 'http://192.168.0.30:8081/home/showlistView/', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38'})
 2) Traceback (most recent call last):
 3)   File "/opt/sickgear/app/lib/tornado/web.py", line 1511, in _execute
 4)     result = yield result
 5)   File "/opt/sickgear/app/lib/tornado/gen.py", line 1055, in run
 6)     value = future.result()
 7)   File "/opt/sickgear/app/lib/tornado/concurrent.py", line 238, in result
 8)     raise_exc_info(self._exc_info)
 9)   File "/opt/sickgear/app/lib/tornado/gen.py", line 292, in wrapper
10)     result = func(*args, **kwargs)
11)   File "/opt/sickgear/app/sickbeard/webserve.py", line 319, in get
12)     result = method(**kwargss)
13)   File "/opt/sickgear/app/sickbeard/webserve.py", line 1506, in displayShow
14)     return t.respond()
15)   File "/opt/sickgear/data/cache/cheetah/_opt_sickgear_app_gui_slick_interfaces_default_displayShow_tmpl.py", line 1010, in respond
16)     self._handleCheetahInclude(VFN(VFFSL(SL,"os.path",True),"join",False)(VFFSL(SL,"sg_str",False)('PROG_DIR'), 'gui/slick/interfaces/default/inc_displayShow.tmpl'), trans=trans, includeFrom="file", raw=False)
17)   File "/opt/sickgear/.pyenv/versions/2.7.13/lib/python2.7/site-packages/Cheetah/Template.py", line 1615, in _handleCheetahInclude
18)     self._CHEETAH__cheetahIncludes[_includeID].respond(trans)
19)   File "_opt_sickgear_app_gui_slick_interfaces_default_inc_displayShow_tmpl.py", line 292, in respond
20)   File "/opt/sickgear/app/lib/subliminal/language.py", line 1034, in __init__
21)     items.append(Language(i, languages=languages, strict=strict))
22)   File "/opt/sickgear/app/lib/subliminal/language.py", line 884, in __init__
23)     raise ValueError('Language %s does not exist' % language)
24) ValueError: Language  does not exist
</pre>

**Comment by JackDandy** [comment]
thanks,
1) what do you have for your subtitle settings ? 
2) when you added the show, what lang did you select?

**Comment by JackDandy** [comment]
This issue could have been resolved a long time ago, it's easy to see where the error is being generated in the code, but with no context as to why the error is raised, then I can only assume it is there for good reason, therefore, I cannot call this a bug and I have nothing to fix.

**Comment by itachemy** [comment]
1. The language used in English in Subtitle search.
2. When adding a show, English is used.
3. Since I can't access the show to access edit settings, I would ASSume that the subtitle settings are checked.

While using the Development build, things went wonky and shows were incorrectly being added with the wrong names. So I blew out SickGear, reinstalled and re-added my shows. The issue with Star Trek Discovery still exists as before.

**Comment by itachemy** [comment]
Lastly, I appreciate your looking into this weird issue. I understand the frustration of having to work with end-users who don't have the time timeliness you expect, with all the other frustrations (to put it mildly) that SickGear has had to deal with the last few months, along with trying to have a life outside of SG. Your time is valuable.

**Comment by JackDandy** [comment]
@itachemy 
use this link for [direct support](https://gitter.im/SickGear/Lobby/~chat#share)

**Comment by tomwitt2** [comment]
I had pretty much the same experience as itachemy. 
1. I switched to the development branch.
2. I applied the most recent updates (when told I was multiple versions behind the github current version).
Attempts to apply updates failed with scary messages about object not having a _getitem property (exact message was lost).
3. Incoming shows started being added to the last successfully moved show after the update was attempted (Most recent Get Shorty episode added successfully, the next incoming show "Dirk Gently" was added as Get Shorty episode,  the next incoming Survivor episode was also added as a Get Shorty episode)

I also recently changed my subtitles retrieval setting to now attempt downloading subtitles; I wasn't previously downloading subtitles.

**Comment by JackDandy** [comment]
Instead of turning more things on, it is more useful to keep turning things off until you get back to normality, then slowly turn things on until you can replicate what you are saying because I simply cannot get any issue here. And in order for me to help you, you need to work this out instead of just saying what is not working for you - which is no use at this point for me, or more importantly for you.

**Comment by JackDandy** [comment]
For realtime help on this issue, in your browser come to : https://gitter.im/SickGear/Lobby and sign in with git account or if you prefer sickgear @ slack

**Comment by JackDandy** [comment]
[Fixed](https://github.com/SickGear/SickGear/releases/tag/release_0.14.4)
